### PR TITLE
[16.0][MIG] account_menu_invoice_refund: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
#1250 
Migration account_menu_invoice_refund module from v13

### CODE REVIEW

**Review by flotho — APPROVED** [review]
LGTM

**Comment by RodrigoBM** [comment]
@rafaelbn can you check it?

**Comment by rafaelbn** [comment]
Well, this is not useful in my side, you have the same objetive just clicking in the name of the journal, I've never used this module. It's OK for me if you like 😄 but we will not use this one this time! ❤️  PD: too much menus to add more to the users! 😃

**Comment by rafaelbn** [comment]
Just testing to check if runbot works!

**Comment by RodrigoBM** [comment]
@rafaelbn why rebase? it would not be the command "/ocabot merge patch". I have applied rebase in my branch

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by legalsylvain** [comment]
Hi. I try to create a custom module that depends on account_menu_invoice_refund (V16)

The CI of my repo is red, because it can not install the module. 
I took a look on pypi, and the module is not present on pypi : 
- See : KO V16 : https://pypi.org/project/odoo16-addon-account-menu-invoice-refund/
- See : OK V12 : https://pypi.org/project/odoo12-addon-account-menu-invoice-refund/

Do you know why the module is not available on pypi ? CC : @sbidoul , do you know how to investigate ? 

thanks !

**Comment by sbidoul** [comment]
@legalsylvain It's https://pypi.org/project/odoo-addon-account-menu-invoice-refund (we stopped adding the series number in the package name when the pip resolver became smart enough to handle that, starting with Odoo 15).

**Comment by legalsylvain** [comment]
> @legalsylvain It's https://pypi.org/project/odoo-addon-account-menu-invoice-refund (we stopped adding the series number in the package name when the pip resolver became smart enough to handle that, starting with Odoo 15).

thanks @sbidoul for your explanation and your reactivity.

**Pull request merged**
