### PR TITLE
[15.0][MIG] account_move_tier_validation

### PR DESCRIPTION
**Pull request by vvrossem**

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by JasminSForgeFlow — APPROVED** [review]
LGTM!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Comment by AaronHForgeFlow** [comment]
/ocabot merge nobump  trying again, seems build failed due to an unrelated thing

**Pull request merged**
