### PR TITLE
[12.0] [MIG] account_invoice_merge

### PR DESCRIPTION
**Pull request by sylvainvh**
Migration of the module account_invoice_merge

### CODE REVIEW

**Comment by sylvainvh** [comment]
Hi @pedrobaeza , I remark that I push on the wrong branch. I pushed on my branch 12. Do you want that I close my current PR and I recreate a new one ?

**Comment by pedrobaeza** [comment]
This can be valid while you don't change that branch while the PR is opened, so you decide.

**Comment by mourad-ehm** [comment]
Hi @sylvainvh @pedrobaeza , 
What's about this PR ? what is the right repository ?

**Comment by AaronHForgeFlow** [comment]
The name of the branch is not relevant, it is fine as it is.

**Comment by mourad-ehm** [comment]
Why this pr is closed ? 
This module has been moved to another repository ?

**Pull request closed without merging**
