### PR TITLE
[14.0][FIX] account_invoice_refund_reason: refund and new draft invoice

### PR DESCRIPTION
**Pull request by JaumeBforgeFlow**
Forward Port of #1335

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
Hi @JaumeBforgeFlow 

Could you fix the PR you are forwarding (it seems incorrect)? Also could you FW to V15 as well? Thanks! :)

**Comment by JordiMForgeFlow** [comment]
@AaronHForgeFlow could we merge this FW? comes from https://github.com/OCA/account-invoicing/pull/1355

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
@JordiMForgeFlow do you know if forward port to 15.0 is needed?

**Comment by JordiMForgeFlow** [comment]
@AaronHForgeFlow it was already considered in the migration :) https://github.com/OCA/account-invoicing/pull/1324#issuecomment-1405253400

**Comment by AaronHForgeFlow** [comment]
> @AaronHForgeFlow it was already considered in the migration :) [#1324 (comment)](https://github.com/OCA/account-invoicing/pull/1324#issuecomment-1405253400)

Great! Thanks :)

**Pull request merged**
