### PR TITLE
[12.0][MIG] account_move_tier_validation: Migration from 14.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @douglascstd @rvalyi

**Review by douglascstd — CHANGES_REQUESTED** [review]
The model selection allows to select any model, it may cause an error. The suggestion is add a domain to restrict the selection to the **account.move** **model** only.
### Follow example from this PR:
image

This is the domain applied on v14 (source):
image

### The process tested:
- Then the account.move is created by an invoice, the tier validation is bypassed. **OK**
image

- Single Journal Entry: **OK**
image

image
image
image
image

**Comment by sergiocorato** [comment]
@marcelsavegnago This branch is now upgraded to copier (see #1285 ), so please rebase to re-launch tests.

**Comment by marcelsavegnago** [comment]
all green :)

**Comment by marcelsavegnago** [comment]
> The model selection allows to select any model, it may cause an error. The suggestion is add a domain to restrict the selection to the **account.move** **model** only.

@douglascstd 

image

**Comment by marcelsavegnago** [comment]
cc @kaynnan @WesleyOliveira98

**Pull request closed without merging**
