### PR TITLE
[13.0][IMP] account_invoice_refund_reason: active and description fields

### PR DESCRIPTION
**Pull request by JaumeBforgeFlow**
Adds a description field for refund reasons, the ability to archive them and updates to the view.

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JordiMForgeFlow — APPROVED** [review]
Code review LGTM 👍🏼

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM :+1: :smile:

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Can you do the forward ports?

**Pull request merged**
