### PR TITLE
[15.0][MIG] `account_invoice_transmit_method`

### PR DESCRIPTION
**Pull request by ivantodorovich**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this be rethought around new EDI features in Odoo core?

**Comment by ivantodorovich** [comment]
> Shouldn't this be rethought around new EDI features in Odoo core?

Mmm, I'm not familiar with it but I guess it makes sense, yeah.
I'll check with my colleagues and get back at you

**Comment by pedrobaeza** [comment]
OK, let me know if you want to exchange brainstorming.

**Comment by ivantodorovich** [comment]
I checked with my team, and it turns out on the project we're working on we really do only need the `transmit_method_id` field on moves, not EDI features. I also couldn't find an alternative to this on core 😅

Most probably the refactor around the new EDI would have to be done in modules like `account_invoice_export`, that used to depend on this module and it's possible they won't have to anymore

**Comment by pedrobaeza** [comment]
OK, thanks for checking

**Comment by rven** [comment]
@pedrobaeza
> /ocabot migration account_invoice_transmit_method
Now the module is twice in the list?
image

**Comment by pedrobaeza** [comment]
Well, not sure why the bot hasn't recognized correctly the existing line. I have corrected it manually.

**Comment by rven** [comment]
@pedrobaeza
where is the use of this file **test-requirements.txt** documented?

**Comment by pedrobaeza** [comment]
I don't think it's documented. cc @sbidoul

**Comment by sbidoul** [comment]
There is at least this [slide](https://docs.google.com/presentation/d/1_mOzweqJcJQlatcVvaY5UI4hR6b6Ebhk0er3sGjQCmw/edit#slide=id.ga1c8f2f2a9_0_319) from OCA days. What would be a good place to put such documentation ?

**Review by damdam-s — APPROVED** [review]
LG

**Comment by pedrobaeza** [comment]
> There is at least this [slide](https://docs.google.com/presentation/d/1_mOzweqJcJQlatcVvaY5UI4hR6b6Ebhk0er3sGjQCmw/edit#slide=id.ga1c8f2f2a9_0_319) from OCA days. What would be a good place to put such documentation ?

Should we put it at https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst ? Or https://odoo-community.org/page/Contribute ? Or as part of https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 (and maybe 14.0)?

**Review by ajaniszewska-dev — APPROVED** [review]
LG

**Comment by ivantodorovich** [comment]
Rebased and removed the test-requirement, as https://github.com/OCA/server-tools/pull/2232 has been merged already

This is ready to merge now ✔️

**Comment by aisopuro** [comment]
Both @damdam-s and @ajaniszewska-dev have approved these changes: do either of you have the ability to ask @OCA-git-bot to merge?

**Comment by ivantodorovich** [comment]
FTR `15.0` branch is red, hence why this is failing to merge.
The error seems related to this module: 

- https://github.com/OCA/account-invoicing/pull/1084#issuecomment-1147729364

**Pull request merged**
