### PR TITLE
[14.0][MIG] account_invoice_payment_warranty

### PR DESCRIPTION
**Pull request by Saran440**
Standard MIgrated
Migration from https://github.com/OCA/account-invoicing/pull/785

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hello @Saran440 ,

The problem is related with `account_invoice_triple_discount` 's Tests...


```
> 2022-09-30 19:17:52,510 249 ERROR odoo odoo.addons.account_invoice_triple_discount.tests.test_invoice_triple_discount: ERROR: TestInvoiceTripleDiscount.test_01_discounts
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/models.py", line 5011, in ensure_one
>     _id, = self._ids
> ValueError: not enough values to unpack (expected 1, got 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/__w/account-invoicing/account-invoicing/account_invoice_triple_discount/tests/test_invoice_triple_discount.py", line 62, in test_01_discounts
>     invoice = self.create_simple_invoice(200)
>   File "/__w/account-invoicing/account-invoicing/account_invoice_triple_discount/tests/test_invoice_triple_discount.py", line 55, in create_simple_invoice
>     line_form.tax_ids.add(self.tax)
>   File "/opt/odoo/odoo/tests/common.py", line 1880, in __exit__
>     self.save()
>   File "/opt/odoo/odoo/tests/common.py", line 2215, in save
>     proxy._parent._perform_onchange([proxy._field])
>   File "/opt/odoo/odoo/tests/common.py", line 2020, in _perform_onchange
>     result = record.onchange(self._onchange_values(), fields, spec)
>   File "/__w/account-invoicing/account-invoicing/account_invoice_date_due/models/account_move.py", line 34, in onchange
>     return super(AccountMove, obj).onchange(values, field_name, field_onchange)
>   File "/opt/odoo/addons/account/models/account_move.py", line 1158, in onchange
>     return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
>   File "/opt/odoo/odoo/models.py", line 6267, in onchange
>     record._onchange_eval(name, field_onchange[name], result)
>   File "/opt/odoo/odoo/models.py", line 6009, in _onchange_eval
>     method_res = method(self)
>   File "/opt/odoo/addons/account/models/account_move.py", line 541, in _onchange_invoice_line_ids
>     self._onchange_recompute_dynamic_lines()
>   File "/opt/odoo/addons/account/models/account_move.py", line 545, in _onchange_recompute_dynamic_lines
>     self._recompute_dynamic_lines()
>   File "/opt/odoo/addons/account/models/account_move.py", line 1127, in _recompute_dynamic_lines
>     invoice._recompute_tax_lines()
>   File "/__w/account-invoicing/account-invoicing/account_invoice_triple_discount/models/account_move.py", line 27, in _recompute_tax_lines
>     res = super(AccountMove, self)._recompute_tax_lines(**kwargs)
>   File "/__w/account-invoicing/account-invoicing/account_invoice_fixed_discount/models/account_move.py", line 21, in _recompute_tax_lines
>     tax_rep_lines_to_recompute=tax_rep_lines_to_recompute,
>   File "/__w/account-invoicing/account-invoicing/account_global_discount/models/account_move.py", line 72, in _recompute_tax_lines
>     tax_rep_lines_to_recompute=tax_rep_lines_to_recompute,
>   File "/opt/odoo/addons/account/models/account_move.py", line 731, in _recompute_tax_lines
>     if currency.is_zero(taxes_map_entry['amount']):
>   File "/opt/odoo/odoo/addons/base/models/res_currency.py", line 171, in is_zero
>     self.ensure_one()
>   File "/opt/odoo/odoo/models.py", line 5014, in ensure_one
>     raise ValueError("Expected singleton: %s" % self)
> ValueError: Expected singleton: res.currency()
```

**Comment by Saran440** [comment]
Waiting this pr merged https://github.com/OCA/account-invoicing/pull/1256

**Pull request closed without merging**
