### PR TITLE
[13.0][FIX] account_invoice_pricelist: Avoid division by zero

### PR DESCRIPTION
**Pull request by mrgoetz**
Module account_invoice_pricelist:
When calculating the discount, pricelists discount_policy not
"with_discount", the percentage of the discount is calculated.
If base_price is 0.0 we receive an error.

So we try to avoid this by checking the base_price.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM can you please add the module name in the title of this PR? and also in the commit message. It should be "[FIX]account_invoice_pricelist: avoid division by zero" or something similar

**Review by ferran-S73 — APPROVED** [review]

**Review by hildickethan — APPROVED** [review]

**Comment by rafaelbn** [comment]
@AaronHForgeFlow please could you re-review?

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
I see there is a FW port to 16: https://github.com/OCA/account-invoicing/pull/1485 What about 14.0 and 15.0? is that done already?

**Comment by AaronHForgeFlow** [comment]
I see the fix is already in 14.0 but not in 15.0, would you create the forward port?

**Comment by AaronHForgeFlow** [comment]
Sorry, I did  not realize the commit history is not correct and it has 3 commits. Apologies.

**Comment by AaronHForgeFlow** [comment]
Just did the PW port to v15 here: https://github.com/OCA/account-invoicing/pull/1641

**Pull request merged**
