### PR TITLE
[12.0][MIG] purchase_stock_picking_return_invoicing

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Standard migration of module purchase_stock_picking_return_invoicing to v12

cc ~ @Eficent

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]
Works great!

**Comment by JordiBForgeFlow** [comment]
cc @hveficent @aheficent  can you review?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on runbot:
* Returning after receive bills
* Retruning before receiving bills

Qauntities updated correctly. Qauntities proposed on returns or bills are correct.

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:
Functional review

**Pull request closed without merging**
