### PR TITLE
[15.0][ADD]account_invoice_zip_export

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional test.
LGTM

**Comment by dsolanki-initos** [comment]
@yajo Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@rafaelbn Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@kittiu Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@dani-xtendoo Could please review this PR?

**Pull request closed without merging**
