### PR TITLE
[14.0][MIG] account_move_tier_validation

### PR DESCRIPTION
**Pull request by newtratip**
Standard Migration, Ready for review.

cc: @ecosoft-odoo

### CODE REVIEW

**Comment by newtratip** [comment]
@kittiu Can you review this ?

**Review by CasVissers-360ERP — APPROVED** [review]

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
It seems that PR is ready to merge can someone please merge this PR?

**Comment by dsolanki-initos** [comment]
Can this be merged?

**Comment by dsolanki-initos** [comment]
@newtratip @kittiu can the issue be resolved and merge it again?

**Pull request merged**
