### PR TITLE
[MIG] account_invoice_merge: Migration to 13.0

### PR DESCRIPTION
**Pull request by cubells**
Superseds https://github.com/OCA/account-invoicing/pull/971

- added oca readme files
- fix https://github.com/OCA/account-invoicing/pull/971#issuecomment-891535830

### CODE REVIEW

**Comment by cubells** [comment]
@kittiu @acsonefho ping.

**Review by acsonefho — APPROVED** [review]
Code LGTM

**Review by ajaniszewska-dev — APPROVED** [review]
code LG

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@OCA/accounting-maintainers

**Review by anajuaristi — APPROVED** [review]

**Comment by anajuaristi** [comment]
Hello, any problem to merge this PR?

**Comment by asismorodo** [comment]
@OCA/accounting-maintainers code can be merged?

**Pull request closed without merging**
