### PR TITLE
[12.0][MIG] account_invoice_supplier_self_invoice

### PR DESCRIPTION
**Pull request by jarroyomorales**
Superseedes https://github.com/OCA/account-invoicing/pull/492 as author is not responding.

@pedrobaeza @Saran440 @etobella @LoisRForgeFlow

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
@Saran440 @pedrobaeza @LoisRForgeFlow Original migrator is not responding @Nikul-Chaudhary

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
