### PR TITLE
[MIG] account_invoice_refund_line_selection: Migration to 13.0

### PR DESCRIPTION
**Pull request by etobella**
Migration to 13.0.

Modified logic using account moves.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
I got this when trying to refund one line of a customer invoice on runbot:

```
  File "/home/odoo/build/OCA/account-invoicing/account_invoice_refund_link/wizards/account_move_reversal.py", line 16, in reverse_moves
    AccountMoveReversal, self.with_context(link_origin_line=True)
  File "/home/odoo/build/OCA/account-invoicing/account_invoice_refund_line_selection/wizards/account_move_reversal.py", line 48, in reverse_moves
    is_refund_line_reversal=self.refund_method == "refund_lines"
  File "/.repo_requirements/odoo/addons/account/wizard/account_move_reversal.py", line 86, in reverse_moves
    new_moves = moves._reverse_moves(default_values_list, cancel=is_cancel_needed)
  File "/.repo_requirements/odoo/addons/sale/models/account_invoice.py", line 75, in _reverse_moves
    return super()._reverse_moves(default_values_list=default_values_list, cancel=cancel)
  File "/home/odoo/build/OCA/account-invoicing/account_invoice_supplier_ref_unique/models/account_move.py", line 72, in _reverse_moves
    default_values_list=default_values_list, cancel=cancel
  File "/.repo_requirements/odoo/addons/account/models/account_move.py", line 2159, in _reverse_moves
    move_vals_list.append(move.with_context(move_reverse_cancel=cancel)._reverse_move_vals(default_values, cancel=cancel))
  File "/.repo_requirements/odoo/addons/stock_account/models/account_move.py", line 25, in _reverse_move_vals
    move_vals['line_ids'] = [vals for vals in move_vals['line_ids'] if not vals[2]['is_anglo_saxon_line']]
KeyError: 'line_ids'
```
It is weird because the traceback does not mention the relevant code for this module

**Comment by etobella** [comment]
Ugh! There is an incompatibility with stock_account, because it is not checking with get...

I think I solved it

**Review by AaronHForgeFlow — COMMENTED** [review]
It works now :)
But travis is unhappy testing another module :(

**Comment by etobella** [comment]
:green_apple: now :wink:

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by albariera — APPROVED** [review]
Functional review LGTM :+1:

**Pull request merged**
