### PR TITLE
[17.0][MIG] sale_invoicing_date_selection: Migration to version 17.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v17.
- Move invoice_date in form view so it is visible independently of advance payment method option.

@Tecnativa
TT49330
@carlosdauden @sergio-teruel

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by carolinafernandez-tecnativa** [comment]
ping @sergio-teruel

**Review by sergio-teruel — CHANGES_REQUESTED** [review]
I am testing in runboat and i think that the module does not work properly

Peek 24-07-2024 14-03

**Comment by carolinafernandez-tecnativa** [comment]
Could you please check now? Thanks! @sergio-teruel

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
