### PR TITLE
[13.0][MIG] account_billing

### PR DESCRIPTION
**Pull request by kongrattapong**
**Work In Process**
this PR is waiting for https://github.com/OCA/account-invoicing/pull/523, you can always use this for readability.

- [x] [[12.0] account_billing](https://github.com/OCA/account-invoicing/pull/523)

### CODE REVIEW

**Comment by kittiu** [comment]
Please state in the PR description that, this PR is waiting for #523, you can always use this for readability.

- [ ] XXX

**Comment by kittiu** [comment]
@kongrattapong account_billing v12 is on the way to merge. Please make sure all points in v12 is migrated to this v13, and rebase.
Thanks!

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by komsan-S — APPROVED** [review]
Functional Test ~ :+1:

**Pull request closed without merging**
