### PR TITLE
12.0 mig account invoice supplier ref unique

### PR DESCRIPTION
**Pull request by jeroenev**

### CODE REVIEW

**Comment by jeroenev** [comment]
sent signed CLA this morning to cla@odoo-community.org ^^

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by jeroenev** [comment]
merged transbot commits

**Comment by emagdalenaC2i** [comment]
there is other PR for the migration of this module, check #433

**Comment by pedrobaeza** [comment]
Thanks for the reference, @emagdalenaC2i. Indeed, the first one that arrives has preference over other ones.

**Comment by pedrobaeza** [comment]
Closing this one in favor of #433

**Pull request closed without merging**
