### PR TITLE
[15.0][MIG] account_portal_invoice_search_by_lot: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT41648

This PR extends #1342 

@pedrobaeza please review!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The title of the PR doesn't seem correct.

**Comment by stefan-tecnativa** [comment]
> The title of the PR doesn't seem correct.

Ups, corrected.

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Pull request merged**
