### PR TITLE
14 account invoice merge xbo

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by anajuaristi — APPROVED** [review]

**Comment by anajuaristi** [comment]
Functionally tested, it works

**Comment by xavier-bouquiaux** [comment]
@OCA/accounting-maintainers
@dreispt 

Is it possible to relaunch the merge please

regards

Xbo

**Comment by rousseldenis** [comment]
@OCA/accounting-maintainers

**Pull request merged**
