### PR TITLE
[15.0][MIG] account_portal_invoice_search: Migration to version 15.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT41647

@chienandalu review please!

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks! :+1:

**Comment by pedrobaeza** [comment]
You can squash together all of these commits:

Selección_068

**Review by pedrobaeza — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
