### PR TITLE
[17.0][MIG]account_move_tier_validation: Migration to v17.0

### PR DESCRIPTION
**Pull request by moitabenfdz**
Depends on:

- [x]  [base_tier_validation #787](https://github.com/OCA/server-ux/pull/787)

### CODE REVIEW

**Review by cormaza — APPROVED** [review]
LGTM

**Review by bosd — APPROVED** [review]
LGTM; the maturity level can be set to `Production/Stable`

**Comment by rven** [comment]
Could this be merged?

**Review by celm1990 — APPROVED** [review]
LGTM

**Comment by moitabenfdz** [comment]
@fclementic2c @grindtildeath @sbidoul Can I get some help to get this merged?

**Review by bizzappdev — APPROVED** [review]
LGTM

**Comment by patrickrwilson** [comment]
@moitabenfdz I know this is approved but it won't work correctly without this same fix that is in this PR for v16. https://github.com/OCA/account-invoicing/pull/1703
Can this be applied to this PR?

**Comment by moitabenfdz** [comment]
@fclementic2c @sbidoul @rafaelbn Can I get this merged, please?

**Comment by SonoDavid** [comment]
To remove a standard Odoo warning, you could remove the first line of 'index.html'.
The xml version description is not necessary any more and since version 17 issues a warning in console.

**Comment by mylbco** [comment]
Can this be merged ?

**Comment by StefanRijnhart** [comment]
Not to block this but including https://github.com/OCA/account-invoicing/pull/1703 seems a little premature. It has not received any reviews when I looked just now.
Please rename your commit `[FIX]Delete xml version` to include the module name: `[FIX] account_move_tier_validation: delete XML version`.

**Comment by StefanRijnhart** [comment]
I'm convinced now by the test that is now added to #1703. Maybe you can re-pick the commit of that PR?

**Comment by BT-etejeda** [comment]
Hi @moitabenfdz , any progress? Could you attend the comments from @StefanRijnhart ?

**Review by luc-demeyer — APPROVED** [review]

**Comment by mylbco** [comment]
Can this be merged ?

**Comment by luc-demeyer** [comment]
I have tested the module and deployed at a customer site.
Imho it can be merged (with or without cherry-pick of https://github.com/OCA/account-invoicing/pull/1703 )

**Comment by StefanRijnhart** [comment]
Superseded by https://github.com/OCA/account-invoicing/pull/1829 to include the final version of #1703

**Pull request closed without merging**
