### PR TITLE
[15.0] [MIG] account_invoice_tax_note

### PR DESCRIPTION
**Pull request by Shide**
Standard migration

- Bumped version
- Fixed report
- Squashed tranlsation and adminstrative commits

@yajo @rafaelbn please review if you want 😄 

MT-656 @moduon

### CODE REVIEW

**Comment by Shide** [comment]
Tests are passing: https://github.com/OCA/account-invoicing/runs/6270654711?check_suite_focus=true#step:8:156

**Review by yajo — APPROVED** [review]

**Comment by HaraldPanten** [comment]
> Tests are passing: https://github.com/OCA/account-invoicing/runs/6270654711?check_suite_focus=true#step:8:156

You should FIX the failure for the other module. Sorry 😔

**Comment by rafaelbn** [comment]
So,

```
2022-05-03 09:07:06,623 265 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.account_invoice_fiscal_position_update.tests.test_inv_fiscal_pos_update.TestProductIdChange)
Traceback (most recent call last):
  File "/opt/odoo/addons/account/tests/common.py", line 31, in setUpClass
    assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
```
**Migrated to v15 here**:  [MIG] account_invoice_fiscal_position_update: Migration to 15.0 #1084 
**Later Added FIX to tests in v14 here**:  [14.0][FIX] account_invoice_fiscal_position_update: fix tests #1141


```
2022-05-03 09:07:13,401 265 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.account_invoice_tax_required.tests.test_account_move_tax_required.TestAccountInvoiceTaxRequired)
Traceback (most recent call last):
  File "/opt/odoo/addons/account/tests/common.py", line 524, in setUpClass
    super().setUpClass(chart_template_ref=chart_template_ref)
  File "/opt/odoo/addons/account/tests/common.py", line 31, in setUpClass
    assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
```
**Migrated to v15 here**:  [15.0][MIG] account_invoice_tax_required #1086 

**This FIX talk also about "post_install"** --> [15.0][FIX] account_asset_management: add post-install tagged [#1387](https://github.com/OCA/account-financial-tools/pull/1387)

Super thanks! 🤟

**Comment by etobella** [comment]
Can you rebase?

**Comment by yajo** [comment]
Rebasing won't fix it, [the 15.0 branch is broken](https://github.com/OCA/account-invoicing/actions/runs/2234864203). We need to forward-port https://github.com/OCA/account-invoicing/pull/1141 as @rafaelbn said.

**Comment by Shide** [comment]
Tests are passing in this migration and runboat is working perfectly.
Why to wait to another unexisting PR to merge this one?

**Comment by etobella** [comment]
Done on #1148

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
@etobella @HaraldPanten all 💚 😄 Ready!! 🚀

**Comment by rafaelbn** [comment]
Sorry @etobella @HaraldPanten , I call bot by mistake thinking it had a triple validation (I change so quickly of tab), I try to stop de merge but I don't know how. I tried to close de PR and open again but bot didn't stop after closing de PR 😢 . Lucky is that all was 🟢 and working!

**Comment by etobella** [comment]
Don't worry, It looked fine :smile:

**Comment by HaraldPanten** [comment]
@rafaelbn  to abort the merging process:

See that when bot is merging, a new branch is created. In this PR, the new branch was called [15.0-ocabot-merge-pr-1146-by-rafaelbn-bump-patch](https://github.com/OCA/account-invoicing/commits/15.0-ocabot-merge-pr-1146-by-rafaelbn-bump-patch)

If you want to cancel the merging process, you need to delete the new branch created by the bot. So... you should had deleted [15.0-ocabot-merge-pr-1146-by-rafaelbn-bump-patch](https://github.com/OCA/account-invoicing/commits/15.0-ocabot-merge-pr-1146-by-rafaelbn-bump-patch) before the PR was merged.

After this step, the merging process will stop and you can continue working on the PR. Once you want to merge, you can write the bot merge commands as usual.

Hope it could be helpful.

PS: I know this because I had to abort some merging processes due to self mistakes. 🤓😂

**Pull request merged**
