### PR TITLE
7.0 sale_order_partial_invoice: Some enhancements in the way to 8.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
See commit messages for the list of changes.

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by eLBati** [comment]
Is there a reference PR about the same changes on 8.0 ?

**Comment by pedrobaeza** [comment]
No, this is not a backport, but a preparation PR before the migration to 8.0.

**Comment by eLBati** [comment]
:+1: thanks

**Pull request merged**
