### PR TITLE
[14.0][mig] account_invoice_merge

### PR DESCRIPTION
**Pull request by fredzamoabg**
`account_invoice_merge` module migration from 12.0

### CODE REVIEW

**Review by SimoneVagile — APPROVED** [review]

**Comment by andreampiovesana** [comment]
you should change origin with invoice_origin in 
https://github.com/fredzamoabg/account-invoicing/blob/174e4101ee91641cbf492b4469ced327c49a5a7b/account_invoice_merge/models/account_move.py#L142
and
https://github.com/fredzamoabg/account-invoicing/blob/174e4101ee91641cbf492b4469ced327c49a5a7b/account_invoice_merge/models/account_move.py#L143

**Comment by fredzamoabg** [comment]
> you should change origin with invoice_origin in https://github.com/fredzamoabg/account-invoicing/blob/174e4101ee91641cbf492b4469ced327c49a5a7b/account_invoice_merge/models/account_move.py#L142 and https://github.com/fredzamoabg/account-invoicing/blob/174e4101ee91641cbf492b4469ced327c49a5a7b/account_invoice_merge/models/account_move.py#L143

done, thank you.

**Review by andreampiovesana — APPROVED** [review]
go

**Comment by francescapenso** [comment]
it works properly

**Review by francescapenso — APPROVED** [review]

**Comment by andreampiovesana** [comment]
merge?

**Review by ioans73 — APPROVED** [review]
Functional review 👍🏻

**Comment by andreampiovesana** [comment]
merge?

**Comment by ioans73** [comment]
We want to add an improvement, so that the new invoices are linked with pickings and stock moves, in case the `stock_picking_invoice_link` module is installed

**Comment by ioans73** [comment]
> We want to add an improvement, so that the new invoices are linked with pickings and stock moves, in case the `stock_picking_invoice_link` module is installed

@OCA/accounting-maintainers Can it be reviewed and merged? To be able to make another PR and apply the changes

**Comment by ioans73** [comment]
> We want to add an improvement, so that the new invoices are linked with pickings and stock moves, in case the `stock_picking_invoice_link` module is installed

@fredzamoabg 
I have tried to make a PR against your branch, to apply the changes, but I have not been able to, due to lack of permissions.
Can you give me permission to do the PR or do you prefer to add these changes yourself?

[account_invoice_merge_diff.txt](https://github.com/OCA/account-invoicing/files/8900069/account_invoice_merge_diff.txt)

**Comment by ioans73** [comment]
ping @fredzamoabg

**Pull request closed without merging**
