### PR TITLE
[13.0][IMP] add addons table

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/accounting-maintainers

**Review by chusamo — APPROVED** [review]
Great Job Thank you LGTM

**Comment by marcelsavegnago** [comment]
ping @OCA/accounting-maintainers

**Review by HaraldPanten — APPROVED** [review]

**Review by renatonlima — APPROVED** [review]

**Pull request merged**
