### PR TITLE
[12.0][IMP+FIX] Return Picking Invocing Process and mapping Invoice Type

### PR DESCRIPTION
**Pull request by mbcosta**
Included in Return Picking Wizard option to select if should be Invocing, fix mapping Invoice Type and test this process.

image

cc @renatonlima @rvalyi

### CODE REVIEW

**Review by renatonlima — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by rvalyi — APPROVED** [review]
well done @mbcosta !

**Comment by rvalyi** [comment]
@mbcosta kudos also for the SavepointCase test move. As we have 12 tests in the same file it really makes less DB requests and saves some time.

**Pull request merged**
