### PR TITLE
[10.0][ADD] account_invoice_merge - making make_key() generic

### PR DESCRIPTION
**Pull request by baimont**
Today, it is not possible to merge fields that are Many2many.
In order to achieve that, I changed make_key(), making it more generic.

### CODE REVIEW

**Review by benwillig — APPROVED** [review]
Code review. LGTM

**Comment by apineux** [comment]
I made a code review of this method because I wanted to understand the use of json here.

**Review by mourad-ehm — APPROVED** [review]
Code review. Thanks for improvement

**Pull request merged**
