### PR TITLE
[16.0][MIG] purchase_stock_picking_return_invoicing: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa  TT42427

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @sergio-teruel , @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Code review and tested in runboat

**Review by sergio-teruel — APPROVED** [review]
Functional review ok

**Comment by sergio-teruel** [comment]
ping @juangomezzurita

**Pull request merged**
