### PR TITLE
[16.0][ADD] account_tax_change

### PR DESCRIPTION
**Pull request by sebalix**
Declare your tax changes starting from a date, and apply these changes on your existing invoices.

The following glue module has also been created to be compatible with `account_invoice_start_end_dates`:
- https://github.com/OCA/account-closing/pull/243

### CODE REVIEW

**Review by mmequignon — APPROVED** [review]
LG!

**Review by grindtildeath — COMMENTED** [review]
cf my comments on v10.0 PR, I'll get back to this one later on.

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by ivantodorovich — APPROVED** [review]
LG

Don't we need an `ir.rule` for multi companies?

**Comment by sebalix** [comment]
Switched to LGPL to be compatible with enterprise modules.

**Comment by rafaelbn** [comment]
@grindtildeath ?

**Review by grindtildeath — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
