### PR TITLE
[MIG][14.0]  account_invoice_search_by_reference: Migration to 14.0

### PR DESCRIPTION
**Pull request by chusamo**

### CODE REVIEW

**Comment by chusamo** [comment]
Isn't there travis for this repo?

**Review by anasuarez1 — APPROVED** [review]
Functional Review OK!

**Comment by xavierjimenez** [comment]
Technical review LGTM, can you check it please @AaronHForgeFlow @newtratip

**Review by xavierjimenez — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
functional tests. It seems good.

**Review by newtratip — APPROVED** [review]
Code review, LGTM :+1:

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
