### PR TITLE
[13.0][WIP][MIG]account_invoice_pricelist

### PR DESCRIPTION
**Pull request by HaraldPanten**
WIP MIG to V13

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@HaraldPanten 
Are you planning to do work on this or is this already proposed? It includes @api.multi and still refers to account.invoice? Module is not installable for sure.

**Comment by HaraldPanten** [comment]
> @HaraldPanten
> Are you planning to do work on this or is this already proposed? It includes @api.multi and still refers to account.invoice? Module is not installable for sure.

Hi @CasVissers I'll work on it in the next few days/weeks. It's still WIP and it's not ready to test.

Do you need it? If you need it ASAP I don't mind closing this PR and let you continue with the MIG.

Thanks!

**Comment by legalsylvain** [comment]
I think that this module should be renamed to account_move_pricelist. Don't you think ?

**Comment by CasVissers-360ERP** [comment]
> I think that this module should be renamed to account_move_pricelist. Don't you think ?

I think invoice is fine, move would imply that it can be used in moves as well? So not only on invoice_line_ids but also line_ids?

**Comment by HaraldPanten** [comment]
> I think that this module should be renamed to account_move_pricelist. Don't you think ?

I think invoice is OK. I agree with CasVissers. Furthermore, pricelist is going to be invisible in normal account moves.

**Comment by CasVissers-360ERP** [comment]
@HaraldPanten Are you planning to do work on this?

**Comment by HaraldPanten** [comment]
Hi @CasVissers I was trying this but I had a problem with the calculation (and account move balance debit/credit) once the pricelist has been set. I need more time, so I'll close this PR as I'm not able to focus on it because I'm attending other PR's/duties.

You can take it if you want as it seems to be urgent for your team. Ping me once you have it ready and I'll review your PR. 👍

**Comment by HaraldPanten** [comment]
@CasVissers  that might be interesting for you https://github.com/OCA/account-invoicing/pull/757

**Pull request closed without merging**
