### PR TITLE
[FIX] account_invoice_triple_discount: Discount rounding

### PR DESCRIPTION
**Pull request by SirAionTech**
The added tests show how those trivial use-cases are failing before this PR.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@SirAionTech is this different from https://github.com/OCA/account-invoicing/pull/1256 and related back- and fw-portings?

**Comment by SirAionTech** [comment]
> @SirAionTech is this different from #1256 and related back- and fw-portings?

Yes, it looks like that PR is already included in `16.0`.

**Comment by francesco-ooops** [comment]
@sergiocorato @ferran-S73 fyi

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Review by GSLabIt — APPROVED** [review]

**Review by odooNextev — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@eLBati @sergiocorato @OCA/accounting-maintainers good for merge?

**Comment by francesco-ooops** [comment]
@almumu can you take a look at this? thanks!

**Comment by francesco-ooops** [comment]
@tafaRU anything against this one?

**Comment by francesco-ooops** [comment]
@pedrobaeza does this approach look reasonable to you?

**Comment by pedrobaeza** [comment]
I can't say. Merging due to existing reviews and nothing specially blocking seen.

/ocabot merge patch

**Pull request merged**
