### PR TITLE
8.0 reinsert purchase invoice merge

### PR DESCRIPTION
**Pull request by vrenaville**
I have reinsert and fix the ability to merge invoices linked to a purchase order.

### CODE REVIEW

**Comment by vrenaville** [comment]
@adrienpeiffer could you please review it.
It seems that you had removed this feature at 2723863cf50c67b20dedac55a1e061e6bfaa5915

**Comment by pedrobaeza** [comment]
It's in a separated module in https://github.com/OCA/account-invoicing/tree/9.0/account_invoice_merge_purchase

**Comment by leemannd** [comment]
:+1:

**Comment by gurneyalex** [comment]
@vrenaville mabe the readme should be updated ?

@pedrobaeza this is in the 8.0 branch

**Comment by pedrobaeza** [comment]
Sorry, wrong link, but the same applies to 8.0

**Pull request closed without merging**
