### PR TITLE
[8.0][FIX] invoice pricelist sale purchase stock

### PR DESCRIPTION
**Pull request by legalsylvain**
supersed https://github.com/OCA/account-invoicing/pull/409

Current behaviour : 
- sale pricelist is not get from sale_order when generating invoice from out picking. (ref #409)
- purchase pricelist is not get from purchase order when generating invoice from in picking.
- partner pricelist is not get from partner if picking is created from scrach, with invoice policy set to 'to 2 invoiced'.
- pricelist can be changed on non draft invoices that should be forbidden. 

this PR fixes all that bugs (Commit # 2 and # 4) . Also I refactored the code factoring some duplicated code (commit # 1 and # 3) 

Note, this PR make the module account_invoice_pricelist_sale_stock obsolete. I made it depends on the new one, that is more generic and handles all the cases.

CC : @quentinDupont, @pedrobaeza, @NL66278 

Note : I didn't introduced tests because the 8.0 revision is quite old, and because modules has been ported and refactored in 10.0 and should work without there patches, due to the changes in the invoicing process. (from sale / purchase, instead of pickings).

### CODE REVIEW

**Comment by legalsylvain** [comment]
travis is failing because broken upstream. (ref : https://travis-ci.org/OCA/account-invoicing/branches)

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
Maybe have a look at red Travis. One thing: at some places _columns is used (also in the original code). Maybe this can be replaced with _fields.

**Comment by legalsylvain** [comment]
> Maybe have a look at red Travis.

Travis is red for unrelated reason, and 8.0 branch is red since many commits. https://travis-ci.org/OCA/account-invoicing/branches

> One thing: at some places _columns is used (also in the original code). Maybe this can be replaced with _fields.

Well, I just moved code from a module to another, and it's working. I think _columns and _fields are aliases.

propose to merge this PR to fix this bug, and to make the changes on more recent version.

regards.

**Comment by legalsylvain** [comment]
> Maybe have a look at red Travis.

Travis is red for unrelated reason, and 8.0 branch is red since many commits. https://travis-ci.org/OCA/account-invoicing/branches

> One thing: at some places _columns is used (also in the original code). Maybe this can be replaced with _fields.

Well, I just moved code from a module to another, and it's working. I think _columns and _fields are aliases.

propose to merge this PR to fix this bug, and to make the changes on more recent version.

regards.

**Review by quentinDupont — APPROVED** [review]

**Comment by legalsylvain** [comment]
2 approvals, and running on production. Merging. 
(Same reason as here https://github.com/OCA/account-invoicing/pull/528. Travis is broken since monthes).

image

**Pull request merged**
