### PR TITLE
[12.0] [MIG] account_invoice_tax_required

### PR DESCRIPTION
**Pull request by Nikul-Chaudhary**
Account invoice with tax required in invoice line
==================================================

This module adds functional a check on invoice to force user to set tax on invoice line.

### CODE REVIEW

**Comment by Nikul-Chaudhary** [comment]
@OCA/accounting-maintainers could you please review code?

**Comment by pedrobaeza** [comment]
Please include 1d654401d01893a9ded3062ba0fed1110b716179 that I had to fix for avoiding a gap in sequences

**Comment by pedrobaeza** [comment]
And the test fixing in 2c1e5f9cbf88e7923cd985372042450ecd0dce4c (you can squash both)

**Comment by Nikul-Chaudhary** [comment]
@pedrobaeza Now Done, Review Again

**Review by pedrobaeza — APPROVED** [review]
It would be good to have README by fragments

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM, new fragment readme is included

**Pull request merged**
