### PR TITLE
[13.0][MIG] account_invoice_supplierinfo_update: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT34962

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @chienandalu @pedrobaeza

**Review by chienandalu — APPROVED** [review]
Tested :+1: Thanks!

**Review by legalsylvain — APPROVED** [review]
Hi. Thanks a lot for porting this module.

Diff review / no test : LGTM.

Note : there is a similar module in purchase-workflow : I think that in recent version a refactor should be done to avoid duplicated code. Could you add a text in the roadmap section, similar to this : 

https://github.com/OCA/purchase-workflow/pull/1268#pullrequestreview-774840323

thanks.

**Comment by ernestotejeda** [comment]
@legalsylvain thank you for reviewing. Changes done.

**Comment by pedrobaeza** [comment]
/ocabot migration /ocabot migration account_invoice_supplierinfo_update

**Pull request merged**
