### PR TITLE
[12.0][minor and fast fix] account_invoice_fixed_discount: templated correctly

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Bad migration. Please, approve and merge ASAP.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@ageficent @hveficent @lreficent

**Review by HviorForgeFlow — APPROVED** [review]
FF

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]
Not the perfect patch, but is mimicking Odoo

**Pull request merged**
