### PR TITLE
[IMP] account_invoice_supplier_self_invoice: Allow to use a refund sequence

### PR DESCRIPTION
**Pull request by etobella**
@rafaelbn @Shide

### CODE REVIEW

**Review by Shide — APPROVED** [review]
Functional and code review, LGTM

**Review by rafaelbn — COMMENTED** [review]
Nor related to this PR but is a BUG 😄 

- [ ] The self invoice if for the partner and all the contacts not only for the parent

imagen

**Comment by etobella** [comment]
True, fixed in the last commit (with a test in order to not loose the functionality)

image

**Review by rafaelbn — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
