### PR TITLE
[15.0][MIG]account_invoice_warn_message

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@etobella @sbidoul @pedrobaeza any clue about what could we do to fix pre-commit? THX

**Comment by pedrobaeza** [comment]
/ocabot migration account_invoice_warn_message

#1590 should be finished.

**Review by HaraldPanten — APPROVED** [review]
Functional review, tested in runboat. LGTM.

@pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
