### PR TITLE
[11.0][ADD] account_invoice_approval

### PR DESCRIPTION
**Pull request by tarteo**
Configure an approval flow for customer invoices, vendor bills, and credit notes. Automatically sends notifications to reviewers.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Dear @tarteo ,

Could please take a look in https://odoo-community.org/shop?&search=base_tier_validation ?

This is a generic mechanism for every model :smile: 

cc @ageficent @etobella @jbeficent

**Comment by tarteo** [comment]
@rafaelbn Thanks, It's quite similar. I miss some functionality though: Mails, sequenced validation, override setting. I can probably migrate the functionalities from here to base_tier_validation.

**Comment by rafaelbn** [comment]
You are the best @tarteo ! :+1:

**Comment by CasVissers-360ERP** [comment]
@tarteo Did you already create a mechanism based on tier validation? I would like to help in validating.

**Pull request closed without merging**
