### PR TITLE
[15.0][MIG] account_invoice_tree_currency: Migration to 15.0

### PR DESCRIPTION
**Pull request by OriolVForgeFlow**

### CODE REVIEW

**Comment by OriolVForgeFlow** [comment]
@ForgeFlow

**Review by MiquelRForgeFlow — APPROVED** [review]
Please, rebase, let's see if the new runbo**a**t triggers.

**Review by JoanMForgeFlow — APPROVED** [review]
Code review OK! :+1: Functional LG

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
Hi @OriolVForgeFlow could you try a rebase to see if runboat go green ?

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
