### PR TITLE
[15.0][MIG] account_invoice_merge

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
please rebase

**Review by gaikaz — APPROVED** [review]
Tests pass, and migration code changes seem minimal and non functional.
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@MiquelRForgeFlow is it ready to merge?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by tbaden** [comment]
@OCA/accounting-maintainers can this be merged?

**Comment by tbaden** [comment]
@OCA/accounting-maintainers anything new here?

**Comment by gaikaz** [comment]
It's a bit crazy how the module is already migrated to Odoo 16 (https://github.com/OCA/account-invoicing/pull/1400) where the migration used THIS migration as base, yet here we are still not merged without a comment on why...

**Comment by rvalyi** [comment]
Hello @gaikaz well basically the OCA is voluntary work, so at some point no guarantee, just better like-hoods than modules lost somewhere behind some company walls...

I'm not an expert of this module myself, so I won't take the risk to assume the merge myself here. But all I can say is: despite v15 and v16 took the same last v14 commit as a base, v16 got a lot more fix/refactor:
https://github.com/OCA/account-invoicing/pull/1400/commits/0c241a713354495dffe4219ed9a932c61bce8c6e
vs https://github.com/OCA/account-invoicing/pull/1189/commits/94dc5d4968197d68bb42f686bce19dc9946afea4 for v15.
If the diff was smaller (I mean more stuff from the v16 changes in the v15 proposal) I would certainly merge it myself. But may be some other accounting Project Steering Committee members will think the v15 PR is ready enough and approved so it could be merged.

cc @OCA/community-maintainers

**Comment by gaikaz** [comment]
Hey, @rvalyi
Thank you for the explanation and the comment on the commit history. It's understandable that OCA's maintainers have their own businesses to run as first priority. 
Honestly, didn't mean to sound like I'm ranting. 😅 (that's what we use Twitter for, it seems) 
Just found it odd, that the module was successfully migrated from this unmerged 15.0 version to 16.0.
I suppose, someone should have at least left a comment here (or there) about the additional changes, if they should be applied on this migration PR.

**Comment by rvalyi** [comment]
sadly, it's fairly common that:

- some Odoo versions don't get a migration or a merge, or only years later.
- all our real life projects deal with this using alien git tools like acsone/git-aggregator
- if you look at the stats, you'll see that odd Odoo versions got less traction in the community, easily 25% less modules after a given time period. I guess Odoo SA screwed a few odd versions enough (I won't be ranting here that's what Tiwtter is for :-) so the even Odoo versions got some sort o resonance with more deployments. Creating such thresholds might not be desirable but it's still true.

all this being said I hope some PSC who know the module a bit will hit the merge button.

**Comment by pedrobaeza** [comment]
/ocabot migration account_invoice_merge

I don't like this module, as it's a deformation of the flows and requires a lot of glue modules for having all the information on the merged invoices correct, but as the migration itself is correct and have reviews, and merging:

/ocabot merge nobump

I encourage you to go deeper into the reason for using it and rethink the flows for not needing this one.

**Pull request merged**
