### PR TITLE
[10.0][MIG] account_invoice_refund_link

### PR DESCRIPTION
**Pull request by luismontalba**
Link refund invoice with original
=========================

This module links customer and supplier refunds with the invoice that originate
them (and invoice lines).

Usage
--------

This module creates in the invoice form a new 'Refund' page.

In case of refund invoices this new page shows refund reason and original
invoice information.

In case of original invoices this new page shows a line for each refund
invoice with main information.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
ECLA assigned

**Review by pedrobaeza — APPROVED** [review]
Squashing last 2 commits together when merging.

**Review by chienandalu — APPROVED** [review]
tested on runbot

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza @luismontalba 
Some tests of this module are failing in the Travis of https://github.com/OCA/account-invoicing/pull/238.
Please, check and say what to do!

**Pull request merged**
