### PR TITLE
[REF] Move change currency button to a better place inside the invoice form

### LINKED ISSUE #442: [FIX] 12.0 stable branch pylint checks
More info about:
 - https://travis-ci.org/OCA/account-invoicing/jobs/445250568#L580

Could you help me to fix it @hugho-ad?

### LINKED ISSUE #443: [REF] account_invoice_change_currency: Change button from header to next to currency field
Currently
 - screen shot 2018-10-23 at 22 11 29

RFC
  - Hidde the button if there is not activated the multi-currency settings.
  - Move the header top button to next to currency field with a fancy icon related:
   - borrar

What do you think @novawish?

@hugho-ad Could you help us with this one?

### PR DESCRIPTION
**Pull request by hugho-ad**
fix https://github.com/OCA/account-invoicing/issues/442
fix https://github.com/OCA/account-invoicing/issues/443

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]
:+1:
Thanks!

**Comment by moylop260** [comment]
FYI I just tested that the button is hidden/showed when I active/disable the multi-currency check from settings:
 - update

**Comment by moylop260** [comment]
@pedrobaeza Could you check it, please?

**Review by lmignon — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Tested in runbot :+1:

**Review by chienandalu — COMMENTED** [review]
Can we cherry pick this into `11.0`? The .rst is making the CI fail in that branch

**Comment by hugho-ad** [comment]
WIP on https://github.com/OCA/account-invoicing/pull/446

**Pull request merged**
