### PR TITLE
[16.0] [ADD] account_invoice_currency_taxes

### PR DESCRIPTION
**Pull request by JavierIniesta**
This module adds tax-related amounts in the company's currency when printing
invoices.

In some countries, this is a requirement for certain transactions.

The amounts will appear on the printed invoice when the currency of the invoice
is different from the company's currency.

Example: In the case of Spain, the amount of tax charged must be specified. https://www.boe.es/buscar/act.php?id=BOE-A-2012-14696

imagen

### CODE REVIEW

**Comment by JavierIniesta** [comment]
We have done functional tests and it works correctly.

**Comment by rafaelbn** [comment]
Hello @JavierIniesta ! 😄 

It helps if you record a short video showing how it works.

> The amounts will appear on the printed invoice when the currency of the invoice is different from the company's currency.

I don't understand this sentence clearly 🙏 

Thank you!

**Comment by RodrigoBM** [comment]
Hi @rafaelbn 

_By example, we have a company whose currency is $, and has created a sales invoice in €. In the tax calculation, the taxes are shown in the € currency of the printed invoice and in brackets in the company's currency $._

out_invoice

Regards

**Review by RodrigoBM — APPROVED** [review]

**Comment by RodrigoBM** [comment]
ping @fcvalgar @rafaelbn

**Review by fcvalgar — APPROVED** [review]
Functional review, it's working in pdf report and portal preview when the invoice is confirm.

LGTM, thankx @RodrigoBM 

image

image

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
