### PR TITLE
[14.0] ADD account_receipt_journal: Define and use journals dedicated to receipts

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by eLBati** [comment]
https://github.com/OCA/account-invoicing/actions/runs/3219774473/jobs/5265595874 @primes2h does this error say anything to you?

**Comment by primes2h** [comment]
> https://github.com/OCA/account-invoicing/actions/runs/3219774473/jobs/5265595874 @primes2h does this error say anything to you?

Mmhh... It's due to this, committed 7 days ago:

https://github.com/odoo/odoo/pull/101242/commits/7a415fef6dc5ce880163491dcc1a3bc4e68b7d36

I'll try to fix `account_receipt_print` as soon as i can. Tomorrow, I hope.

**Comment by primes2h** [comment]
> > https://github.com/OCA/account-invoicing/actions/runs/3219774473/jobs/5265595874 @primes2h does this error say anything to you?
> 
> Mmhh... It's due to this, committed 7 days ago:
> 
> [odoo/odoo@7a415fe](https://github.com/odoo/odoo/commit/7a415fef6dc5ce880163491dcc1a3bc4e68b7d36)
> 
> I'll try to fix `account_receipt_print` as soon as i can. Tomorrow, I hope.

@eLBati 
It has been fixed in https://github.com/OCA/account-invoicing/pull/1262

Thanks @Saran440 @kittiu !

**Comment by HekkiMelody** [comment]
```
WARNING test odoo.addons.base.models.ir_model: Two fields (receipt_ids, receipts) of sale.order() have the same label: Receipts. 
```

Aside from the warning, tested it on a local installation (in the context of a migration from 12.0 and the previous l10n_it module) and it seems to be working great!

I used these queries in a `pre-migrate.py` file on v14 to migrate my existing receipts:

```py
openupgrade.logged_query(
    env.cr,
    """UPDATE account_move am
    SET type = 'out_receipt'
    where am.id in (SELECT am2.id
    FROM account_move am2
    JOIN account_invoice ai on am2.old_invoice_id = ai.id
    WHERE ai.type = 'out_invoice'
    AND ai.corrispettivo = true)""",
)
openupgrade.logged_query(
    env.cr,
    """UPDATE account_move am
    SET type = 'in_receipt'
    where am.id in (SELECT am2.id
    FROM account_move am2
    JOIN account_invoice ai on am2.old_invoice_id = ai.id
    WHERE ai.type = 'in_invoice'
    AND ai.corrispettivo = true)""",
)
```
maybe they can be used in the migrations of this module or directly in openupgrade?

**Review by HekkiMelody — APPROVED** [review]

**Comment by eLBati** [comment]
> maybe they can be used in the migrations of this module or directly in openupgrade?

This is included in https://github.com/OCA/account-invoicing/pull/1267

**Review by rafaelbn — APPROVED** [review]
Thank you @eLBati ! 👍 

Great thing!

**Review by rafaelbn — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
