### PR TITLE
[14.0] [FIX] account_invoice_refund_line_selection: Business fields were missing

### PR DESCRIPTION
**Pull request by jappi00**
Hello together,

I have migrated the fix from #1131 for version 14.0.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Comment by jappi00** [comment]
I would be very happy if somebody can merge it.

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by rafaelbn** [comment]
Pre-commit fails
```

An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://gitlab.com/': No such device or address
    
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: Process completed with exit code 3.
```

https://github.com/OCA/account-invoicing/actions/runs/3660003036/jobs/6186642247

**Comment by jappi00** [comment]
> Pre-commit fails
> 
> ```
> 
> An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
> return code: 128
> expected return code: 0
> stdout: (none)
> stderr:
>     fatal: could not read Username for 'https://gitlab.com/': No such device or address
>     
> Check the log at /home/runner/.cache/pre-commit/pre-commit.log
> Error: Process completed with exit code 3.
> ```
> 
> https://github.com/OCA/account-invoicing/actions/runs/3660003036/jobs/6186642247

Excuse me please, what do I need to change? I don't understand the error.

**Comment by ioans73** [comment]
@jappi00 @rafaelbn @legalsylvain can we merge?

**Pull request merged**
