### PR TITLE
[14.0][MIG] account_move_exception

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard Migration.

### CODE REVIEW

**Comment by kittiu** [comment]
The ignore_exception and exeption_ids fields is showing like following. I think it looks a bit out of order.

image

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by kittiu** [comment]
> The ignore_exception and exeption_ids fields is showing like following. I think it looks a bit out of order.

Can you attend this @ps-tubtim ?

**Comment by ps-tubtim** [comment]
@kittiu Sorry for the late reply. I already fixed it. Could you review, please?

Selection_067

**Review by kittiu — APPROVED** [review]

**Pull request merged**
