### PR TITLE
IMP 15.0 sale_order_invoicing_grouping_criteria: extract _prepare_so_grouping

### PR DESCRIPTION
**Pull request by leemannd**
Extract the so-grouping to allow pre or post processing.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You already have `_get_sale_invoicing_group_key` for changing the way the groups are done. Why another hook? Just add an extra key for the grouping criteria you want.

**Comment by leemannd** [comment]
Hello, given the result of the grouping result I want to trigger distinct methods if the invoice is the result of a grouping or not.
The previous hook prepares the data for the grouping, but we don't know at this moment if the invoice that will be created will be from grouped SO.

**Comment by pedrobaeza** [comment]
I don't get exactly your explanation, as you get the link SO line <> invoice line for doing any kind of traceability between both without having to call the grouping method IMO, but well, I don't want to oppose to this. Pre-commit is not OK though.

**Comment by leemannd** [comment]
Closing as old and outdated

**Pull request closed without merging**
