### PR TITLE
[13.0][FIX] account_invoice_refund_line_selection, error singleton

### PR DESCRIPTION
**Pull request by kittiu**
Select > 1 refund lines, singleton error will occur.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Seems legit.

Ping @etobella @olgamarcocb

**Review by bosd — APPROVED** [review]
LGTM! func test on runboat

**Review by HaraldPanten — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Pull request merged**
