### PR TITLE
[IMP] Permission to set if an user can or can't use "Force Invoice Nu…

### PR DESCRIPTION
**Pull request by OpenCode**
Permission to set if an user can or can't use "Force Invoice Number"

### CODE REVIEW

**Comment by eLBati** [comment]
Thanks @OpenCode LGTM :+1: 

Travis error unrelated

**Comment by lepistone** [comment]
Also runbot is broken, and that also seems unrelated to this PR. Would be nice to debug it though.

**Comment by atchuthan** [comment]
@OpenCode travis fails due to the use of include/exclude in .travis.yml file
update the travis.yml file for 8.0 with the help of https://github.com/OCA/account-invoicing/blob/9.0/.travis.yml

**Comment by atchuthan** [comment]
code review :+1:

**Comment by CiroBoxHub** [comment]
run locally. lgtm :+1:

**Comment by andrea4ever** [comment]
:+1: for me

**Comment by lepistone** [comment]
I opened #145 #146. No objection on this PR. Thanks!

**Comment by OpenCode** [comment]
@lepistone thanks to you :)

**Pull request merged**
