### PR TITLE
[16.0][MIG] account_invoice_payment_retention

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Review by Taewii23 — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@Saran440 do you mind rebasing? We'd like to try the PR in runboat. THX

**Comment by HaraldPanten** [comment]
@Saran440 Could you have a look at my last comment? Do you mind rebasing, please? @kittiu

**Comment by Saran440** [comment]
@HaraldPanten Sorry for late reply. can you check again please?

**Review by HaraldPanten — APPROVED** [review]
Functional review in local environment

**Pull request merged**
