### PR TITLE
[13.0][MIG] account_invoice_supplier_ref_unique

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by fclementic2c** [comment]
isn't it the standard behavior ?

**Comment by astirpe** [comment]
Right @fclementic2c, I just tried it in Runbot. Thank you!

**Comment by sbidoul** [comment]
@astirpe @fclementic2c does Odoo now support distinct fields for supplier invoice number and supplier payment reference? See also: https://github.com/OCA/account-invoicing/pull/433#issuecomment-503175806

**Comment by astirpe** [comment]
So this module is still valid, right? @fclementic2c ?

**Comment by fclementic2c** [comment]
> @astirpe @fclementic2c does Odoo now support distinct fields for supplier invoice number and supplier payment reference? See also: [#433 (comment)](https://github.com/OCA/account-invoicing/pull/433#issuecomment-503175806)

yes

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by CasVissers-360ERP** [comment]
@astirpe I get a tb when duplicating an invoice:
```
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo13/community/account_invoice_supplier_ref_unique/models/account_move.py", line 79, in copy
    return super().copy(default)
  File "/odoo/odoo/odoo/models.py", line 4538, in copy
    new = self.with_context(lang=None).create(vals)
  File "<decorator-gen-182>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo/addons/purchase/models/account_invoice.py", line 74, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-158>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/addons/account/models/account_move.py", line 1542, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-111>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/models.py", line 3679, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'reference' on model 'account.move'
```

**Comment by astirpe** [comment]
Thanks @CasVissers . Done.

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM!

**Comment by astirpe** [comment]
@OCA/accounting-maintainers is it okay to merge this PR?

**Comment by sbidoul** [comment]
LGTM.

/ocabot merge patch

**Comment by astirpe** [comment]
Thank you @sbidoul 
Not sure if `merge patch` bumps the version. In this case it's just a porting of the module, so version should not increase.

**Comment by sbidoul** [comment]
Yes we should get 13.0.1.0.1. It's a trick I'm experimenting with to get round version numbers on PyPI for first versions.

**Pull request merged**
