### PR TITLE
[IMP] account_invoice_refund_link: Improve module

### PR DESCRIPTION
**Pull request by pedrobaeza**
Odoo already includes a method for preparing the refund, so using it we don't have to make any guess about the returned domain and the method also serves for refunds created directly by code.

Initial line match has also been improved comparing product or description.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @Tecnativa

@cubells @Yajo @rafaelbn please review

**Review by cubells — APPROVED** [review]
Core review and tested on runbot.
:+1:

**Review by elicoidal — APPROVED** [review]
:+1:

**Review by luismontalba — APPROVED** [review]
Functionality tested on runbot, it works.

**Pull request merged**
