### PR TITLE
[FIX] errors got after running flake8

### PR DESCRIPTION
**Pull request by tafaRU**
This PR contains some fixes to avoid errors got after running flake8. In addition the fix concerning the file travis.yml

### CODE REVIEW

**Comment by eLBati** [comment]
:+1:

**Comment by tafaRU** [comment]
**_test_flake8**_ looks green while  **_test_server**_ looks red.

I think this PR can be merged meanwhile I create another one to fix the errors occured after running tests.

**Comment by eLBati** [comment]
Tests are fixed by https://github.com/OCA/account-invoicing/pull/18

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
