### PR TITLE
[8.0][MOD] stock_picking_invoicing_incoterm: remove dependency, update code

### PR DESCRIPTION
**Pull request by esthermm**

### CODE REVIEW

**Review by NL66278 — CHANGES_REQUESTED** [review]
Code improvements look good to me. But when bringing code up to OCA standards and conventions, maybe a good idea to move model definitions to models directory, and views to views directory.

And don't hesitate to put your name with the contributors in the README.rst.

**Comment by NL66278** [comment]
Travis error is unrelated to work in this module, will be solved by PR #215

**Comment by esthermm** [comment]
Thanks for your comments @NL66278. Module updated and waiting for that merge. Thx!

**Comment by NL66278** [comment]
@esthermm My own PR that solves travis errors has been merged in 8.0. If you rebase your branch, you will have green travis too I would think, increasing chance for speedy adoption.

**Comment by esthermm** [comment]
PR [#215](https://github.com/OCA/account-invoicing/pull/215) is not merged yet! @NL66278  I'll wait to rebase my branch

**Review by pedrobaeza — APPROVED** [review]
Merging although Travis will be fixed in the other PR.

**Pull request merged**
