### PR TITLE
[11.0][add][account_invoice_supplier_self_invoice_tax_note]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module allows to display tax notes in self invoices.

Installation
============

This module will be automaically installed when the modules
'account_invoice_supplier_self_invoice' and 'account_invoice_tax_note' are
installed.

image

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
@JordiBForgeFlow , could you rebase to check bots?

**Comment by LoisRForgeFlow** [comment]
Rebased.

**Pull request merged**
