### PR TITLE
[FIX][16.0] account_invoice_triple_discount : Error when print reports

### PR DESCRIPTION
**Pull request by ramiadavid**
Fix to #1375

### CODE REVIEW

**Comment by ramiadavid** [comment]
@OCA/accounting-maintainers Can you review this?

**Comment by SkiBY** [comment]
Could you take care about code-coverage warning?

**Review by SkiBY — APPROVED** [review]

**Review by Shide — APPROVED** [review]

**Review by hildickethan — APPROVED** [review]

**Comment by andreampiovesana** [comment]
merge?

**Pull request merged**
