### PR TITLE
[13.0][MIG] account_invoice_change_currency

### PR DESCRIPTION
**Pull request by Saran440**
- In version 13 message tracking has changed. you have to save new invoice before change currency.
- action force rate change `reconciled` to `to_check` because account.move don't have a reconciled field
- add context `check_move_validity` in function action_account_change_currency

### CODE REVIEW

**Comment by gaikaz** [comment]
@Saran440 
Hi, are there plans to continue with this PR?
Also, maybe someone already uses it as is in production?

**Comment by Saran440** [comment]
@gaikaz 
This PR is ready to review.
Could you review, please?

**Review by gaikaz — APPROVED** [review]
Migration changes LGTM

My colleague will also do some functional testing and code review of his own tomorrow.
But I suppose you need at least one review from the maintainers?

**Review by DonatasV — APPROVED** [review]
LGTM

**Comment by gaikaz** [comment]
@OCA/accounting-maintainers Could we please merge this?

**Comment by luisg123v** [comment]
@Saran440 could you rebase to make CI to be green, please?

**Comment by rafaelbn** [comment]
Please @Saran440 could you rebase to check

**Pull request closed without merging**
