### PR TITLE
[17.0][IMP] account_invoice_fixed_discount: avoid replace in xml

### PR DESCRIPTION
**Pull request by CRogos**
forward port of https://github.com/OCA/account-invoicing/pull/1593

### CODE REVIEW

**Review by MohamedOsman7 — APPROVED** [review]
code LGTM

**Comment by CRogos** [comment]
@JordiBForgeFlow you've merged it into 16.0 . Could you review and merge?

**Comment by CRogos** [comment]
@pedrobaeza could you merge this forward port?

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
