### PR TITLE
[ADD] add module to force currency rate on account invoice

### PR DESCRIPTION
**Pull request by bguillot**
Hello, 

This PR adds a module : account_invoice_currency_rate. 
It allows to manually set the currency rate on account invoice and it will be used on the move creation.

Thanks for reviews

### CODE REVIEW

**Comment by chafique-delli** [comment]
Hello Benoit,

I tested your module, it is good but i will hide the button 'Force currency rate' on invoice when currency_id.rate=1 that is the currency of the company otherwise it is confusing.

Best Regards,

**Comment by bguillot** [comment]
Hello Chafique,

Thank you for the review, I think you are right.

It was a bit tricky to hide the button with those conditions, so I had to add a function field to decide when to display the button. If someone has a better idea I can change the code.

**Comment by chafique-delli** [comment]
It's good for me now. :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
