### PR TITLE
[16.0] MIG account_invoice_supplierinfo_update

### PR DESCRIPTION
**Pull request by legalsylvain**
- [x] Cherry pick improvment done on 12.0 here https://github.com/OCA/account-invoicing/pull/1404
    - [x] [FIX] use float compare to avoid false positive 
    - [x] [IMP] Check if the uom of the invoice line is the same as the uom of supplierinfo. If not, allow to change the UoM in the wizard
    - [x] [FIX] account_invoice_supplierinfo_update : update supplierinfo min_qty, based on new_min_quantity value on wizard line

**Other changes**
- [x] [MIG] migrate module from 14.0 to 16.0
- [x] [IMP] use new optional='show' features 
- [x] [FIX] take into changes in the wizard to compute price variation
- [x] [REF] rename 'price_variation' into 'cost_variation', because the current name is not correct with glue modules (discount / triple discount...)
- [x] [REF] add lambda function to know how to recompute costs fields, to make the overload simplier in glue modules
- [x] [REF] Add legalsylvain as maintainer

### CODE REVIEW

**Comment by rafaelbn** [comment]
Ping me when ready to review @legalsylvain  😄

**Comment by legalsylvain** [comment]
hi @rafaelbn This one should be ready for review !

**Comment by rafaelbn** [comment]
Great! Thank you!

@moduon @fcvalgar @Shide

**Review by rafaelbn — APPROVED** [review]
LGTM 👍 

Great work!

**Review by rafaelbn — CHANGES_REQUESTED** [review]
@legalsylvain testing in detail I get a Odoo Server Error when updating in a new creation

Check

imagen

```python
RPC_ERROR

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/api.py", line 983, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/fields.py", line 1160, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo/api.py", line 990, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'wizard.update.invoice.supplierinfo.line(5,).new_cost'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/models.py", line 5119, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 2979, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo/models.py", line 3136, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo/models.py", line 5858, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1368, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/models.py", line 4193, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/mnt/data/odoo-addons-dir/account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo_line.py", line 88, in _compute_new_cost
    line.new_cost = line.new_uom_id._compute_price(
  File "/opt/odoo/addons/uom/models/uom_uom.py", line 229, in _compute_price
    self.ensure_one()
  File "/opt/odoo/odoo/models.py", line 5122, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: uom.uom()

The above server error caused the following client error:
null
```

**Comment by legalsylvain** [comment]
Hi @rafaelbn. Sorry for the late, I missed your last comment.
I added a fix.
could you take a look ? 
thanks !

**Comment by rafaelbn** [comment]
Thank you @legalsylvain ! are you going to squash commits?

**Comment by legalsylvain** [comment]
> Thank you @legalsylvain ! are you going to squash commits?

Which commits exactly ?

**Comment by rafaelbn** [comment]
Do you want all this commits separated?

imagen

**Review by rafaelbn — APPROVED** [review]
Thank you for this great work! 👍🏼

**Review by Shide — APPROVED** [review]

**Comment by Gelo-fl** [comment]
When using the "UPDATE AND VALIDATE" button, a traceback appears https://www.awesomescreenshot.com/video/19430792?key=d13f81e38d852092923042d0b0e791ed
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/data/odoo-addons-dir/account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.py", line 65, in update_supplierinfo_validate
    invoice.post()
AttributeError: 'account.move' object has no attribute 'post'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://oca-account-invoicing-16-0-pr1436-767850df473d.runboat.odoo-community.org/web/assets/465-24e2fbc/web.assets_backend.min.js:985:163)
    at XMLHttpRequest.<anonymous> (http://oca-account-invoicing-16-0-pr1436-767850df473d.runboat.odoo-community.org/web/assets/465-24e2fbc/web.assets_backend.min.js:993:13)

**Comment by Gelo-fl** [comment]
> When using the "UPDATE AND VALIDATE" button, a traceback appears https://www.awesomescreenshot.com/video/19430792?key=d13f81e38d852092923042d0b0e791ed Traceback (most recent call last): File "/opt/odoo/odoo/http.py", line 1584, in _serve_db return service_model.retrying(self._serve_ir_http, self.env) File "/opt/odoo/odoo/service/model.py", line 133, in retrying result = func() File "/opt/odoo/odoo/http.py", line 1611, in _serve_ir_http response = self.dispatcher.dispatch(rule.endpoint, args) File "/opt/odoo/odoo/http.py", line 1815, in dispatch result = self.request.registry['ir.http']._dispatch(endpoint) File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch result = endpoint(**request.params) File "/opt/odoo/odoo/http.py", line 697, in route_wrapper result = endpoint(self, *args, **params_ok) File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button action = self._call_kw(model, method, args, kwargs) File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/opt/odoo/odoo/api.py", line 461, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/opt/odoo/odoo/api.py", line 448, in _call_kw_multi result = method(recs, *args, **kwargs) File "/mnt/data/odoo-addons-dir/account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.py", line 65, in update_supplierinfo_validate invoice.post() AttributeError: 'account.move' object has no attribute 'post'
> 
> The above server error caused the following client error: RPC_ERROR: Odoo Server Error at makeErrorFromResponse (http://oca-account-invoicing-16-0-pr1436-767850df473d.runboat.odoo-community.org/web/assets/465-24e2fbc/web.assets_backend.min.js:985:163) at XMLHttpRequest. (http://oca-account-invoicing-16-0-pr1436-767850df473d.runboat.odoo-community.org/web/assets/465-24e2fbc/web.assets_backend.min.js:993:13)

@legalsylvain can you check it, please?

**Comment by rafaelbn** [comment]
Hello @Gelo-fl ,

I review this PR and I didn't get any error. In fact today a review again and I don't find the error.

I guess this PR is in producction for a while 

How you get the button "UPDATE AND VALIDATE"? I don't see clearly in the README all the use cases

See: https://www.loom.com/share/64a212823a7f4356b187d5b99f07bd14?sid=7e9c9e99-fe55-409f-94b3-6d527f2a600d

Thank you! ❤️ 

- [ ] If you click in "Check supplier infos" before validating the invoice the buttons disappears and not update anything. Later you cannot update automatically. I think this should be solved.

**Comment by legalsylvain** [comment]
> How you get the button "UPDATE AND VALIDATE"? I don't see clearly in the README all the use cases

update and validate is a button in the wizard, if the account move is not posted. there are in that case two options. update and validate OR update without validating.

>  If you click in "Check supplier infos" before validating the invoice the buttons disappears and not update anything. Later you cannot update automatically. I think this should be solved.

Once the invoice has been "checked" (whatever the state of the account move), there is a checkbox checked in the "other information" tab of the invoice. If you uncheck this box, you can rerun the wizard. (rare case, thought).

Does it answer your question?

**Comment by Gelo-fl** [comment]
Hi @rafaelbn ,

> How you get the button "UPDATE AND VALIDATE"? I don't see clearly in the README all the use cases

As @legalsylvain  says, the invoice must be unvalidated for the "UPDATE AND VALIDATE" option to appear. I understand that the idea of this button is to update the rate and validate the invoice in one step.
The steps seen in the video I made https://www.awesomescreenshot.com/video/19430792?key=d13f81e38d852092923042d0b0e791ed are as follows:
1. The invoice is in draft status
2. I fill in the invoice data so that it can be validated later.
3. I am changing the price.
4. I click the "Check Supplier Infos" button.
5. Click the "UPDATE AND VALIDATE" button. 
6. Boom! 😛

I hope I have helped you to clarify the issue.

Best regards,

**Comment by legalsylvain** [comment]
Hi @Gelo-fl. Thanks for your feedback. I tested again, and indeed there was a trivial problem in the button "update and validate" button. 
However, the current wizard is to update the supplierinfo, not to validate the invoice. This button is useless. I so removed it.

**Comment by rafaelbn** [comment]
Thank you @Gelo-fl ! 😄  Helps a lot!

No button, no problem, OK?

**Comment by Gelo-fl** [comment]
Hi @legalsylvain  and @rafaelbn ,
Yes, as @rafaelbn  says, if there is no button, there is no problem. But while testing I noticed a behavior that I think is not correct.
If we have a supplier with scaled rates depending on the quantity, it does not always work correctly.
Example 1: We buy a product from a supplier. Up to 100u the price is 65 and more than 100 at 60. The first line of the pricelist is up to 100u and the second is over 100u. If I buy 5u the price is 65 and I update it to 70. It works correctly and updates the correct row in the pricelist. The one up to 100u. You can check it https://www.awesomescreenshot.com/video/19433329?key=fd1e997cee501dcc1cc6616039ab418e
Example 2: We buy a product from a supplier. Up to 100u the price is 65 and more than 100u the price is 60. Now the first line of the pricelist is the one over 100u and the second one is the one up to 100u. If I buy 1u the price is 65 and I update it to 70. However, when I update it, the line of the pricelist over 100u is updated because it is the one in the first position. You can check this behavior https://www.awesomescreenshot.com/video/19433428?key=cb7ef82c645d2f70ea7eee694fac8a0b
The same thing happens with dates. If there are several lines in the pricelist, either because there is a scaling of quantities or different rates between dates, the first one is always updated. and sometimes it is not correct.

**Comment by legalsylvain** [comment]
Hi @Gelo-fl.

>  If we have a supplier with scaled rates depending on the quantity, it does not always work correctly.
> The same thing happens with dates.

totally agree. It's a limitation of the current implementation. This feature has never been implemented since the beginning, 8 versions ago : https://odoo-community.org/shop/account-invoice-supplier-info-update-313#attr=5826

As I think it will be hard to implement properly, we should merge this PR and wait for another PR that adds this feature. 
If you try to implement this missing feature, please ping me on the PR, I'll review it !

Thanks.

**Comment by Gelo-fl** [comment]
> Hi @Gelo-fl.
> 
> > If we have a supplier with scaled rates depending on the quantity, it does not always work correctly.
> > The same thing happens with dates.
> 
> totally agree. It's a limitation of the current implementation. This feature has never been implemented since the beginning, 8 versions ago : https://odoo-community.org/shop/account-invoice-supplier-info-update-313#attr=5826
> 
> As I think it will be hard to implement properly, we should merge this PR and wait for another PR that adds this feature. If you try to implement this missing feature, please ping me on the PR, I'll review it !
> 
> Thanks.

@legalsylvain Okay. Also, I don't think it's going to be easy to fix.

**Pull request merged**
