### PR TITLE
Migration V9 account_payment_term_extension

### PR DESCRIPTION
**Pull request by jcoux**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@jcoux, have you analyzed the mentioned module in the issue?

**Comment by damdam-s** [comment]
:+1:  Great !
This PR fix https://github.com/odoo/odoo/pull/10458 (https://github.com/OCA/OCB/pull/418) by adding a field in payment term form view. 
cc @njeudy

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Sorry, but I don't agree to go with this module without at least check and merge the functionality of https://github.com/OCA/account-payment/tree/8.0/account_payment_term_multi_day

:-1: until then

**Comment by jcoux** [comment]
Hi @pedrobaeza 
I will see for merge the `account_payment_term_multi_day` module with this `account_payment_term extension` module.
And I will add the result of merge on this PR.

**Comment by pedrobaeza** [comment]
Thank you very much!

**Comment by jcoux** [comment]
@pedrobaeza 
The functionality of https://github.com/OCA/account-payment/tree/8.0/account_payment_term_multi_day has been merged on this module.

**Comment by pedrobaeza** [comment]
You have forgotten the post-init-hook in https://github.com/OCA/account-payment/blob/8.0/account_payment_term_multi_day/__init__.py#L20 (it should be now in the hooks.py file according guidelines).

You can also take my nice icon for the module.

**Comment by jcoux** [comment]
Thanks @pedrobaeza for you review.

About the post-init-hook, its goal was to populate the `payment_days`  field with the `days2` field because in the `account_payment_term_multi_day` module, the `days2` field was replaced by the `payment_days` field.
However, on Odoo V9, the `days2` field doesn't longer exists and has been replaced by payment term options.
Thats why i didn't merge this post-init-hook.

Maybe I don't understand well what you did in your `post_init_hook`. Can you explain me what this script does ?

About your nice icon, i will add it to this module.

**Comment by pedrobaeza** [comment]
@jcoux, thanks for your answer. OK, I see the new behaviour. According this, I see the best integrated option is to add a new option called "Specific payment days" to the existint list ("Day(s) after the invoice date", "Fixed day of the following month", "Last day of following month", "Last day of current month"), and when selected, then the field is shown (and required). At computation time you have to check this new value for changing the computation.

**Comment by jcoux** [comment]
Hi @pedrobaeza 

I understand your proposition. 

However, my implementation choice was to allow the user to choose the parameters he wants to use. 

With my implementation, for options "Day(s) after the invoice date" and "Fixed day of the following month", the user can define days (Odoo 9 standard usage), weeks, months and payment days. He can define only one of this parameter, but also all parameters : that is his choice.

The result of your proposition is the same as my implementation if you choose option "Day(s) after the invoice date" and you set only the parameter "payment days".

I have also merged your tests, and there are OK with my implementation choice.

That's why i prefer keep my implementation and let the user choose the parameters he wants.

**Comment by pedrobaeza** [comment]
OK, I understand. Thanks for the explanation.

:+1:

**Comment by jcoux** [comment]
Thanks @pedrobaeza 
I will add your icon to this module and the migration will done.

**Pull request merged**
