### PR TITLE
[12.0] FIX account_invoice_force_number Italian translations, as weblate did not

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why Weblate is not working? cc @sbidoul

**Comment by sbidoul** [comment]
@eLBati what's wrong exactly? AFAICS all changes are synchronized.

**Comment by eLBati** [comment]
@sbidoul @pedrobaeza without this changes, if you install this module using Italian, in invoice form you see `Force Number` instead of `Numero da forzare`, for example

**Comment by primes2h** [comment]
@sbidoul 
There are still mismatches between .pot and .po files.

e.g.
account_invoice_force_number
partner_contact
l10n_it_rea
l10n_it_fatturapa
l10n_it_fatturapa_in
l10n_it_fatturapa_pec

**Comment by eLBati** [comment]
@pedrobaeza @sbidoul what do you think?

**Comment by sbidoul** [comment]
@eLBati there is a bug in weblate somewhere. I'll try to put a workaround in place. I'll run a refresh over the week-end, please leave this PR open until then so we can check.

**Comment by eLBati** [comment]
@sbidoul thanks

**Comment by sbidoul** [comment]
I just forced the msgmerge addon to run on partner-contact, account-invoincing and l10n-italy and it picked quite a few .pot changes... We need to continue investigations to understand why the msgmerge weblate addon is not triggered when needed.

**Comment by sbidoul** [comment]
So I think this PR can be closed.

**Comment by primes2h** [comment]
> So I think this PR can be closed.

> I just forced the msgmerge addon to run on partner-contact, account-invoincing and l10n-italy and it picked quite a few .pot changes... We need to continue investigations to understand why the msgmerge weblate addon is not triggered when needed.

Thanks a lot, now all work flawlessly.
We indeed need to keep on investigating on this, it's a really frustrating issue.

**Comment by primes2h** [comment]
> So I think this PR can be closed.

:ok_hand:

**Comment by primes2h** [comment]
@sbidoul 
I just caught one.

1) A source string has been modified yesterday in this commit 

https://github.com/OCA/l10n-italy/commit/1e7283e0704599fdce8d04e255a0db1336030265#diff-a1b600a217458c87c2b54a559199629aL133

2) New .pot file has been generated with this commit.


https://github.com/OCA/l10n-italy/commit/7ed05194603aaf7da01dad97bd512ceb8744588b

3) In weblate .po file is not updated
https://translation.odoo-community.org/translate/l10n-italy-12-0/l10n-italy-12-0-l10n_it_fatturapa_in/it/?type=all&offset=156


I noticed a strange thing, have a look at the commit time and GMT.

String change:
Date:   Mon Jan 28 14:57:52 2019 +0100

.pot update:
Author: oca-travis <oca+oca-travis@odoo-community.org>
Date:   Mon Jan 28 14:53:03 2019 +0000

Might this give us a clue?

**Comment by primes2h** [comment]
@sbidoul 
Another (same) issue here:

1) Commit made yesterday to fix an error (an important one) in a source string:
https://github.com/OCA/l10n-italy/pull/891/commits/2448fa717dcf2956028f43212154d57567213f21
Date:   Wed Jan 30 17:53:43 2019 +0100

2) oca-travis has correctly updated .pot file:
https://github.com/OCA/l10n-italy/commit/be98ca5a7e09c74d79aafd007530fd4996761240
Date:   Wed Jan 30 21:00:57 2019 +0000

3) .po file in weblate has not been updated:
https://translation.odoo-community.org/projects/l10n-italy-12-0/l10n-italy-12-0-l10n_it_account_stamp/it/

**Comment by sbidoul** [comment]
@primes2h I just ran a manual refresh on l10n-italy.

Following guidance from @nijel whom I had the pleasure to meet at FOSDEM, I also implemented some additional error handling by applying some code from weblate master branch, in the hope to detect what the root cause is.

**Comment by primes2h** [comment]
@sbidoul 
That's wonderful, let me know if you need some help.
Thanks a lot.

**Pull request closed without merging**
