### PR TITLE
[13.0][ADD] account_portal_invoice_search: New module to search invoices in portal

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT40857

ping @sergio-teruel @chienandalu

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Careful there. Your search overrides the user's access rules :fearful: 

Peek 10-01-2023 11-45

**Comment by CarlosRoca13** [comment]
Solved @chienandalu

**Review by chienandalu — APPROVED** [review]
Thanks! :+1:

**Review by ioans73 — APPROVED** [review]
Functional review 👍🏻

**Pull request merged**
