### PR TITLE
[16.0][MIG] account_invoice_refund_line_selection: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
#1250

### CODE REVIEW

**Review by ljsalvatierra-factorlibre — APPROVED** [review]

**Review by Gelo-fl — APPROVED** [review]
Functional revision OK

**Review by SoniaViciana — APPROVED** [review]
Functional review: LGTM

**Comment by RodrigoBM** [comment]
ping @AaronHForgeFlow

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test

**Pull request merged**
