### PR TITLE
[FIX] PEP8

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by bwrsandman** [comment]
:+1: 
Could you remove the deprecated call to `travis_run_flake8`

**Comment by eLBati** [comment]
On 09/12/2014 07:13 PM, Sandy wrote:

> :+1:
> Could you remove the deprecated call to |travis_run_flake8|

Done.
Thanks

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
Needs a rebase

**Comment by eLBati** [comment]
account-invoicing 7.0 should be green now, so I close this

**Pull request closed without merging**
