### PR TITLE
[16.0][MIG] account_invoice_supplierinfo_update_discount : Migration to 16.0

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial migration of the glue module ``account_invoice_supplierinfo_update_discount``

- classic migration from 14.0 to 16.0
- commit to review : 
    - https://github.com/OCA/account-invoicing/pull/1444/commits/c8c26c5c8cbc3322bfadf99cbef1daf447042991
    - https://github.com/OCA/account-invoicing/pull/1444/commits/14873afbf436ae5ebe0b9c54980fd46253ea94ec

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration account_invoice_supplierinfo_update_discount

This one is ready to review.

**Comment by carolinafernandez-tecnativa** [comment]
@legalsylvain 

Thanks for this. Could you follow migration guide ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

Please rebase for getting a fresh runboat. Thanks

**Comment by legalsylvain** [comment]
> Please rebase for getting a fresh runboat. Thanks

OK !

/ocabot rebase


> Thanks for this. Could you follow migration guide ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

I did ! what did i forget?

**Comment by carolinafernandez-tecnativa** [comment]
> > Please rebase for getting a fresh runboat. Thanks
> 
> OK !
> 
> /ocabot rebase
> 
> > Thanks for this. Could you follow migration guide ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch
> 
> I did ! what did i forget?

Hi!

1- PR name is not correct as Migration guide
2- Still have administrative commits.
image

3-  Commit's name should be as migration guide says.

See here an example: https://github.com/OCA/stock-logistics-warehouse/pull/1846

4- I tested the module and I have two situations:

- Im not being able to see current discount 2 and current discount 3
- When I enter a discount and press the button "Update supplier infos", im getting this error message:

image

Could you please check it? Thanks!

**Comment by legalsylvain** [comment]
Hi @carolinafernandez-tecnativa. Thanks for the precisions. 

> 1- PR name is not correct as Migration guide :  

Renamed.

> 2- Still have administrative commits.  

2 commits merged.

> 3- Commit's name should be as migration guide says. : 

migration commit renamed.

> Im not being able to see current discount 2 and current discount 3

That's quite normal, as it is not in the scope of this module. The feature you want is in another glue module, named account_invoice_supplierinfo_update_triple_discount


> When I enter a discount and press the button "Update supplier infos", im getting this error message:

i confirm there the bug, but it is not related to the current PR. It is related to the migrated module account_invoice_supplierinfo_update module. 
Step to reproduce : 

1) Do not belong to the group "Tecnical / Manage Multiple Units of Measure" > click on "check supplier infos" > Click on "Update Supplier Infos" >> ERROR.
1) belong to the group "Tecnical / Manage Multiple Units of Measure" > click on "check supplier infos" > Click on "Update Supplier Infos" >> OK.

I don't understand why there is a problem. I added ``force_save="1"`` but without success. Do you have an idea ? 

https://github.com/OCA/account-invoicing/blob/16.0/account_invoice_supplierinfo_update/wizard/wizard_update_invoice_supplierinfo.xml#L40

anyway,unrelated to the current PR.

**Comment by pedrobaeza** [comment]
It requires to add double the same field, one with groups, and the other invisible and without groups. IMO it's a screw of the framework in the new way of fetching/handling the views. They have needed to do the same with `company_id` field. Check the diff I added the other day about this on the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0/_compare/ad52290cdb5f5385ae25fad0c4862a4fa244d9f8...e2d0ba6cd1bfdc8cee787c3fd61b6feecfbe49cc

**Comment by legalsylvain** [comment]
Hi @pedrobaeza. A huge thanks for all that information. I didn't know. 
I fixed the bug here : https://github.com/OCA/account-invoicing/pull/1560

personal PoV : I see that new requirement as a regression, and can be source of error. But well.

**Comment by legalsylvain** [comment]
@carolinafernandez-tecnativa : it could be OK now. Could you confirm ?

**Comment by carolinafernandez-tecnativa** [comment]
@legalsylvain 
It works ok!

Please squash administative commits

image

**Comment by legalsylvain** [comment]
> Hi @carolinafernandez-tecnativa

Thanks for your review.

Don't understand what you want I do with commits. there is one commit oca-bot authored. So I don't see with wich commit I can squash it.

And for the two last commits, there are different commits and there are not administrative.

Let me know ! 
thanks !

**Comment by carolinafernandez-tecnativa** [comment]
> > Hi @carolinafernandez-tecnativa
> 
> Thanks for your review.
> 
> Don't understand what you want I do with commits. there is one commit oca-bot authored. So I don't see with wich commit I can squash it.
> 
> And for the two last commits, there are different commits and there are not administrative.
> 
> Let me know ! thanks !

Hi, please check this documentation: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

See this example to see how commits has to be. 
 https://github.com/OCA/stock-logistics-warehouse/pull/1846

**Comment by legalsylvain** [comment]
Hi @carolinafernandez-tecnativa. The commits you mention are not administrative. There are done by bot because I gave a rebase order. But there is nothing to squash. If you don't think so, please explicit the list(s) of commits (with hash) you consider to be squashed. 

kind regards.

**Comment by carolinafernandez-tecnativa** [comment]
> Hi @carolinafernandez-tecnativa. The commits you mention are not administrative. There are done by bot because I gave a rebase order. But there is nothing to squash. If you don't think so, please explicit the list(s) of commits (with hash) you consider to be squashed.
> 
> kind regards.

Hi, it should be like this

image

**Comment by pedrobaeza** [comment]
@carolinafernandez-tecnativa the second one is not an administrative commit, as Sylvain has improved the module and decided to put it in a separate commit, but the first one is.

**Comment by legalsylvain** [comment]
should be OK now.

**Review by pedrobaeza — APPROVED** [review]

**Review by carolinafernandez-tecnativa — APPROVED** [review]
TT45173

**Pull request merged**
