### PR TITLE
[12.0] [FIX] account_invoice_triple_discount: Fix precision when compute discount

### PR DESCRIPTION
**Pull request by ramiadavid**
Fix the bugs described here #1240

### CODE REVIEW

**Review by cscocca — APPROVED** [review]
These changes seems to works correctly I think it is ready to merge

**Review by Saran440 — APPROVED** [review]

**Review by cscocca — APPROVED** [review]

**Comment by cscocca** [comment]
Hi, why this pr still is not merged? Seam I have not permission to do it. 
Can anyone merge?

**Review by sergiocorato — APPROVED** [review]

**Comment by cscocca** [comment]
@sergiocorato some problems happens during merge process?

**Comment by sergiocorato** [comment]
@c-amara Yes, repo configuration must be upgraded (see https://app.travis-ci.com/github/OCA/account-invoicing/jobs/588401877 ) as all 12.0 with .travis.yml are failing.

**Comment by cscocca** [comment]
@sergiocorato but this ERROR is not linked directly to this PR but to all 12.0 PR of this repository? Did I understand correctly? 
And no solutions is available?

**Comment by c-amara** [comment]
Seems linked to the obsolete use of Python 3.5 and if it is true no one else 12.0 oca module can be merged.

**Comment by sergiocorato** [comment]
@c-amara please wait until I check how to upgrade to the new configuration

**Comment by sergiocorato** [comment]
@c-amara This PR should solve the problem: #1285

**Comment by cscocca** [comment]
@sergiocorato grazie. I wait for the merge process do the rest.

**Comment by sergiocorato** [comment]
@c-amara #1285 needs review to proceed here

**Pull request merged**
