### PR TITLE
[12.0] [MIG] account_invoice_pricelist

### PR DESCRIPTION
**Pull request by Nikul-Chaudhary**
Account - Pricelist on Invoices
===============================
* Add a stored field pricelist on invoices, related to the partner pricelist.
* Use this pricelist when manually adding invoice lines
* Possibility to group by pricelist on account.invoice view.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Please replace yml data
```
2019-01-27 17:10:31,069 6454 WARNING openerp_test odoo.modules.loading: Module account_invoice_pricelist demo data failed to install, installed without demo data
Traceback (most recent call last):
File "/home/travis/odoo-12.0/odoo/modules/loading.py", line 84, in load_demo
load_data(cr, idref, mode, kind='demo', package=package, report=report)
File "/home/travis/odoo-12.0/odoo/modules/loading.py", line 68, in load_data
tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
File "/home/travis/odoo-12.0/odoo/tools/convert.py", line 805, in convert_file
raise ValueError("Can't load unknown file type %s.", filename)
ValueError: ("Can't load unknown file type %s.", 'demo/res_groups.yml')
```

**Comment by Nikul-Chaudhary** [comment]
@StefanRijnhart Remove .yml, No need here

**Comment by StefanRijnhart** [comment]
Agreed in this case, thanks! Can you squash your latest commits into the one upgrade commit?

**Comment by Nikul-Chaudhary** [comment]
> Agreed in this case, thanks! Can you squash your latest commits into the one upgrade commit?

@StefanRijnhart Done

**Comment by Nikul-Chaudhary** [comment]
@StefanRijnhart @OCA/accounting-maintainers could you please review code?

**Review by StefanRijnhart — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by legalsylvain** [comment]
FYI : minor patch you can review here : https://github.com/OCA/account-invoicing/pull/573
regards.

**Pull request merged**
