### PR TITLE
[15.0] [MIG] account_invoice_fixed_discount

### PR DESCRIPTION
**Pull request by xhnilic3**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
please rebase

**Comment by MiquelRForgeFlow** [comment]
please cherry-pick https://github.com/OCA/account-invoicing/commit/1c43fe5b468ecb1945538a53c4fabea372694d61

**Comment by ao-landoo** [comment]
Created new PR as no activity here (#1276)

**Comment by rafaelbn** [comment]
Migrated https://github.com/OCA/account-invoicing/tree/15.0/account_invoice_fixed_discount

**Pull request closed without merging**
