### PR TITLE
[15.0][FIX] account_invoice_fixed_discount: Fix Division by zero  error

### PR DESCRIPTION
**Pull request by angelmoya**

### CODE REVIEW

**Comment by angelmoya** [comment]
#1557

**Comment by angelmoya** [comment]
Remember: fixed discount module is not compatible with triple discount, so you need to uninstal triple discount before test it

**Review by JorgeQuinteros — APPROVED** [review]
LGTM Technical and Functional Review

**Review by JGarcia-Panach — APPROVED** [review]
LGTM

**Review by valentincastravete — APPROVED** [review]
**LGTM!** Technical and Functional Review

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
