### PR TITLE
[WIP][11.0][FIX] account_invoice_supplier_self_invoice: self invoice number on copy

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please @ljsalvatierra-factorlibre check travis to get the error and try fo fix it! 😄 Thank you!

**Comment by ljsalvatierra-factorlibre** [comment]
> Please @ljsalvatierra-factorlibre check travis to get the error and try fo fix it! smile Thank you!

Hi, the issue comes from here

- https://github.com/OCA/pylint-odoo/pull/396

```
pylint-plugin-utils==0.6
pylint<=2.13.5 ;python_version >= '3'
```

to

```
pylint-plugin-utils==0.7
pylint==2.13.5
```

```
ERROR: Could not find a version that satisfies the requirement pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1)) (from versions: 0.1, 0.1.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.6, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1))

ERROR: Could not find a version that satisfies the requirement pylint==2.15.* (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 2)) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 2.0.0.dev0, 2.0.0.dev1, 2.0.0.dev2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0.dev0, 2.3.0.dev1, 2.3.0.dev2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2)
ERROR: No matching distribution found for pylint==2.15.* (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 2))
```

Any advice on how to proceed? Thank you

**Comment by rafaelbn** [comment]
No idea, maybe @moylop260 can help?

**Comment by moylop260** [comment]
@sbidoul 

Are we have planned to support 11.0 in the new CI & pre-commit things?

**Comment by sbidoul** [comment]
Yes there is a copier template for 11.0. You can apply it to the project and answer GitHub to the CI question.

**Pull request closed without merging**
