### PR TITLE
[FIX]  account_invoice_change_currency: Failing when new invoice crea…

### LINKED ISSUE #476: [12.0] account_invoice_change_currency: psycopg2.ProgrammingError: syntax error at or near ")" LINE 5: mtv.mail_message_id IN ()
image

### PR DESCRIPTION
**Pull request by hugho-ad**
…ted, newid record not consider at onchange and get_last_currency method

fix https://github.com/OCA/account-invoicing/issues/476

### CODE REVIEW

**Comment by hugho-ad** [comment]
@moylop260 

could you review please

**Review by moylop260 — COMMENTED** [review]
I think that model is falsy
I mean, try using “if not self.id”

**Comment by hugho-ad** [comment]
@moylop260 you're right

Done thanks!

**Review by moylop260 — APPROVED** [review]

**Comment by hugho-ad** [comment]
@pedrobaeza 

could you review / merge please

**Comment by pedrobaeza** [comment]
Merging based on trust.

**Pull request merged**
