### PR TITLE
[16.0][MIG] account_invoice_change_currency

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**
https://github.com/OCA/account-invoicing/issues/1250

### CODE REVIEW

**Review by AnizR — APPROVED** [review]
code LGTM

**Comment by ljsalvatierra-factorlibre** [comment]
Hi, is it ok to merge? Can anyone please take a look?

**Review by RodrigoBM — APPROVED** [review]

**Comment by RodrigoBM** [comment]
is it possible to merge this PR? @OCA/accounting-maintainers

**Comment by rafaelbn** [comment]
Could you please show functionality in runboat in a 1 minute video?

**Review by MayteGLC — APPROVED** [review]
Functional review OK

https://www.awesomescreenshot.com/video/17763320?key=2ccee70e124bc26107e41576f93c13eb

**Comment by RodrigoBM** [comment]
> Functional review OK
> 
> https://www.awesomescreenshot.com/video/17763320?key=2ccee70e124bc26107e41576f93c13eb

FYI: @rafaelbn

**Review by rafaelbn — APPROVED** [review]
You are awesome! ❤️ 


/ocabot merge patch

**Pull request merged**
