### PR TITLE
[ADD] account_invoice_pro_forma_sequence

### PR DESCRIPTION
**Pull request by SimoRubi**
Module to track pro-forma invoices with sequences.
Please check, thanks

### CODE REVIEW

**Review by hurrinico — APPROVED** [review]
👍 just code review

**Review by eLBati — APPROVED** [review]
LGTM

**Review by tafaRU — CHANGES_REQUESTED** [review]
Please move https://github.com/OCA/account-invoicing/pull/394/commits/e0425e8f7efad7ca33cc91da49f4644fc3ffbaa5 to a separate PR

**Comment by SimoRubi** [comment]
Done, now this depends on https://github.com/OCA/account-invoicing/pull/401

**Comment by SimoRubi** [comment]
@tafaRU is it ok now? Please see #401

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers is this ok to be merged?

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can this be merged?
Thanks

**Review by elicoidal — COMMENTED** [review]
LGTM but I have a general question. It seems weird to me to have a number different from the final number (I would have tended to use the invoice number in the proforma stage).
At least in China it is not an issue because there is an official invoice with separate number.
Was there a specific legal reason to implement it separately?
Would there be reason (legal or not) to not have it separately?

**Comment by SimoRubi** [comment]
@elicoidal Thanks for the review!
I implemented it in a separate field for a couple of reasons:

- `account.invoice.number` is a related field from `move_id.name` and I do not want mess up with the account move

- In many points (https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_invoice.py#L452 is one) Odoo applies some logic based on the fact if the invoice has a number or not, and I do not want to mess up there either

I do not know about legal reasons but *coding reasons* are enough for me

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
Let's move on: if there is a requirement in the future for same number then a configuration could be added by the requester :wink:

**Pull request merged**
