### PR TITLE
[12.0][FIX] account_invoice_refund_link: Fix tests

### PR DESCRIPTION
**Pull request by ernestotejeda**
TT18546

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is this needed? Please explain the problem you faced.

**Comment by ernestotejeda** [comment]
I got this error during tests performance:
https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_invoice.py#L842
This PR could fix that.

**Comment by pedrobaeza** [comment]
That's not possible. The possible problem is that the scaffolding doesn't contain `l10n_generic_coa` in the included addons.

**Comment by pedrobaeza** [comment]
This is finally not needed.

**Pull request closed without merging**
