### PR TITLE
[FIX] account_invoice_date_due: Small fixes to the initial version

### PR DESCRIPTION
**Pull request by luisg123v**
This applies pending comments on #632, which are:
- Fix some typos
- Be consistent with the license, use AGPL-3
- Add maintainer (not commented)
- Set group data as noupdate (not commented)

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 & @kittiu  
Could you approve, please?

**Review by moylop260 — APPROVED** [review]

**Comment by moylop260** [comment]
The red is unrelated:
 - `account_menu_invoice_refund`

**Comment by luisg123v** [comment]
@pedrobaeza could you merge, please?

**Comment by pedrobaeza** [comment]
Sorry, I'm not anymore OCA's community manager and also the build is red although unrelated.

**Review by kittiu — APPROVED** [review]
Just awaiting for this PR to merged, then, this one should be fine. https://github.com/OCA/account-invoicing/pull/695

**Comment by luisg123v** [comment]
@kittiu  Done, rebased and it's not red anymore. Could you merge, please?

**Comment by luisg123v** [comment]
@OCA-git-bot need help dude? :laughing:

**Pull request merged**
