### PR TITLE
[17.0][MIG]account_invoice_fixed_discount: Migrated module to v17.0

### PR DESCRIPTION
**Pull request by fd-oerp**

### CODE REVIEW

**Comment by fd-oerp** [comment]
Hi @OCA-git-bot  can I have any update regarding this PR ?

**Comment by fd-oerp** [comment]
Hi @rafaelbn Can I have any update regarding this PR ?

**Comment by fd-oerp** [comment]
Hi @JordiBForgeFlow , can you let me know if I'm missing anything in this PR?

**Comment by fd-oerp** [comment]
Hi @JordiBForgeFlow , can you please review this ?

**Review by MohamedOsman7 — APPROVED** [review]
Code & functionality LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
