### PR TITLE
[11.0][MIG] account_invoice_view_payment

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Superseeds https://github.com/OCA/account-invoicing/pull/399.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
:green_apple: 

@AMhadhbi @jbeficent @pedrobaeza reviews are welcome

**Comment by AMhadhbi** [comment]
@mreficent Great Job 👍 Thanks.
but just I have one question about the tools travis-ci : did you fix the issue related to Travis-CI? because I found issue during test the module. Also now, does not exist in the list, just Runbot and codecov Patch/project. It should be 4 successful checks.

**Comment by MiquelRForgeFlow** [comment]
Yeah, Travis-CI disappeared for some odd reason, maybe by pushing too consecutively. I will try to reactivate it.

**Comment by AMhadhbi** [comment]
Yeah. Perfect 👍 
Everything now its fine.
It should be merged :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
