### PR TITLE
[16.0][MIG] account_ invoice_payment_term_date_due: Migration to 16.0

### PR DESCRIPTION
**Pull request by pausanchezqubiq**

### CODE REVIEW

**Comment by ferran-S73** [comment]
Please merge your last commit into the migration commit

**Comment by pausanchezqubiq** [comment]
@ferran-S73 already there!

**Review by ferran-S73 — APPROVED** [review]

**Comment by BT-anieto** [comment]
Hi @pausanchezqubiq ! Could you rebase to 16.0 branch so that the build is workign and it can be merged? Thank you!

**Review by BT-anieto — COMMENTED** [review]
There should be no change in the README.rst file, since the bot will automtically update it

**Comment by BT-anieto** [comment]
Hello @pausanchezqubiq. Will you take care of this PR or shall I close it and take it myself?

**Comment by pedrobaeza** [comment]
Superseded by #1607

**Pull request closed without merging**
