### PR TITLE
Update report_invoice.xml

### PR DESCRIPTION
**Pull request by mkrajaci**
On line 9 was the wrong iterator name. "l" needs to be line.

### CODE REVIEW

**Review by astirpe — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Please sign the CLA

**Comment by mkrajaci** [comment]
It is signed and sent to 

cla@odoo-community.org

**Review by astirpe — APPROVED** [review]

**Comment by mkrajaci** [comment]
@astirpe Do I have to do something more for this PR to be merged?

**Comment by astirpe** [comment]
@mkrajaci this PR needs at least another reviewer to be merged.

**Comment by mkrajaci** [comment]
@pedrobaeza Could you be the second reviewer?

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
