### PR TITLE
[16.0] account_invoice_pricelist: Use setter for triple discount

### PR DESCRIPTION
**Pull request by grindtildeath**
Relates to #1638

### CODE REVIEW

**Comment by legalsylvain** [comment]
This should not be required, with latest refactoring. don't you think ? 

Could you provide a test that is failing without that patch ? Thanks !

**Comment by grindtildeath** [comment]
It is needed if you test in the UI.

Without this, the onchange on product (when creating a new line and selecting the product) will not set the discount in discount1 field. We would need the inverse function for this to happen when the document is saved, which will in turn overwrite any changes done in other discount fields.

Requiring the user to save the invoice before being able to set the fields properly is not nice.

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
hi @OCA/accounting-maintainers : could you merge this one ? it is required to merge https://github.com/OCA/account-invoicing/pull/1840

thanks !

**Review by mmequignon — APPROVED** [review]

**Pull request merged**
