### PR TITLE
[14.0][MIG] sale_timesheet_invoice_description

### PR DESCRIPTION
**Pull request by clementmbr**
Basic migration adapting the tests and improving the check to catch sale.order.line's timesheets.

### CODE REVIEW

**Comment by kittiu** [comment]
Here may be the fix, https://github.com/OCA/account-invoicing/pull/910/files by @JordiBForgeFlow 
I will make the cherry pick to fix account_billing.

**Comment by rvalyi** [comment]
@clementmbr can you rebase please? the offending test has been fixed in #911

**Comment by bosd** [comment]
I'm actually using this module. Works fine!! :+1: 
Lets get this one merged!
ping @clementmbr

**Comment by clementmbr** [comment]
@kittiu @bosd @rvalyi sorry for the late reply, I made the rebase!

**Review by bosd — APPROVED** [review]
Migration LGTM!
I am using this in production.
I've encoutered a problem with this module. When there is no invoiceline descirption selected on a partner, it throws an internal server error.
 Imo, it would be better to have a default description selected, or an usefull error message.
  
 need to do some further testing on other versions and installs,as it might occure there as well. Will open a new issue, when I have more info. 
it is no stopper for the migration :)

**Comment by bosd** [comment]
Im having problems on a database that timesheet lines get unlinked from the invoice.

Not sure if it is related to this pr. Or one of the other modules that are installed like tinesheet_sheet.

Will report back when more info is available.

**Comment by bosd** [comment]
went trough the code again. The problem is likely not caused by this module, but in Odoo native.
@clementmbr  Does it need a rebase again before it can be merged?

**Comment by bosd** [comment]
my bad. Did'nt notice there is a superseding pr.
https://github.com/OCA/account-invoicing/pull/1078

This one can be closed now.

**Review by jordancoest — APPROVED** [review]

**Review by JulianaPoudou — APPROVED** [review]

**Comment by rvalyi** [comment]
@clementmbr can you check? I think https://github.com/OCA/account-invoicing/pull/1078 doesn't include your improvements...

**Comment by pedrobaeza** [comment]
Already migrated.

**Pull request closed without merging**
