### PR TITLE
[16.0] mig account_invoice_supplierinfo_update_triple_discount

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial migration of the glue module ``account_invoice_supplierinfo_update_triple_discount``

- classic migration from 12.0 to 16.0
- commit to review : 
    - https://github.com/OCA/account-invoicing/commit/bef02ea05f3989dc38d6d9478d0288e0faf624c7

### CODE REVIEW

**Comment by legalsylvain** [comment]
This one is ready to review.
CC : other contributors : @ sergio-teruel, @sergiocorato

**Review by quentinDupont — APPROVED** [review]
Code review and tested

**Comment by legalsylvain** [comment]
Friendly reminder @sergio-teruel, @sergiocorato. could you take a look on this one ? thanks !

**Review by sergio-teruel — APPROVED** [review]
LGMT

**Comment by legalsylvain** [comment]
Thanks !

/ocabot merge nobump

**Pull request merged**
