### PR TITLE
[16.0][mig] account_invoice_force_number

### PR DESCRIPTION
**Pull request by aktiv-heli-kantawala**

### CODE REVIEW

**Comment by JavierIniesta** [comment]
Hi @heliaktiv 
Please could you take into account this step from the migration wiki? (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)

- Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for a procedure for reducing commits from "OCA Transbot...".

**Comment by Gelo-fl** [comment]
@heliaktiv Runboat does not work. Can you enable it to check the module?
Thanks in advance.

**Review by SoniaViciana — COMMENTED** [review]
Functional review done.

This addons works fine for me. However, it allows you to force numbers without limitation, you can take an invoice that already has a given number, pass it to draft and validate it again with a different new number.

The above can be legally problematic in certain countries... In my opinion I would add some [IMP]:

* "Force number" visible only on OUT type invoices.

* "Force number" visible only in certain invoices. Enable permission at journal.

Thanks for the contribution!

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Comment by tafaRU** [comment]
@heliaktiv could you please address https://github.com/OCA/account-invoicing/pull/1441#issuecomment-1602761005 ?

**Comment by tafaRU** [comment]
@JavierIniesta @heliaktiv I took care of squashing the administrative commits. Now the PR is ready to be merged.

**Comment by tafaRU** [comment]
@SoniaViciana concerning https://github.com/OCA/account-invoicing/pull/1441#pullrequestreview-1571620117 is a new feature request so please open a related issue. Thank you in advance.

**Pull request merged**
