### PR TITLE
13.0 mig account payment term extension

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm thinking that this module doesn't belong here, but on OCA/account-payment, as it's not related to (only) invoicing. Please check also Travis status.

**Comment by emagdalenaC2i** [comment]
Travis status is red because of the pre-commit
I have tried a few options and seems there are no way to get it right

**Comment by pedrobaeza** [comment]
But at the end it's all automatic:

- Install pre-commit once in your equipment (in Linux)
- Run `pre-commit install -f` in the repo.
- Run `pre-commit run -a` in the repo.
- Commit

**Comment by emagdalenaC2i** [comment]
First, I usually work with windows, not Linux. So, that's an issue to me. Yes, I know I can run a VM... etc. But honestly, I am not interested in increasing the entropy of my business workflows and programming in Odoo is not relevant to the company.

Second, `pre-commit install -f` should be run in each repo?

And last, I doesn't have issues with other PRs and I think this is because this one is the first PR in the repo. That also happened to me with other first-repo PRs in other repos

**Comment by pedrobaeza** [comment]
Well, I don't know if pre-commit exists for Windows, but in general, everything gets complicated being done in Windows. About the install one, yes, it should be done on each repo. I don't know about the rest of the problems you have, but I don't have them in first PRs.

**Comment by pedrobaeza** [comment]
Please never use GitHub conflict resolution that creates a merge commit that messes up everything. Rebase in your local and forced push.

**Comment by emagdalenaC2i** [comment]
Ok, sorry

**Comment by pedrobaeza** [comment]
You should rebase and fix Travis.

**Comment by emagdalenaC2i** [comment]
I will in a while

**Comment by HaraldPanten** [comment]
Hi @emagdalenaC2i 

Are you planning to continue with this PR?

Thanks!

**Comment by emagdalenaC2i** [comment]
Not now, sorry. Maybe I could next week

**Comment by HaraldPanten** [comment]
> Not now, sorry. Maybe I could next week

OK!

**Comment by HaraldPanten** [comment]
Hi @emagdalenaC2i ,

It seems that @carlos-domatix opened a new migration PR for this module.

Do you prefer to continue with yours, or it's better for you to let him continue with his? https://github.com/OCA/account-invoicing/pull/714

**Comment by emagdalenaC2i** [comment]
ok, closed

**Pull request closed without merging**
