### PR TITLE
[17.0][MIG] account_move_tier_validation

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Continued from https://github.com/OCA/account-invoicing/pull/1634 by @moitabenfdz

### CODE REVIEW

**Review by BT-etejeda — APPROVED** [review]

**Review by celm1990 — APPROVED** [review]
LGTM please squash administrative commits

**Comment by StefanRijnhart** [comment]
@celm1990 commits squashed, thanks.

**Review by celm1990 — APPROVED** [review]
LGTM

**Pull request merged**
