### PR TITLE
[MIG] account_invoice_fiscal_position_update: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
+1 technical review + functional test on runboat

**Review by JoanMForgeFlow — CHANGES_REQUESTED** [review]
This commit should be the [IMP] Black, issort, prettier: https://github.com/OCA/account-invoicing/pull/1084/commits/610ce6948c7456abab255bc597a19bb501857a29
and your commit of [IMP] Black, issort, prettier, is your actual migration.

Please, could you change the order?

**Comment by nicomacr** [comment]
@JoanMForgeFlow Ready the changes

**Comment by nicomacr** [comment]
@HaraldPanten could you check this PR?

**Review by rafaelbn — APPROVED** [review]
tested functionaly in runboat 👍

**Comment by rafaelbn** [comment]
Please @JoanMForgeFlow review as you comments were attended and answered, thanks!

**Comment by nicomacr** [comment]
@JoanMForgeFlow could you review this?

**Comment by JoanMForgeFlow** [comment]
LGTM! Thanks for the changes. @nicomacr @rafaelbn

**Comment by yankinmax** [comment]
@nicomacr I have an issue on my PR, related to the tests in this module.
Could you pls take a look?
https://github.com/OCA/account-invoicing/pull/1163

**Comment by ivantodorovich** [comment]
For some reason this module is making `15.0` branch red 🤔 

<details>
<summary>Traceback</summary>

```python-traceback
2022-06-06 17:10:04,831 256 ERROR odoo odoo.addons.account_invoice_fiscal_position_update.tests.test_inv_fiscal_pos_update: ERROR: TestProductIdChange.test_fiscal_position_id_change
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_fiscal_position_update/tests/test_inv_fiscal_pos_update.py", line 129, in test_fiscal_position_id_change
    out_invoice.with_context(check_move_validity=False)._onchange_partner_id()
  File "/__w/account-invoicing/account-invoicing/account_invoice_fiscal_position_update/models/account_move.py", line 18, in _onchange_partner_id
    self._onchange_fiscal_position_id_account_invoice_fiscal_position_invoice()
  File "/__w/account-invoicing/account-invoicing/account_invoice_fiscal_position_update/models/account_move.py", line 38, in _onchange_fiscal_position_id_account_invoice_fiscal_position_invoice
    self._onchange_invoice_line_ids()
  File "/opt/odoo/addons/account/models/account_move.py", line 587, in _onchange_invoice_line_ids
    self._onchange_recompute_dynamic_lines()
  File "/opt/odoo/addons/account/models/account_move.py", line 591, in _onchange_recompute_dynamic_lines
    self._recompute_dynamic_lines()
  File "/opt/odoo/addons/account/models/account_move.py", line 1121, in _recompute_dynamic_lines
    invoice._recompute_tax_lines()
  File "/opt/odoo/addons/account/models/account_move.py", line 785, in _recompute_tax_lines
    self.line_ids -= taxes_map_entry['tax_line']
  File "/opt/odoo/odoo/fields.py", line 1217, in __set__
    records.write({self.name: write_value})
  File "/__w/account-invoicing/account-invoicing/account_invoice_date_due/models/account_move.py", line 37, in write
    res = super().write(vals)
  File "/opt/odoo/addons/account/models/account_move.py", line 2294, in write
    res = super(AccountMove, self.with_context(check_move_validity=False, skip_account_move_synchronization=True)).write(vals)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/addons/mail/models/mail_activity_mixin.py", line 243, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo-venv/lib/python3.8/site-packages/odoo/addons/base_tier_validation/models/tier_validation.py", line 255, in write
    return super(TierValidation, self).write(vals)
  File "/opt/odoo/odoo/models.py", line 3858, in write
    field.write(self, value)
  File "/opt/odoo/odoo/fields.py", line 3288, in write
    return self.write_batch([(records, value)])
  File "/opt/odoo/odoo/fields.py", line 3309, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo/fields.py", line 3485, in write_real
    flush()
  File "/opt/odoo/odoo/fields.py", line 3443, in flush
    comodel.browse(to_delete).unlink()
  File "/opt/odoo/addons/account/models/account_move.py", line 4726, in unlink
    res = super(AccountMoveLine, self).unlink()
  File "/opt/odoo/odoo/models.py", line 3635, in unlink
    self.flush()
  File "/opt/odoo/odoo/models.py", line 5647, in flush
    process(self.env[model_name], id_vals)
  File "/opt/odoo/odoo/models.py", line 5638, in process
    recs._write(vals)
  File "/opt/odoo/odoo/models.py", line 3949, in _write
    cr.execute(query, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/odoo/sql_db.py", line 89, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 310, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(51, ) already exists.
```

</details>

**Pull request merged**
