### PR TITLE
[10.0][MIG] account_invoice_merge_attachment migration

### PR DESCRIPTION
**Pull request by benwillig**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this be integrated on main module?

**Comment by benwillig** [comment]
As @adrienpeiffer said in #182. There is no attachment action without document module so it could confusing.

**Review by adrienpeiffer — APPROVED** [review]
:+1: (Code review and functional test)

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Shouldn't this be auto-install?

**Comment by benwillig** [comment]
Indeed, it makes sense. I changed it @pedrobaeza

**Review by zakiuu — APPROVED** [review]
Code review

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
