### PR TITLE
[13.0] [FIX] account_move_tier_validation fix RecursionError

### LINKED ISSUE #765: [13.0] account_move_tier_validation: RecursionError
module: account_move_tier_validation
version: 13.0

Tested in runbot

**Steps to reproduce**
- Configure the module for validation of draft journal entries with admin as reviewer
- Create draft invoice with demo user
- Attemp to validate invoice with reviewer user

**Current behavior**

Error

File "/home/odoo/dependencies/server-ux/base_tier_validation/models/tier_validation.py", line 158, in write
    reviews = rec.request_validation()
  File "/home/odoo/dependencies/server-ux/base_tier_validation/models/tier_validation.py", line 351, in request_validation
    self._notify_review_requested(created_trs)
  File "/home/odoo/dependencies/server-ux/base_tier_validation/models/tier_validation.py", line 325, in _notify_review_requested
    subtype="mt_comment", body=rec._notify_requested_review_body()
  File "/.repo_requirements/odoo/addons/account_facturx/models/account_move.py", line 274, in message_post
    res = super(AccountMove, self).message_post(**kwargs)
  File "/.repo_requirements/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 1887, in message_post
    new_message = self._message_create(values)
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 2107, in _message_create
    return self.env['mail.message'].create(create_values_list)
  File "<decorator-gen-106>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/addons/mail/models/mail_message.py", line 1060, in create
    messages = super(Message, self).create(values_list)
  File "<decorator-gen-3>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3745, in create
    records = self._create(data_list)
  File "/.repo_requirements/odoo/odoo/models.py", line 3877, in _create
    records.modified(self._fields, create=True)
  File "/.repo_requirements/odoo/odoo/models.py", line 5712, in modified
    self.sudo().with_context(active_test=False)._modified_triggers(tree, create)
  File "/.repo_requirements/odoo/odoo/models.py", line 5088, in with_context
    return self.with_env(self.env(context=context))
  File "/.repo_requirements/odoo/odoo/api.py", line 497, in __call__
    return Environment(cr, uid, context, su)
  File "/.repo_requirements/odoo/odoo/api.py", line 446, in __new__
    self.registry = Registry(cr.dbname)
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 45, in __getitem__
    self[a[0]] = a[1]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 51, in __setitem__
    del self[obj]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Expected behavior**

### PR DESCRIPTION
**Pull request by CasVissers-360ERP**
Fixes #765

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Is the None state possible? and not in state_from?

**Comment by CasVissers-360ERP** [comment]
None should not be possible:
            ('draft', 'Draft'),
            ('posted', 'Posted'),
            ('cancel', 'Cancelled')

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow and required=True

**Review by AaronHForgeFlow — APPROVED** [review]
This makes sense. Not sure what was the purpose of adding that "None" there.

**Comment by AaronHForgeFlow** [comment]
ping @LoisRForgeFlow

**Review by kittiu — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, initial author was @pegonzalezspesol, maybe he could clarify what the goal was

**Review by HaraldPanten — APPROVED** [review]

**Review by pegonzalezspesol — APPROVED** [review]

**Pull request merged**
