### PR TITLE
[16.0][FIX] account_move_tier_validation: Pass context to allow confirming moves with tier validation

### PR DESCRIPTION
**Pull request by ByteMeAsap**
Fixes https://github.com/OCA/account-invoicing/issues/1698

### CODE REVIEW

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Thanks for the fix. It's not entirely clear to me what causes the issue. Would it be possible to add a reproducing test?

**Comment by ByteMeAsap** [comment]
> Thanks for the fix. It's not entirely clear to me what causes the issue. Would it be possible to add a reproducing test?

@StefanRijnhart , if you check the issue https://github.com/OCA/account-invoicing/issues/1698 , it details the steps that causes the issue. Is it possible for you to review it?

**Comment by StefanRijnhart** [comment]
@ByteMeAsap If it's that easy, then it should definitely be included as a test in the module.

**Comment by ByteMeAsap** [comment]
> @ByteMeAsap If it's that easy, then it should definitely be included as a test in the module.

@StefanRijnhart , I have added the test

**Comment by ByteMeAsap** [comment]
> @ByteMeAsap If it's that easy, then it should definitely be included as a test in the module.

@StefanRijnhart , I have added the test scripts

**Review by StefanRijnhart — APPROVED** [review]
Excellent, thanks for adding the test!

**Review by gurneyalex — APPROVED** [review]

**Comment by ByteMeAsap** [comment]
Can we have this merged?

**Pull request merged**
