### PR TITLE
[14.0][MIG] account_invoice_block_payment

### PR DESCRIPTION
**Pull request by Ricardoalso**
Backport of V15 https://github.com/OCA/account-invoicing/tree/15.0/account_invoice_block_payment

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Review by sergiocorato — APPROVED** [review]

**Comment by sergiocorato** [comment]
I didn't found the version from wich this module is migrated, can you help me please?
I need it to check commit policy.

**Comment by Ricardoalso** [comment]
> I didn't found the version from wich this module is migrated, can you help me please? I need it to check commit policy.

Hey @sergiocorato, sorry I forgot to mention it is a backport of  V15 https://github.com/OCA/account-invoicing/tree/15.0/account_invoice_block_payment

**Comment by leemannd** [comment]
Hello @sergiocorato it is a backport from 15.0 -> https://github.com/OCA/account-invoicing/pull/1343

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
