### PR TITLE
Migration of stock_invoice_picking_incoterm

### PR DESCRIPTION
**Pull request by tafaRU**
This PR depends on https://github.com/OCA/account-invoicing/pull/62

### CODE REVIEW

**Comment by eLBati** [comment]
Thanks :+1:

**Comment by archetipo** [comment]
:+1:

**Comment by eLBati** [comment]
@tafaRU After renaming of `stock_picking_invoicing`, theoretically this module should now be called `stock_picking_invoicing_incoterm`? What do you think?

**Comment by tafaRU** [comment]
@eLBati I agree with the renaming of the module.

About the migration, I'm wondering if I can handle it simply updating https://github.com/OCA/OpenUpgrade/blob/8.0/openerp/addons/openupgrade_records/lib/apriori.py#L5 cc @pedrobaeza

**Comment by pedrobaeza** [comment]
For the v7 > v8 module migration, indeed you only need to add an entry in https://github.com/OCA/OpenUpgrade/blob/8.0/openerp/addons/openupgrade_records/lib/apriori.py#L5 as we have done with another renamed module.

**Comment by tafaRU** [comment]
@pedrobaeza, thanks! Please, one more thing: in case the module v8 is already installed, what's the best way to replace it by that one with the new name avoiding data loss?

Thank you in advance.

**Comment by pedrobaeza** [comment]
For that things, I use the shell module and start a shell:

``` shell
odoo.py --addons-path=<path> shell --config=<config_path> -d <dbname>
```

and execute this code:

``` python
from openupgradelib import openupgrade
openupgrade.update_module_names([('old_name', 'new_name')])
self.env.cr.commit()
```

And you have the module renamed.

**Comment by tafaRU** [comment]
@pedrobaeza, thanks a lot, you know a bit more than the devil:exclamation:

**Comment by tafaRU** [comment]
@eLBati @pedrobaeza I renamed the module as suggested at https://github.com/OCA/account-invoicing/pull/74#issuecomment-149563028

Now the module is ready to be merged, please review it.

Thank you in advance.

**Comment by gurneyalex** [comment]
:+1: (code review, no test)

**Comment by hurrinico** [comment]
:+1: (no test)

**Pull request merged**
