### PR TITLE
[MIG] account_invoice_alternate_payer: Migration to 12.0

### PR DESCRIPTION
**Pull request by etobella**
No major changes

### CODE REVIEW

**Comment by jarroyomorales** [comment]
There is this minor error on Travis flake8 `account_invoice_alternate_payer/models/account_invoice.py:8:1: E302 expected 2 blank lines, found 1`, can you check?

**Review by jarroyomorales — APPROVED** [review]

**Review by albariera — APPROVED** [review]
Code review LGTM :+1:

**Pull request merged**
