### PR TITLE
15.0 mig purchase stock picking return invoicing

### PR DESCRIPTION
**Pull request by 26hpredraglazarevic**

### CODE REVIEW

**Comment by 26hpredraglazarevic** [comment]
@pedrobaeza @MiquelRForgeFlow hi guys, since I'm first-time contributor could you please approve workflows, so checks can run. Also if you are available to do code review, that would be much appreciated. Thank you in advance.

**Comment by MiquelRForgeFlow** [comment]
Only @OCA/community-maintainers can approve workflows.

**Comment by 26hpredraglazarevic** [comment]
> Only @OCA/community-maintainers can approve workflows.

Thanks for the info Miguel. @OCA/community-maintainers since I'm first-time contributor could you please approve workflows, so checks can run. Also if you are available to do code review, that would be much appreciated. Thank you in advance.

**Comment by pedrobaeza** [comment]
Approved

**Comment by 26hpredraglazarevic** [comment]
@pedrobaeza can u help me with this pull request, who do I contact regarding Review. Three tests that are failing are:

1. pylint, but I can't fix it bcs its Missing `return` (`super` is used) in methods _get_invoiced and _compute_invoice and there is no returned value on method's super
2. unit tests on account_invoice_fiscal_position_update
3. unit tests on account_invoice_fiscal_position_update

**Comment by pedrobaeza** [comment]
For the super missing, just include the return, although no value is returned on super:
```python
def _get_invoiced(self):
    res = super()._get_invoiced()
    return res
```

The problem in the tests seems something outside this PR.

**Comment by MiquelRForgeFlow** [comment]
@26hpredraglazarevic please could you rebase?

**Comment by StefanRijnhart** [comment]
Already migrated to 15 in https://github.com/OCA/account-invoicing/pull/1169

**Pull request closed without merging**
