### PR TITLE
[14.0][FIX] stock_picking_invoicing: demo product compatible with MRP module.

### PR DESCRIPTION
**Pull request by antoniospneto**
Same as #1547 but with all occurrences.

@rvalyi

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
all right, I missed it in the review as well, my bad.

**Review by mileo — APPROVED** [review]

**Comment by rvalyi** [comment]
hum strange this last error in the account_invoice_pricelist module seems unrelated to the change:

```
2023-09-07 22:21:41,496 250 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_change_pricelist ... 
2023-09-07 22:21:41,787 250 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_fixed_pricelist_with_discount_secondary_currency ... 
2023-09-07 22:21:42,127 250 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_fixed_pricelist_without_discount_secondary_currency ... 
2023-09-07 22:21:42,461 250 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: ====================================================================== 
2023-09-07 22:21:42,462 250 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_fixed_pricelist_without_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 318, in test_account_invoice_fixed_pricelist_without_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 65.41)
AssertionError: 100.0 != 65.41 within 7 places
```

no suspect recent change in odoo/odoo account either. Is it some unconsistent test bug?

Trying to merge again as tests were passing in the PR in first place.


/ocabot merge patch

**Comment by antoniospneto** [comment]
@rvalyi 

As for inconsistencies in the `account_invoice_pricelist` module tests:

I ran the module tests in my local environment and it was failing as well, I suspected it might be something with the tests type `SavepointCase`, I changed it to `TransactionCase` and everything worked fine.

**Comment by rvalyi** [comment]
> @rvalyi
> 
> As for inconsistencies in the `account_invoice_pricelist` module tests:
> 
> I ran the module tests in my local environment and it was failing as well, I suspected it might be something with the tests type `SavepointCase`, I changed it to `TransactionCase` and everything worked fine.

great. However, I don't feel comfortable merging that one here on my own as I'm not mastering the repo as much as say l10n-brazil. Could you please open a different PR only for account_invoice_pricelist with a cross link and some explanations?

**Comment by antoniospneto** [comment]
> > @rvalyi
> > As for inconsistencies in the `account_invoice_pricelist` module tests:
> > I ran the module tests in my local environment and it was failing as well, I suspected it might be something with the tests type `SavepointCase`, I changed it to `TransactionCase` and everything worked fine.
> 
> great. However, I don't feel comfortable merging that one here on my own as I'm not mastering the repo as much as say l10n-brazil. Could you please open a different PR only for account_invoice_pricelist with a cross link and some explanations?

Done, I put the **account_invoice_pricelist** change in #1550

**Comment by antoniospneto** [comment]
@rvalyi

try the merge again?

**Pull request merged**
