### PR TITLE
[12][account_invoice_triple_discount] removed groups="base.group_no_one" from all lines

### PR DESCRIPTION
**Pull request by antonionardella**
Solves issue https://github.com/OCA/account-invoicing/issues/914

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Hi. 

I personally agree with that move. I think it makes no sense to have this group.

in the other way it is not consistent with odoo core account module.

See : https://github.com/OCA/account-invoicing/pull/370#discussion_r179718037
And : original code : https://github.com/odoo/odoo/blob/12.0/addons/account/views/account_invoice_view.xml#L55

@pedrobaeza : any PoV ? 

thanks.

**Comment by pedrobaeza** [comment]
If original `discount` field has such group, it's not homogeneous not to put it, but I think `sale` module adds another specific group for putting discounts (`sale.group_discount` or similar), that on v13, it's transferred to `account` module. `sale_triple_discount` can fill the gap as well.

**Comment by cscocca** [comment]
Yes @pedrobaeza it's right, the invoice discount attributes (for all views) changed here in sale module:

https://github.com/odoo/odoo/blob/12.0/addons/sale/views/sale_views.xml#L1053.

with new group `sale.group_discount_per_so_line`

So these attributes has to be changed also for `discount2 `and `discount3 `in `sale_triple_discount ` module.

If I'll have time I'll do a PR as soon as possible, but if anyone can be before it is appreciated

**Review by sergiocorato — APPROVED** [review]

**Comment by sergiocorato** [comment]
I think this fields should be visible if a specific group does not exist.
If sale is installed with this [PR](https://github.com/OCA/sale-workflow/pull/2297) `sale.group_discount_per_so_line` can be used.
@pedrobaeza @legalsylvain do you think this is acceptable?

**Comment by pedrobaeza** [comment]
The discount field not being in v12 in the account module makes the thing difficult, so you decide what you prefer.

**Comment by cscocca** [comment]
> I think this fields should be visible if a specific group does not exist. If sale is installed with this [PR](https://github.com/OCA/sale-workflow/pull/2297) `sale.group_discount_per_so_line` can be used. @pedrobaeza @legalsylvain do you think this is acceptable?

I think this is an acceptable solution but if sale is not installed then also original `discount` fields should haven't the group `base.group_no_one`, otherwise a standard user will see just `discount2 `and `discount3 ` without the main `discount`.

**Review by legalsylvain — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]

**Pull request closed without merging**
