### PR TITLE
[13.0][FIX] account_invoice_triple_discount: Calculate taxes correcly consi…

### PR DESCRIPTION
**Pull request by ao-landoo**
…dering all discounts

When creating an invoice from a sale order and using different discounts (sale_triple_discount, still not merged but working on PR https://github.com/OCA/sale-workflow/pull/2028) invoice's taxes were not calculated correctly.

Example:

> Created a sale order where the product unit price is 60. Added discount of 20% and discount 2 of 10%. Taxes are 15%.
> 60 * 0.8 * 0.1 * 0.15 = 6.48 -> This is OK
> 
> Created an invoice from the sale order. The taxes on the invoice are 7.2 instead of 6.48.
> This is because it's not considering discount2 and discount3 field values for the tax calculation
> 60 * 0.8 * 0.15 = 7.2 -> This is WRONG

After I saw it's working correctly on version 14.0, I looked at it's code and applied the differences. Now it's working fine.

@igallart Could you check it?

### CODE REVIEW

**Comment by ao-landoo** [comment]
@pedrobaeza Could you review this PR? The module is not working OK

**Comment by pedrobaeza** [comment]
Please include a regression test showcasing the problem that this patch is solving.

**Review by bi-landoo — APPROVED** [review]

**Comment by ao-landoo** [comment]
> Please include a regression test showcasing the problem that this patch is solving.

Added a test which is not passed without the changes in this commit. There also is a PR in sale-workflow repo (https://github.com/OCA/sale-workflow/pull/2028) which is not passing tests because of this bug.

**Review by adrienpeiffer — APPROVED** [review]
So it's seems the issue comme from the usage of invoice_line_ids instead of line_ids

**Pull request merged**
