### PR TITLE
[15.0][mig]-account_invoice_line_description

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — COMMENTED** [review]
According to the code the description in the product is the only thing that should appear in the invoice line as label. However it is appearing a compound name, for example, for a sales order of a product with name "Widget" and description for sales "this is a widget" the label in the invoice line is "Widget this is a widget". Is that intended?

**Comment by rafaelbn** [comment]
Please @JuanyDForgeflow could you answer @AaronHForgeFlow ?

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
@rafaelbn I checked and in v14 the behaviour is not the same, the product label is not in the description. So that must be fixed.

**Review by AaronHForgeFlow — APPROVED** [review]
Last commit makes this to behave same as v14. I will wait for others to review before merging it.

**Pull request merged**
