### PR TITLE
[11.0][MIG] sale_timesheet_invoice_description

### PR DESCRIPTION
**Pull request by astirpe**
Porting of module sale_timesheet_invoice_description to V11

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together "OCA Transbot..." commits

**Review by carlosdauden — APPROVED** [review]

**Comment by carlosdauden** [comment]
If you want you can add test to this condition:
https://github.com/OCA/account-invoicing/pull/334/files#diff-119f376e06c10d6cda5c5c5a3fa6cb5dR49
:wink:

**Comment by astirpe** [comment]
"OCA Transbot..." commits squashed

**Comment by carlosdauden** [comment]
:+1:

**Review by rvalyi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@astirpe can you please squash your last 3 commits before merging?

**Comment by astirpe** [comment]
@pedrobaeza Done

**Pull request merged**
