### PR TITLE
[13.0][FIX] account_global_discount: leave amount_currency empty

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT37931

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@omar7r your previous patch is causing problems when there's no currency involved. Can you please check for a solution along my colleague?

**Comment by omar7r** [comment]
Hi,

I think in 14.0 all lines have amount_currency but in 13.0 not, only when currency is set. You must check if currency is set and write amount_currency only in this case for 13.0.

**Comment by ernestotejeda** [comment]
ping @pedrobaeza @omar7r

**Review by omar7r — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@ernestotejeda please fw-port it to v14

**Comment by ernestotejeda** [comment]
> @ernestotejeda please fw-port it to v14

In v14 it is not necessary because as @omar7r said in v14 all lines have amount_currency

**Comment by pedrobaeza** [comment]
OK, right, I didn't remember.

**Comment by pedrobaeza** [comment]
But the sign part is correct?

https://github.com/OCA/account-invoicing/blob/044998afabdfc5816fb76e03050fa156f5c63a82/account_global_discount/models/account_move.py#L197

**Comment by ernestotejeda** [comment]
> But the sign part is correct?
> 
> https://github.com/OCA/account-invoicing/blob/044998afabdfc5816fb76e03050fa156f5c63a82/account_global_discount/models/account_move.py#L197

It's correct

**Comment by pedrobaeza** [comment]
Why then such difference here in 13 (no sign correction) against v14 (sign correction)?

**Comment by ernestotejeda** [comment]
What happens is that in that line of code in v14 there is not exactly a sign correction:
`"amount_currency": (disc_amount > 0.0 and disc_amount or 0.0) - (disc_amount < 0.0 and -disc_amount or 0.0),`
It is equivalent to:
`"amount_currency": disc_amount`

I said before, that it is correct because the code is not wrong even though it can be simplified, but there is really no sign correction.

the sign correction is done a few lines above:
https://github.com/OCA/account-invoicing/blob/044998afabdfc5816fb76e03050fa156f5c63a82/account_global_discount/models/account_move.py#L186

**Comment by pedrobaeza** [comment]
OK, it seems a bit awkward, so we can maybe propose the simplification for not being confusing.

**Pull request merged**
