### PR TITLE
[13.0][ADD] account_portal_invoice_search_by_lot: New module to allow search invoices by lots at portal

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT40857

This PR depends on:

- [x] https://github.com/OCA/account-invoicing/pull/1341 

please @sergio-teruel @chienandalu review this.

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
You can add your temporary dependencies with this technique https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference(s)-to-another-pull-request(s)

**Comment by CarlosRoca13** [comment]
@chienandalu change done!

**Review by chienandalu — APPROVED** [review]
Thanks! :+1:

**Review by pedrobaeza — APPROVED** [review]
Let's not let it die

/ocabot merge nobump

**Pull request merged**
