### PR TITLE
[15.0] [MIG] sale_line_refund_to_invoice_qty

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by MiquelRForgeFlow** [comment]
please rebase

**Comment by JasminSForgeFlow** [comment]
> please rebase

Done, thanks

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — COMMENTED** [review]
I created an SO:
Product: Storage BOX QTY=10.0

I delivered 10 units

Then I invoiced the whole order

Then I create a refund for 5 units and did not mark the quantities as to be reinvoiced

Then I created another refund for 1 unit, and marked the quantity to be reinvoiced

Then I was not able to reinvoice that unit. I was expecting to be able to create a new invoice for that extra unit. Am I wrong?

Here is the link to the SO in runboat: http://oca-account-invoicing-15-0-pr1190-3776507fd18c.runboat.odoo-community.org/web?debug=1#id=21&cids=1&menu_id=184&action=296&model=sale.order&view_type=form

**Comment by JasminSForgeFlow** [comment]
> I created an SO: Product: Storage BOX QTY=10.0
> 
> I delivered 10 units
> 
> Then I invoiced the whole order
> 
> Then I create a refund for 5 units and did not mark the quantities as to be reinvoiced
> 
> Then I created another refund for 1 unit, and marked the quantity to be reinvoiced
> 
> Then I was not able to reinvoice that unit. I was expecting to be able to create a new invoice for that extra unit. Am I wrong?
> 
> Here is the link to the SO in runboat: http://oca-account-invoicing-15-0-pr1190-3776507fd18c.runboat.odoo-community.org/web?debug=1#id=21&cids=1&menu_id=184&action=296&model=sale.order&view_type=form

Hi,

I think by mistake you untick the boolean on 2nd credit note also

image

Here I have performed the same kind of case, you can check it.
http://oca-account-invoicing-15-0-pr1190-3776507fd18c.runboat.odoo-community.org/web#id=28&cids=1&menu_id=184&action=296&model=sale.order&view_type=form

Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
You are right. Thanks!

**Pull request merged**
