### PR TITLE
[IMP] README of stock_picking_invoicing

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

I fast track as this doesn't break nothing

**Comment by tafaRU** [comment]
@pedrobaeza bug tracker has a broken link, I forgot the brackets. Do I have to open a new one PR?

**Comment by pedrobaeza** [comment]
Sorry, I didn't see it. Fixed on https://github.com/OCA/account-invoicing/commit/2f07ac94f1e13505c64b965a38e4d7e88ab07cde

**Comment by tafaRU** [comment]
:wink:

**Pull request merged**
