### PR TITLE
[16.0][MIG] product_form_account_move_line_link

### PR DESCRIPTION
**Pull request by lucuswolfius**
- Followup of #1336  (@JaumeBforgeFlow) to merge product_form_account_move_line_link into 16.0.
- Changed the type of the field "account_move_lines_count" to integer because its a counter.

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
Code and Testing LGTM

**Comment by CRogos** [comment]
@JaumeBforgeFlow could you have a look on these changes?

**Review by JaumeBforgeFlow — APPROVED** [review]

**Comment by CRogos** [comment]
@pedrobaeza could you merge this?

**Comment by pedrobaeza** [comment]
Merging blindly:

/ocabot merge nobump

**Pull request merged**
