### PR TITLE
[MIG] partner_invoicing_mode, partner_invoicing_mode_at_shipping, partner_invoicing_mode_monthly: Migration to 16.0

### PR DESCRIPTION
**Pull request by StefanRijnhart**
From unmerged PRs https://github.com/OCA/account-invoicing/pull/1243, https://github.com/OCA/account-invoicing/pull/1245 and https://github.com/OCA/account-invoicing/pull/1247, in which the modules were renamed from account_invoice_base_invoicing_mode, account_invoicing_mode_at_shipping and account_invoice_base_invoicing_mode_monthly respectively.

Standard migration, with increased coverage in all modules.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @StefanRijnhart , Should be different PR per module? I guess is inteded to make a single PR 😄 

/ocabot migration partner_invoicing_mode

/ocabot migration partner_invoicing_mode_at_shipping

/ocabot migration partner_invoicing_mode_monthly

**Comment by StefanRijnhart** [comment]
@rafaelbn I think having a single PR is better than three PRs that depend on each other, having to juggle temporary git locations as test requirements. As you can see, I grouped the migration commits per module for easy review.

**Review by TDu — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@pedrobaeza a last one here :) thanks again !

**Pull request merged**
