### PR TITLE
[12.0][FIX] purchase_stock_picking_return_invoicing create invoices after the first from purchase order

### PR DESCRIPTION
**Pull request by sergiocorato**
Solve #937

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But what happens without this patch if you click on Create? I think that's the intended behavior.

**Comment by sergiocorato** [comment]
It creates an invoice with 0 qty as in original function (the button is in grey).
The intended behavior here is as the comment says `"Change super action for displaying only normal invoices."` so to hide the `in_refund` invoices, or not?
I don't think it was intended to forbid to invoice partially delivered goods anyway.

**Comment by sergiocorato** [comment]
@OCA/accounting-maintainers review?

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by kittiu** [comment]
@sergiocorato thank you for the fix. 
Before the merge, can you add name of this module `purchase_stock_picking_return_invoicing` in the subject. I think it is important to ease future search. Thank you!

**Review by kittiu — APPROVED** [review]

**Pull request merged**
