### PR TITLE
[17.0][MIG] product_form_account_move_line_link: Migration to 17.0

### PR DESCRIPTION
**Pull request by MohamedOsman7**

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
code+usage LGTM

**Comment by CRogos** [comment]
@JaumeBforgeFlow would you be so kind and make the second review of this migration?

**Comment by MohamedOsman7** [comment]
@rousseldenis  could you please make a review?

**Review by antonioburic — APPROVED** [review]
LGTM as well, technical review

**Comment by CRogos** [comment]
@pedrobaeza could you merge?

**Pull request merged**
