### PR TITLE
[13.0][MIG] account_invoice_line_description: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT32095

Supersedes https://github.com/OCA/account-invoicing/pull/646 in order to speed up the migration of this module.

ping @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The test is failing due to the execution time. Merging as previous PR had enough reviews:

/ocabot merge nobump
/ocabot migration account_invoice_line_description

**Comment by pedrobaeza** [comment]
Oh, it seems the error is legit. Please check it and fix it.

**Comment by pedrobaeza** [comment]
In the `assertAlmostEqual", you have to explicitly put the third argument to `2` decimal places.

**Comment by ernestotejeda** [comment]
@pedrobaeza done

**Pull request merged**
