### PR TITLE
[ADD]account_invoice_tier_validation v11

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Invoice validation using tier definitions.

Supersedes #658

cc @ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
can you take care of my comments in the other PR and travis?

**Comment by AaronHForgeFlow** [comment]
@LoisRForgeFlow were already attended :) 

Fixed travis thing.

**Review by LoisRForgeFlow — APPROVED** [review]
Thank you!

**Review by kittiu — APPROVED** [review]
LGTM

**Pull request merged**
