### PR TITLE
[IMP][8.0] account_invoice_merge: Make the function to get draft invoices overridable, since some…

### PR DESCRIPTION
**Pull request by thomaspaulb**
… companies can have workflows where several states are still considered 'Draft'

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
LGTM thanks.

**Comment by thomaspaulb** [comment]
@legalsylvain Thanks, that was quick.

**Review by mourad-ehm — APPROVED** [review]
Thanks for this improvement

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Pull request merged**
