### PR TITLE
[14.0][IMP] sale_timesheet_invoice_description : new option to split SO line

### PR DESCRIPTION
**Pull request by clementmbr**
Based on #897 

Add an option on sale orders with time-sheets to **split the expected invoice line** as many invoice lines as the time-sheets number.

With the *Split Order lines by timesheets* option not selected, the result is still :
image

And with the *Split Order lines by timesheets* option selected :
image

- Take care of the potential difference between [invoice line's UoM](https://github.com/akretion/account-invoicing/blob/14.0-imp-sale-ts-inv-desc/sale_timesheet_invoice_description/models/sale.py#L81) and the time-sheets's one.
- The split lines total quantity is ensured to be exactly the same as the original invoice line by [adapting the last line quantity](https://github.com/akretion/account-invoicing/blob/14.0-imp-sale-ts-inv-desc/sale_timesheet_invoice_description/models/sale.py#L92)

### CODE REVIEW

**Comment by clementmbr** [comment]
Travis red because of #898

**Comment by rvalyi** [comment]
@clementmbr can you rebase please? the offending test has been fixed in #911

**Comment by MeetKD** [comment]
@clementmbr Any updates on this ?

**Review by victoralmau — COMMENTED** [review]
Code review OK.
Can you rebase please?

**Review by victoralmau — APPROVED** [review]
I have relaunched Travis and it is correct.
Code review OK.

**Comment by clementmbr** [comment]
@victoralmau @MeetKD @rvalyi sorry for the late reply but I just made the rebase !

**Comment by victoralmau** [comment]
> @victoralmau @MeetKD @rvalyi sorry for the late reply but I just made the rebase !

Can you put these commits together?
github-explicacion

**Review by CarlosRoca13 — APPROVED** [review]
As @victoralmau said, please squash the commits

**Comment by pedrobaeza** [comment]
Well, not being critical, and more that one is adding a feature, let's continue as is:

/ocabot merge nobump

**Comment by bosd** [comment]
Wow looks like an amazing improvement.
Way better readability of the invoice! 

Does it only change the graphical representation?
Or also change the ubl file contents when used in combination with that module?

**Comment by bosd** [comment]
Why is it taking oca-bot so long??

**Comment by bosd** [comment]
@pedrobaeza Can you check what is going wrong here?

**Pull request merged**
