### PR TITLE
[15.0][ADD] account_manual_currency

### PR DESCRIPTION
**Pull request by Saran440**
This module allows users to update the currency manually for invoices that are still in the draft stage.

Screenshot from 2023-06-15 11-00-51
Screenshot from 2023-06-15 11-00-58

when register payment, Journal Entry in payment will compute rate from moves
Screenshot from 2023-06-15 11-05-26

TODO:
- [x] test script

### CODE REVIEW

**Comment by tate11** [comment]
local test OK very good, thanks for your work

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by Saran440** [comment]
@HviorForgeFlow Thank you for reviewed. I add test script in this PR already.

@ps-tubtim Can you check, please?

**Comment by Saran440** [comment]
Change name `custom_rate` to `manual_currency_rate`
because `custom_rate` field already exists in module https://github.com/OCA/account-invoicing/tree/15.0/account_invoice_change_currency

**Review by cmcreamm — COMMENTED** [review]
In my opinion for functional user the word of "Unit" should change to "Currency" to reduce user confusing. Moreover, I suggest that the sentence will be more clarify if we change it to " Currency per (main currency)" for example, 0.5 currency per 1 THB and 25 THB per 1 currency. 
Could you please check if this suggestion has a chance to be possible? 

Screenshot from 2023-11-23 14-50-30

**Comment by Saran440** [comment]
@cmcreamm I change display to `Currency per 1 <main company currency>.` Can you re-check please?
Selection_001

**Review by cmcreamm — APPROVED** [review]
Functional test

**Pull request merged**
