### PR TITLE
[9.0][FIX][purchase_stock_picking_return_invoicing] minor fixes

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR updates the module a bit
- Update names.
- Update readme.
- Minor things.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@mreficent Can you attend to the error in Travis?

**Comment by mreficent** [comment]
Yes, the fix was done wrong 😵 

I will try to amend this.

**Comment by mreficent** [comment]
Fixed. It depends now from other PR.

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM! Good job

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You can't change the dependencies of an already merged module. You must create a compatible way to not depend on it or make a glue module

**Comment by MiquelRForgeFlow** [comment]
Ok, @pedrobaeza . I didn't know that. I will proceed now with the glue module approach.

**Comment by pedrobaeza** [comment]
But why can't you make both compatible without glue module?

**Comment by MiquelRForgeFlow** [comment]
Both modules have `qty_to_invoice = fields.Float(compute="_compute_qty_to_invoice"` where this compute method in both are different and both `qty_to_invoice` fields are put in the same view and same place

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
