### PR TITLE
[account_invoice_kanban]Don't load demo data on regular install

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
--- otherwise the module is uninstallable

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]

**Comment by elicoidal** [comment]
@sysadminmatmoz We were about to fix it :p 
Thanks!

**Comment by elicoidal** [comment]
@victormartinelicocorp

**Comment by elicoidal** [comment]
@seb-elico

**Review by victor-ditay — CHANGES_REQUESTED** [review]
Also might need fix this:
https://github.com/OCA/account-invoicing/blob/8.0/account_invoice_kanban/demo/account_invoice_demo.xml#L3

replace `<data>`
by `<data noupdate="1">`

**Comment by elicoidal** [comment]
Linked to #255

**Comment by elicoidal** [comment]
@sysadminmatmoz any news on this one?

**Comment by elicoidal** [comment]
I will fix the ```<data noupdate="1">``` in another PR

**Comment by elicoidal** [comment]
@pedrobaeza Can we merge this one?

**Pull request merged**
