### PR TITLE
[16.0][MIG] account_invoice_refund_link

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**
https://github.com/OCA/account-invoicing/issues/1250

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]

**Review by AntoniRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@OCA/community-maintainers 
Could you merge this PR?

**Comment by fcvalgar** [comment]
Hi @ljsalvatierra-factorlibre , can you rebase? Please

**Comment by ljsalvatierra-factorlibre** [comment]
> Hi @ljsalvatierra-factorlibre , can you rebase? Please

Yes, done!

**Comment by fcvalgar** [comment]
@ljsalvatierra-factorlibre

I get some errors when I try to access the credit notes from the "Refunds" tab.

https://www.loom.com/share/5e13258bd407463496bd49aaf1d5a379

Thank you.

Internal MT-1861 @Moduon

**Comment by ljsalvatierra-factorlibre** [comment]
> @ljsalvatierra-factorlibre
> 
> I get some errors when I try to access the credit notes from the "Refunds" tab.
> 
> https://www.loom.com/share/5e13258bd407463496bd49aaf1d5a379
> 
> Thank you.
> 
> Internal MT-1861 @moduon

Thank you for the review, i'll check it.

---
Edit:

Related to https://github.com/odoo/odoo/pull/106295

---
Edit:

I've added a `form` view inside the field and works fine.

imagen

imagen

**Comment by ljsalvatierra-factorlibre** [comment]
Hi, is it ok to merge? Can anyone please take a look?

**Review by fcvalgar — APPROVED** [review]
LGTM, 👍

Thank you @ljsalvatierra-factorlibre

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍 

/ocabot merge patch

**Comment by ljsalvatierra-factorlibre** [comment]
> LGTM, +1
> 
> Thank you @ljsalvatierra-factorlibre

Thank you for your time!

**Comment by ljsalvatierra-factorlibre** [comment]
> Thank you! +1
> 
> /ocabot merge patch

Thank you :)

**Pull request merged**
