### PR TITLE
[MIG] purchase_batch_invoicing: Migration to 10.0

### PR DESCRIPTION
**Pull request by Montxu**
cc @guadaltech

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please sign CLA and check CIs status

**Comment by pedrobaeza** [comment]
And you should preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by Montxu** [comment]
CLA signed and waiting.

**Comment by rafaelbn** [comment]
@Montxu please take take of https://github.com/OCA/account-invoicing/pull/384 in v9 that affects in v10

**Comment by rafaelbn** [comment]
@Montxu take care of this fix in v11 https://github.com/OCA/account-invoicing/pull/505

**Pull request closed without merging**
