### PR TITLE
[MIG] account_invoice_mode_monthly: Migration to 15.0

### PR DESCRIPTION
**Pull request by rven**
Depends on:
- [ ] https://github.com/OCA/account-invoicing/pull/1061

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]
code LG

**Comment by rven** [comment]
This module depends on https://github.com/OCA/account-invoicing/pull/1061.
test-requirements.txt file added in separated commit.

**Comment by TDu** [comment]
LG could you squash the administrative commits ?

**Comment by rafaelbn** [comment]
Closing as https://github.com/OCA/account-invoicing/pull/1061 was closed

**Pull request closed without merging**
