### PR TITLE
[FIX][WIP] Call new APIs

### PR DESCRIPTION
**Pull request by SimoRubi**
Fix to error report here: https://github.com/brain-tec/account-invoicing/commit/2a6f54799d83c33e0c57e5f7239d92df7ee9c6e0#r28802730

### CODE REVIEW

**Comment by BT-tbaechle** [comment]
Hi @SimoRubi 
thanks for your quick action!
Here comes the detailed explanation of the setup that led to this error:
1. (install account_invoice_rounding)
2. In Settings -> Accounting set the following:
selection_183
3. Create new customer invoice
4. Add new invoice line and set the unit price to 15.99 and tax 7.7%
5. Press the "(update)" button to calculate the tax
selection_194

This results in the following error:
selection_193

I was just testing on the runbot (http://3325496-380-181012.runbot1.odoo-community.org/web#view_type=form&model=account.invoice&action=272) and now this error is thrown immediately on creation of the invoice line:
selection_195

I hope this helps, if you need more info's let me know.

**Comment by SimoRubi** [comment]
@BT-tbaechle I have fixed the new error's method call. 
Apparently (and to me, unexpectedly), when you are inside a method that has been defined by the old APIs, methods must go along with old APIs declarations; I've tried the configuration that you described and it works, could you please check too in runbot?
Thanks

**Comment by BT-tbaechle** [comment]
@SimoRubi yes, now it's working just fine. Thanks a lot!

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can we merge this fix please?

**Comment by pedrobaeza** [comment]
You can review other PRs and ask in exchange that they review yours.

**Review by hurrinico — COMMENTED** [review]
👍

**Review by eLBati — APPROVED** [review]
LGTM

**Comment by HviorForgeFlow** [comment]
Trying it in local v8 I reach to this error going to Settings / Invoiving : 
```bash
Odoo Server Error
Traceback (most recent call last):
  File "/home/hveficent/Eficent/odoo/8.0/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/hveficent/Eficent/odoo/8.0/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/models.py", line 5989, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/models.py", line 5881, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/addons/addons-8.0/SimoRubi/***account-invoicing/account_invoice_rounding/res_config.py", line 61, in onchange_company_id
    company_id, context=context)*
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/addons/account/res_config.py", line 251, in onchange_company_id
    journal.type + '_sequence_next': journal.sequence_id.number_next_actual,
  File "/home/hveficent/Eficent/odoo/8.0/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/fields.py", line 928, in determine_value
    record._prefetch_field(self)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/models.py", line 3243, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/models.py", line 3367, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/addons/base/ir/ir_sequence.py", line 75, in _get_number_next_actual
    cr.execute(statement)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/home/hveficent/Eficent/odoo/8.0/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "increment_by" does not exist
LINE 1: SELECT last_value, increment_by, is_called FROM ir_sequence_...
                           ^
```

**Comment by eLBati** [comment]
@hveficent ```increment_by``` is not a field of ```account_invoice_rounding```. Is your local DB clean?

**Comment by HviorForgeFlow** [comment]
I'm not used to work on v8, so yes, I may have done some mistake but I created a clean db for prove it.
```
 File "/home/hveficent/Eficent/odoo/addons/addons-8.0/SimoRubi/***account-invoicing/account_invoice_rounding/res_config.py", line 61, in onchange_company_id
    company_id, context=context)*
```

**Comment by SimoRubi** [comment]
@hveficent coud you please tell me the full name of the table from the last line? I only see ir_sequence_...
The full query might be available in server's log

**Comment by SimoRubi** [comment]
@hveficent if the table is `ir_sequence_date_range`, that table comes from `base` module of v10 and it is not present in v8, so you may have crossed the versions somehow

**Comment by HviorForgeFlow** [comment]
Maybe v8 is not compatible with:
psql (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)

**Comment by SimoRubi** [comment]
I don't think postgres version is the problem in the exception you
reported.. Odoo complains about a field of an Odoo model that should be
there, but it's not in the DB.
I rebuilt the runbot for the PR, can you check if the issue is present
there too?

**Comment by eLBati** [comment]
@hveficent are you able to reproduce any error in a new clean DB?

**Comment by SimoRubi** [comment]
@BT-tbaechle since you already approved the PR, could you please review it too?
If you don't mind to check the code you can just say _Functional ok_, thanks

The more reviews we have, the more chance we have this gets merged soon

**Review by BT-tbaechle — APPROVED** [review]
Functional ok

**Pull request merged**
