### PR TITLE
[ADD] account_invoice_line_link_move_line

### PR DESCRIPTION
**Pull request by hbrunn**
Link invoice lines to move lines
================================

This module was written to have a direct link between move lines and invoice lines.

Usage
=====

This module is meant for developers who need to infer move lines from a given set of invoice lines or the other way around.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We already have stock_picking_invoice_link for this...

**Comment by hbrunn** [comment]
I'm talking about *account* move lines here

**Comment by hbrunn** [comment]
[lint failure](https://travis-ci.org/OCA/account-invoicing/jobs/391253777#L662) is unrelated

**Comment by pedrobaeza** [comment]
Ah, sorry, the name is a bit misleading, but it would be very large to be specified other way.

**Comment by thomaspaulb** [comment]
@pedrobaeza So you know of no module that does exactly this?

**Pull request closed without merging**
