### PR TITLE
[WIP] added new module account_invoice_exception

### PR DESCRIPTION
**Pull request by renatonlima**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please add a README.rst file according template https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

**Comment by renatonlima** [comment]
Hello @pedrobaeza 

Thank you for your feedback, I'm still working on this PR.

**Comment by pedrobaeza** [comment]
OK, WIP tag added.

**Comment by renatonlima** [comment]
@pedrobaeza  Do you know why I can't add labels?

**Comment by pedrobaeza** [comment]
It's a problem of GitHub. Only profiles with write permission on the repo can do it, which is not too much understandable.

**Pull request closed without merging**
