### PR TITLE
[13.0][IMP]  account_invoice_section_sale_order: add a hook to get ordered invoice lines

### PR DESCRIPTION
**Pull request by sebalix**

### CODE REVIEW

**Comment by sebalix** [comment]
Travis is failing due to a flappy test (not related to this PR) which seems to be there for at least 20 days:

- 4 days ago: https://travis-ci.com/github/OCA/account-invoicing/jobs/465431443
- 17 days ago: https://travis-ci.com/github/OCA/account-invoicing/jobs/478145502 + https://travis-ci.com/github/OCA/account-invoicing/jobs/478219784
- 20 days ago: https://travis-ci.com/github/OCA/account-invoicing/jobs/476657226

**Review by TDu — APPROVED** [review]

**Comment by TDu** [comment]
Rebased, lets see about those tests...

**Comment by TDu** [comment]
Also forward port in 14.0 https://github.com/OCA/account-invoicing/pull/1017

**Review by simahawk — APPROVED** [review]

**Pull request merged**
