### PR TITLE
[12.0][ADD] invoice_export

### PR DESCRIPTION
**Pull request by jans23**
This module allows to export multiple sales information to a spread sheet in XLS format.

### CODE REVIEW

**Comment by kittiu** [comment]
@jans23 thank you for your contribution.

For better readability, would you change the name of this PR to,
"[12.0][ADD] invoice_export" ?

**Comment by kittiu** [comment]
The travis still red, you can see what can be changed from here,
https://travis-ci.org/github/OCA/account-invoicing/jobs/666692312?utm_medium=notification&utm_source=github_status

**Comment by kittiu** [comment]
The name of this module, to conform with the rest, should be `account_invoice_export`

**Comment by kittiu** [comment]
> The name of this module, to conform with the rest, should be `account_invoice_export`

Oh i think I am not sure now. I still not quite understand the intention of this module. When I read from the README, I still unsure what this module try to do. Can you elaborate more? 
The good example of module structure is here,
https://github.com/OCA/mis-builder/tree/12.0/mis_builder

**Comment by kittiu** [comment]
And if you want to export excel (in a sense, I think it is link an excel report too), you can reuse couple of modules that will help create excel easier and cleaner,

* https://github.com/OCA/reporting-engine/tree/12.0/report_xlsx (with demo addon too)

Another option is to base on following, in case you want to make it a bit more configurable.

* https://github.com/OCA/server-tools/tree/12.0/excel_import_export (with demo addon too)

It may take time to understand the concept, but once you got it, your next report will be much easier.

Again, I am still not really sure the real propose of this addon, is it a kind of report? Coz if it is a report, it should go to https://github.com/OCA/account-invoice-reporting

Some sample, if you want to produce both PDF and Excel report, https://github.com/OCA/stock-logistics-reporting/tree/12.0/stock_card_report

**Comment by jans23** [comment]
Thanks. Let me check this. However, it may take a while for me to find the time...

**Comment by kittiu** [comment]
@jans23 no problem, let me know when it ready :+1:

**Pull request closed without merging**
