### PR TITLE
[16.0][MIG] account_invoice_refund_reason: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-anieto**
#1494 is stale, so I take it

### CODE REVIEW

**Review by BT-dherreros — APPROVED** [review]
LGTM

**Review by BT-nfrancisco — APPROVED** [review]
Looks good

**Comment by BT-anieto** [comment]
@OCA/accounting-maintainers Good for merge?

**Comment by BT-anieto** [comment]
@max3903 Could we merge it?

**Comment by BT-anieto** [comment]
Good morning @pedrobaeza. Sorry to bother you, but neither the accounting maintainers nor the module maintainers answer me.

Could we merge this PR?

**Comment by pedrobaeza** [comment]
You should respect commit attribution from #1494 instead of overwriting everything, and include him in CONTRIBUTORS.rst, the same you have made with you.

**Comment by BT-anieto** [comment]
Not sure about having done everything right. I added him as author of the last two commits, although I included myself in CONTRIBUTORS.rst in the last one. Is it proper?

**Comment by BT-anieto** [comment]
Not sure about having done everything right. I added him as author of the last two commits, although I included myself in CONTRIBUTORS.rst in the last one. Is it proper?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_invoice_refund_reason
/ocabot merge nobump

**Pull request merged**
