### PR TITLE
[MIG][10.0]product_supplierinfo_for_customer_invoice

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
supersedes #319

### CODE REVIEW

**Comment by mreficent** [comment]
Please, fix the PR

**Comment by MiquelRForgeFlow** [comment]
@aheficent Please, fix the PR

**Comment by AaronHForgeFlow** [comment]
rebased

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM :+1:

**Pull request merged**
