### PR TITLE
[15.0][MIG] account_invoice_line_sequence

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by bosd** [comment]
Thanks for this!! 
Kindly check your last commit. It only includes changes in documentation.

Functional test failed.. Sequence # stays 0.

**Comment by hbrunn** [comment]
did you commit your line? The number is only generated when there's actually a line to save

**Comment by bosd** [comment]
Picture says more then words :)
Here's some feedback on the testing..


[1301cadf-6ae5-4397-8423-c0f3c04309db.webm](https://github.com/OCA/account-invoicing/assets/11499387/2f1f7d31-80cb-4ba3-b82a-71ba3596f73d)

Also tried an alternative method.
Enter 1 line.. While entering data sequence number shows as 1.
click save.
Sequence number changes to 0.
Expected behaviour: Sequence # stays 0
[screenity (11).webm](https://github.com/OCA/account-invoicing/assets/11499387/817c0e06-3f71-4fb9-91dd-0c689036c955)

Adding a second line after the save.
The first line sequence changes to 1.
Second line is number 2.
Expected behaviour: Having consistency number e.g. always start numbers with either 0 or 1.
[screenity (12).webm](https://github.com/OCA/account-invoicing/assets/11499387/bbe06b90-adab-41a5-9620-f948bcffbd37)

**Comment by AaronHForgeFlow** [comment]
This needs to be included: https://github.com/OCA/account-invoicing/pull/1431

**Comment by hbrunn** [comment]
@AaronHForgeFlow thanks for the headsup, but I rewrote this part (we don't touch the sequence field now, which causes the problems in v14) slightly, so I doubt we need this here. Actually, I think it would be more elegant to backport what I do here instead of having to activate the module after installation, which I always find a bit weird.

@bosd thanks for the elaboration, could you retest?

**Review by bosd — APPROVED** [review]
Functional test LGTM!

**Comment by AaronHForgeFlow** [comment]
@hbrunn sorry, I did not see the refactor on that part. I agree this is more consistent solution

**Comment by bosd** [comment]
@AaronHForgeFlow can you please review?

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review :green_circle:

**Pull request merged**
