### PR TITLE
[13.0][MIG] sale_order_invoicing_queued: Change account.invoice model to account.move for stored queue jobs

### PR DESCRIPTION
**Pull request by sergio-teruel**
Script Openupgrade
cc @Tecnativa
ping @carlosdauden @pedrobaeza

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
Unrelated travis error

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You need to change the referred ID from the account invoice to the corresponding account move.

**Comment by sergio-teruel** [comment]
oh!!!! yes... 🤭

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Closing as no longer needed.

**Pull request closed without merging**
