### PR TITLE
[12.0] [MIG] account_invoice_triple_discount

### PR DESCRIPTION
**Pull request by Nikul-Chaudhary**
Account Invoice Triple Discount
===============================

This module allows to have three successive discounts on each invoice line.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
:+1: 
Thanks for porting this module.
code review of the last commit (4f6e7412ba90e00ca044779da7ec1e1f87de2ef6) / no test.

**Comment by legalsylvain** [comment]
CC original authors : @chienandalu, @pedrobaeza

**Comment by Nikul-Chaudhary** [comment]
> +1
> Thanks for porting this module.
> code review of the last commit ([4f6e741](https://github.com/OCA/account-invoicing/commit/4f6e7412ba90e00ca044779da7ec1e1f87de2ef6)) / no test.

@legalsylvain Thanks too You

**Review by StefanRijnhart — APPROVED** [review]
Checked if API overrides were still valid.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
