### PR TITLE
8.0 Port module payment_term_rounding to v8

### PR DESCRIPTION
**Pull request by alexis-via**
Port module payment_term_rounding to v8
Rename module to account_payment_term_extension.
Add support for months and weeks in account.payment.term.line, see README.rst and screenshot.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We should add here the functionality of paydays module (https://github.com/OCA/account-payment/pull/10), don't you think?

**Comment by brother-bernard** [comment]
:+1: OK. I have tested some values, for instance : invoice date = 01/31/15 with payment term 30 days end of month. The term calculated is correct : 02/28/15. Without this module, the term was incorrect : 03/31/15.

**Comment by yvaucher** [comment]
Needs a rebase

**Comment by alexis-via** [comment]
I made the rebase. I hope it's fine now.

**Comment by yvaucher** [comment]
@alexis-via missing a `git push -f` ?

**Comment by alexis-via** [comment]
Here is what I did exactly: 

```
% git push -f akretion 8.0-port-payment_term_rounding-and-rename
Everything up-to-date
```

**Comment by yvaucher** [comment]
@alexis-via but commits have not been updated so you missed the first part:

```
git rebase -i origin/8.0
do for each conflict:
    hack to resolve conflict then git add
    git rebase --continue

git push -f
```

**Comment by alexis-via** [comment]
OK, i made a proper rebase this time, with the help of Benoit

**Comment by bguillot** [comment]
:+1: Looks good

**Comment by sebastienbeau** [comment]
:+1: ok for me too

**Pull request merged**
