### PR TITLE
8.0 add pdf invoice import

### PR DESCRIPTION
**Pull request by olviz**

### CODE REVIEW

**Comment by eLBati** [comment]
@olviz I think target of this PR should be 8.0

**Comment by ivantodorovich** [comment]
Can't test it right now, but if it does what I think it does.. I'll travel to wherever you live and buy you a beer :beer:

**Comment by alexis-via** [comment]
@ivantodorovich I live in France... and I'm glad that you like my work :)
@olviz I don't know why you created this PR, but the official PR for Odoo v8 is this one: https://github.com/OCA/account-invoicing/pull/122
I started to work on Odoo v9, but it's not ready yet and I prefer to finish the work on Odoo v8 before starting to port it to v9.
The first part was announced on Akretion's blog: http://www.akretion.com/blog/akretions-christmas-present-for-the-odoo-community
The second part (full ZUGFeRD implementation) will be announced very soon.

**Comment by alexis-via** [comment]
@olviz could you close this PR to avoid confusion, unless you plan to work on something different than my PR #122

**Comment by pedrobaeza** [comment]
I close the PR because is indeed wrong.

**Pull request closed without merging**
