### PR TITLE
FIX acc_invoice_pricelist: tax include in multicompany

### PR DESCRIPTION
**Pull request by bealdav**
@pedrobaeza 
Thanks

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@bealdav please check Travis error

**Comment by bealdav** [comment]
FAIL: test_change_invoice_currency (odoo.addons.account_invoice_change_currency.tests.test_account_invoice_change_currency.TestAccountInvoiceChangeCurrency)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/account-invoicing/account_invoice_change_currency/tests/test_account_invoice_change_currency.py", line 97, in test_change_invoice_currency
`     'Total amount of invoice does not equal to expected value!!!')
` AssertionError: 2388.14 != 2388.1400000000003 : Total amount of invoice does not equal to expected value!!!
FAILED
Module account_invoice_change_currency: 1 failures, 0 errors

**Comment by pedrobaeza** [comment]
It seems to not be happening on main branch, so might be due to this change. I have relaunched main branch tests in https://travis-ci.org/OCA/account-invoicing/builds/534997436 for being sure. Please check and report when finished.

**Comment by bealdav** [comment]
yes

**Comment by bealdav** [comment]
same behavior in main branch
odoo.addons.account_invoice_change_currency.tests.test_account_invoice_change_currency: ` AssertionError: 2388.14 != 2388.1400000000003 : Total amount of invoice does not equal to expected value!!!

**Comment by pedrobaeza** [comment]
OK, let's merge this and put an issue about the other module.

**Pull request merged**
