### PR TITLE
[12.0][FIX] remove from invoice lines with no quantity

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by bodedra — COMMENTED** [review]
Instead of unlink, how about not include it during prepare invoice line?

**Comment by sergiocorato** [comment]
> Instead of unlink, how about not include it during prepare invoice line?

I didn't found the method which prepare invoice lines, can you link it?

**Comment by bodedra** [comment]
How about following?

In purchase module, purchase_order_change() method

Ref: https://github.com/odoo/odoo/blob/12.0/addons/purchase/models/account_invoice.py#L91

**Comment by pedrobaeza** [comment]
This must be opt-in, as people may want to have them. It can be an option at the wizard level.

**Comment by sergiocorato** [comment]
> This must be opt-in, as people may want to have them. It can be an option at the wizard level.

Done, thanks

**Review by pedrobaeza — APPROVED** [review]
Thanks for the feature.

**Review by bodedra — APPROVED** [review]
LG :+1:

**Comment by pedrobaeza** [comment]
/ocabot merge minor

Does this apply to v13 as well?

**Pull request merged**
