### PR TITLE
[13.0][MIG] account_menu_invoice_refund

### PR DESCRIPTION
**Pull request by hildickethan**
Standard migration to 13.0

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Review by bodedra — COMMENTED** [review]
Functional reviewed. Menus are work fine.

But I can see Odoo standard "Credit Notes" and "Refund" menu.

So IMO, we do not need this module in v13.0.

Any thoughts?

**Comment by bodedra** [comment]
Ignore previous comment, I see, this module will bring both invoices and credit/refund.

**Review by Abranes — APPROVED** [review]
LGTM

**Pull request merged**
