### PR TITLE
[FIX] write method not migrated correctly from v8 to v10

### PR DESCRIPTION
**Pull request by SimoRubi**
Correcting a mistake from v8 -> v10 migration

### CODE REVIEW

**Review by tafaRU — APPROVED** [review]

**Review by hurrinico — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by eLBati** [comment]
oops

**Comment by eLBati** [comment]
next time :sweat_smile:

**Comment by pedrobaeza** [comment]
hehe, well, I change it in direct commit. It's for triggering the wheel reconstruction.

**Pull request merged**
