### PR TITLE
[15.0][MIG] account_invoice_analytic_search

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional tests LG. CI errors seem unrelated.

**Comment by JuanyDForgeflow** [comment]
Functional Review LGTM

**Comment by AaronHForgeFlow** [comment]
Can you rebase @JasminSForgeFlow ?

**Comment by JasminSForgeFlow** [comment]
> Can you rebase @JasminSForgeFlow ?

Done, Thanks

**Comment by AaronHForgeFlow** [comment]
> > Can you rebase @JasminSForgeFlow ?
> 
> Done, Thanks

Thanks. It seems the problem with the other module is still not fixed in the base branch

**Comment by AaronHForgeFlow** [comment]
@JasminSForgeFlow  CI will be fixed here: https://github.com/OCA/account-invoicing/pull/1470

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
