### PR TITLE
[14.0][MIG] account_invoice_check_total: Migration to 14.0

### PR DESCRIPTION
**Pull request by xavierjimenez**
Migration to 14.0 of the module account_invoice_check_total

### CODE REVIEW

**Comment by xavierjimenez** [comment]
Hi @ThomasBinsfeld @ernestotejeda could you do a review if you can please?

Thanks!

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by ernestotejeda — APPROVED** [review]

**Review by anasuarez1 — APPROVED** [review]
Functional Review OK!

**Comment by xavierjimenez** [comment]
@OCA/accounting-maintainers can someone please check this PR? I think it's ready to merge. Thanks!

**Pull request merged**
