### PR TITLE
[14.0][FIX] account_invoice_fiscal_position_update: fix tests

### PR DESCRIPTION
**Pull request by willytal**
cc @Tecnativa TT32113

@chienandalu @pedrobaeza 

Please review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Add here #1142

**Comment by chienandalu** [comment]
You can fix the other modules that are failing on travis as well in separate commits

**Comment by chienandalu** [comment]
Don't set version number in the commits.

**Review by chienandalu — APPROVED** [review]
Thanks @willytal :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by moylop260** [comment]
Branch 15.0 unittests has issues the same module

Could you check it, please?

https://github.com/OCA/account-invoicing/issues/1164

**Pull request merged**
