### PR TITLE
[14.0][ADD] account_invoice_refund_reason_unlink_sale: Add to 14.0

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Odoo by default creates a link between the SO's and the refunds, with this module you're allowed to select whether you want this link or not

### CODE REVIEW

**Comment by ChrisOForgeFlow** [comment]
I checked functional and seem this not working well, can you check if not because you have another module in this repo

image

image

**Comment by ChrisOForgeFlow** [comment]
image

**Comment by JuanyDForgeflow** [comment]
@ChrisOForgeFlow It's working now

**Comment by ChrisOForgeFlow** [comment]
@JuanyDForgeflow  Can you check please if this module has same functionality?

https://github.com/OCA/account-invoicing/tree/14.0/sale_line_refund_to_invoice_qty

**Comment by AaronHForgeFlow** [comment]
The reason for the unlink is to prevent reduction of the qty invoiced?

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow That's the main reason

**Comment by JuanyDForgeflow** [comment]
> @JuanyDForgeflow Can you check please if this module has same functionality?
> 
> https://github.com/OCA/account-invoicing/tree/14.0/sale_line_refund_to_invoice_qty

I tested that module and I think it works for what we're looking for, @AaronHForgeFlow @ChrisOForgeFlow Should I close this one?

**Pull request closed without merging**
