### PR TITLE
[13.0][MIG] account_invoice_tax_note

### PR DESCRIPTION
**Pull request by kongrattapong**

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM 👍

**Review by jarroyomorales — APPROVED** [review]
Functional review and it's working as expected!

**Review by anasuarez1 — APPROVED** [review]
Functional review LGTM!

Since everything looks ok can we get this merged?

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/accounting-maintainers can this be merged?

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

@kongrattapong  sorry for being picky, but can you please amend the commit message? something like `[13.0][MIG] account_invoice_tax_note` would be fine

**Comment by albariera** [comment]
Superseeding as the author is not answering

**Comment by AaronHForgeFlow** [comment]
Superseded by https://github.com/OCA/account-invoicing/pull/930 Thanks for collaborate!

**Pull request closed without merging**
