### PR TITLE
14.0 mig account_invoice_tree_currency

### PR DESCRIPTION
**Pull request by fredzamoabg**
account_invoice_tree_currency module migration from 13.0

### CODE REVIEW

**Review by SimoneVagile — APPROVED** [review]
LGTM

**Comment by stevech091** [comment]
functional test ok.

**Review by kittiu — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
