### PR TITLE
[14.0] stock_picking_invoicing migration

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by kittiu** [comment]
@mileo are you still working on this?

**Comment by mileo** [comment]
> @mileo are you still working on this?

Hi @kittiu 

This week it can't work on it, but I will go back on it and #786 next week.

Do you need this module too?

**Comment by kittiu** [comment]
@mileo not at the moment. Just browse around doing some review. Please let me know when this is ready then. :)

**Comment by rvalyi** [comment]
Hello @mileo, thank you for the PR. Could you look at the the Travis and Runbot issues?
Also, I see the PR you took from the v13 migration had the CI broken as well. It was later abandonned but another person, @Rad0van made a new PR https://github.com/OCA/account-invoicing/pull/836 fixinfg the CI but commented something about the demo data, may be you could use his work and help with the demo data.

Finally in v12 we made a few extra fixes to get things working well in Brazil, may be you could cherry-pick the latest commits from @mbcosta :
https://github.com/OCA/account-invoicing/commits/12.0/stock_picking_invoicing

**Comment by Rad0van** [comment]
@mileo , @rvalyi I tried using the demo data from this PR but it fails the same as mine. Something like this:
```
addons/stock/models/stock_picking.py", line 595, in write
    raise UserError(_("Changing the operation type of this record is forbidden at this point."))
odoo.exceptions.UserError: ('Changing the operation type of this record is forbidden at this point.', '')

```
I have been trying to wrap my head around it to no avail... Does this work in 14.0?

**Comment by renatonlima** [comment]
@mileo,

Can you do rebase or cherry-pick latest commits in 12.0? There are some import fixes made by me and @mbcosta

@Rad0van,

I suggest you start testing after the travis is green ;)

**Comment by Zar21** [comment]
Hello, this pull PR is functional?

**Comment by Zar21** [comment]
@mileo,
I found a permission error with the stock.invoice.onshipping model due to in 14.0 version you must give permissions to all models including Transient. Will you solve it or this pr is abandoned?

**Comment by Zar21** [comment]
superseeded by https://github.com/OCA/account-invoicing/pull/1010

**Comment by rvalyi** [comment]
Superseded by #1014

**Pull request closed without merging**
