### PR TITLE
[11.0][FIX] account_global_discount: link line taxes to discount move line

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT24526

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by chienandalu** [comment]
please review @carlosdauden

**Review by carlosdauden — CHANGES_REQUESTED** [review]
It doesn't work as expected.

Selección_053

Selección_054

**Comment by pedrobaeza** [comment]
@carlosdauden please check my latest changes

**Review by chienandalu — COMMENTED** [review]
Tested @pedrobaeza changes :+1: 
@carlosdauden Please re-review

**Comment by SoniaViciana** [comment]
This PR isn't ok, at the accounting entry of discount, I miss the detail of 349 model on intra-community invoices:

image

Please, could you check it @chienandalu ?

Thanks a lot!

**Comment by pedrobaeza** [comment]
@SoniaViciana this is because you need a glue module between both. It's the problem of having this anti-nature way of giving discounts. We have been forced to do it in a customer, but we DON'T RECOMMEND these global discounts as it needs a lot of patching in successive things, like this 349 side effect.

**Comment by pedrobaeza** [comment]
@SoniaViciana @chienandalu I think I have found  method for not needing that glue modules in most cases. Can you please check with latest push about the 349?

**Comment by pedrobaeza** [comment]
Well, not sure if we need to change 349 method:

https://github.com/OCA/l10n-spain/blob/245ff2527aabd2670c99325a056651fef5cfce3f/l10n_es_aeat_mod349/models/account_invoice.py#L22

and doing this in invoice_line_move_line_get instead. And even in that case, it would depend on the call chain...

I'm giving up now on this, as our customer only uses global discounts for national operations (and in very few cases).

**Comment by chienandalu** [comment]
Yes, looks like a glue module is still needed for that case: https://github.com/OCA/l10n-spain/blob/245ff2527aabd2670c99325a056651fef5cfce3f/l10n_es_aeat_mod349/models/account_invoice.py#L35-L36

Anyway, let's move forward

**Pull request merged**
