### PR TITLE
[8.0] add date invoice on merge wizard

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
This PR add a field on wizard to set date_invoice on merged invoices.

### CODE REVIEW

**Comment by lmignon** [comment]
@gurneyalex I confirm that @Cedric-Pigeon is my colleague and part of Acsone  and therefore have an Enterprise CLA signed.

**Comment by lmignon** [comment]
@gurneyalex I confirm that @Cedric-Pigeon is my colleague and part of Acsone  and therefore have an Enterprise CLA signed.

**Comment by gurneyalex** [comment]
@lmignon @Cedric-Pigeon ok, I updated the OCA database, next PR should be clabot clean.

**Comment by Cedric-Pigeon** [comment]
@gurneyalex Thanks

**Comment by adrienpeiffer** [comment]
:+1: (Code review)

**Comment by anthony-muschang** [comment]
:+1:  Code review

**Pull request merged**
