### PR TITLE
[16.0][FIX] account_invoice_force_number: Assign forced number on mass vali…

### PR DESCRIPTION
**Pull request by aritzolea**
…dation

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Review by SoniaViciana — APPROVED** [review]
Functional review LGTM

**Comment by aritzolea** [comment]
@tafaRU could you check this please? Thanks

**Comment by aritzolea** [comment]
@tafaRU @AaronHForgeFlow can you review this please?

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM! next time please do not change the version in the manifest, ocabot will be doing that.

**Pull request merged**
