### PR TITLE
[15.0][MIG] stock_picking_return_refund_option: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36568

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@sergio-teruel please review

**Comment by cesar-tecnativa** [comment]
@pedrobaeza please review

**Review by sergio-teruel — APPROVED** [review]
Functional and code review

**Review by pedrobaeza — APPROVED** [review]
Code review + tested on runbot

**Pull request merged**
