### PR TITLE
[14.0][MIG] account_invoice_line_description: Migration to 14.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT32095

Supersedes https://github.com/OCA/account-invoicing/pull/846 in order to speed up the migration of this module.

ping @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Code review and functionally tested on runboat

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Pull request merged**
