### PR TITLE
12.0 mig account invoice pricelist sale

### PR DESCRIPTION
**Pull request by legalsylvain**
Hi all,

Porting ``account_invoice_pricelist_sale`` glue module from 10.0 to 12.0.

Trivial module that overload _prepare_invoice function (``sale.order``) to set sale order pricelist on generated invoices.

Commit to review : https://github.com/OCA/account-invoicing/commit/488aecef2a427d05bebd4ad64b1256a09b6a3174

Done : 
- oca convention (readme folder)
- removing duplicating icon
- add test

CC : original author and reviewers of ``account_invoice_pricelist`` and ``account_invoice_pricelist_sale`` module : @NL66278, @StefanRijnhart, @Nikul-Chaudhary, @pedrobaeza, @rvalyi.

Thanks.

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1:  LGTM, and nice the addition of the test.

I have one small question and request for change, but non blocking, so approve.

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Review by StefanRijnhart — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks for your reviews.

**Pull request merged**
