### PR TITLE
[SEC] account_invoice_validation_workflow: fix unsafe eval

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
I did not change the version to 9.0 on purpose as the module is still unported to v9

**Comment by legalsylvain** [comment]
:+1: Thanks.

Is there any reason to change the version of a non installable module ? or it's just a good practice ? 

kind regards.

**Comment by pedrobaeza** [comment]
Should we this time leave this without merging and import the commits from 8.0?

**Comment by antespi** [comment]
:+1:

**Comment by gurneyalex** [comment]
@legalsylvain Its a side effect of cherry picking.

I have no strict opinion on this, and leave the decision to the PSC. My goal in submitting a PR is avoiding false positives on unported addons when looking for suspicious code across the OCA repositories (and making sure this bug does not pop back if the developer porting to v9 misses this, since the problem likely won't show up in the diff)

**Comment by max3903** [comment]
:+1:

**Pull request merged**
