### PR TITLE
[16.0][MIG] account receipt send: Migration to 16.0

### PR DESCRIPTION
**Pull request by anddago78**
Adds a button to Send and Print Receipts
Adds a new mail template for receipts

MT-3066 @moduon @Shide @rafaelbn @yajo @loida-vm @ArantxaSudon  please reviews :)

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
LGTM, thank you @anddago78 

image

**Review by yajo — APPROVED** [review]
Code review.

**Review by rafaelbn — APPROVED** [review]
👍🏼 

/ocabot migration patch

**Pull request merged**
