### PR TITLE
7.0 account_invoice_purchase_origin

### PR DESCRIPTION
**Pull request by mcassuto**
Migration from MP lp:~savoirfairelinux-openerp/account-invoicing/account_invoice_line_merge
- PEP8 corrections
- code review
- functional review
- code fixing

### CODE REVIEW

**Comment by kryskool** [comment]
Hi

As @eLBati said, you must call super() and complete the missing keys (or replace value) 

Because you broke others modules that use these functions

:-1:

Reagrds,

**Comment by pedrobaeza** [comment]
@kryskool You can put needs fixing label until @mcassuto fix the issue.

Regards.

**Comment by kryskool** [comment]
@pedrobaeza yes you're right, thanks for the tips

Regards,

**Comment by mcassuto** [comment]
@eLBati , @kryskool : sorry for the delay. Here is the modification as asked.

**Comment by mcassuto** [comment]
@eLBati , @kryskool : need advice :
1/ why travis highlight this error, it is a non sens:
./account_invoice_sale_origin/**init**.py:22:1: F401 'sale' imported but unused

2/ There is errors on other modules YAML files; what should I do with that

It starts to be discouraging to publish....

**Comment by pedrobaeza** [comment]
Sorry, it was a little problem with quality tools. It has been fixed, but there's still a litlle PEP8 problem with another module. Please ignore it.

**Comment by mcassuto** [comment]
@pedrobaeza : thanks a lot !! Blank line fixed ! waiting for my dear Travis ;-)

**Comment by kryskool** [comment]
Hi @mcassuto 

Thanks for you contribution, i just review the code and it's ok for me :+1:

Regards,

**Comment by pedrobaeza** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
Hello,

I test the module and it seems work as expected :+1:

**Comment by mcassuto** [comment]
@laetitia-gangloff : thanks !

**Comment by pedrobaeza** [comment]
I proceed with the merge.

**Pull request merged**
