### PR TITLE
Fix bug #222 bad use of read in new API

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It should work also with that notation, isn't it?

**Comment by alexis-via** [comment]
Certainly... (by the way, in v9, we use a browse instead of a read).

**Comment by pedrobaeza** [comment]
Travis complains...

**Comment by alexis-via** [comment]
When we merge 2 invoices, why do we bother to re-generate their invoice lines ? Why not just re-attach the existing invoice lines to the new account.invoice ? It would simplify the code quite a lot...

**Comment by alexis-via** [comment]
@pedrobaeza Travis is red on OCA/account-invoicing ; so it's not a regression of this PR.

**Comment by alexis-via** [comment]
I say that for v8 of course (it's green on OCA/account-invoicing/10.0).

**Comment by alexis-via** [comment]
OK, I understand this module also merges invoice lines, that's why they are re-generated... but I complexifies at lot the module :-(

**Comment by pedrobaeza** [comment]
Please solve conflicts

**Pull request closed without merging**
