### PR TITLE
[12.0][FIX] account_invoice_transmit_method

### PR DESCRIPTION
**Pull request by brian10048**

### CODE REVIEW

**Review by jguenat — APPROVED** [review]
LGTM

**Review by jguenat — CHANGES_REQUESTED** [review]
Well in fact you should transfer existing values through a migration script, see #848

**Comment by jguenat** [comment]
I did some work on it, it seems to work. you can find it there 
https://github.com/jguenat/account-invoicing/commit/7f9b656690399be2a0caa26003354a1dbad761ff

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
>I did some work on it, it seems to work. you can find it there
jguenat@7f9b656

Looks great!

**Review by ivantodorovich — APPROVED** [review]

**Pull request closed without merging**
