### PR TITLE
[16.0][MIG] account_invoice_show_currency_rate: Migration to 16.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
#1250

**Review by RodrigoBM — APPROVED** [review]

**Review by Gelo-fl — APPROVED** [review]
LGTM https://www.awesomescreenshot.com/video/19763045?key=586365e80754c88cfa8fe661a43ef574

**Review by rafaelbn — APPROVED** [review]
Thanks for this migration! 👍🏼 

@Gelo-fl nice awesome review! 😄

**Pull request merged**
