### PR TITLE
[ADD] support analytic plans

### PR DESCRIPTION
**Pull request by hbrunn**
The small refactoring should make it simpler to add more things like that or to change the matching logic completely in an inheriting module

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can already inherit the list and add elements. _account_invoice_merge_ module already do it in https://github.com/OCA/account-invoicing/blob/8.0/account_invoice_merge_payment/models/account_invoice.py#L30, and you break it with you change.

**Comment by hbrunn** [comment]
@pedrobaeza doing it this way is a very bad idea. As soon as account_invoice_merge_payment has a static folder, this key is added when the addon is in the addons path without it being installed. At least, this should be protected by means of `_register_hook` or such, and we should encourage using extension mechanisms that respect the difference between "module is loaded python wise" and "module is installed in the database"

**Comment by hbrunn** [comment]
@pedrobaeza I you agree, I'll include fixing this module in the PR

**Comment by pedrobaeza** [comment]
OK, then please change the extension mechanism to the function then.

**Comment by hbrunn** [comment]
@pedrobaeza done

**Comment by legalsylvain** [comment]
:+1: Thanks.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
@adrienpeiffer can you have a look at this one?

**Comment by adrienpeiffer** [comment]
LGTM (Code review and functionnal test). I'll update #92 according changes in this one. :+1:

**Comment by sbidoul** [comment]
:+1:

**Pull request merged**
