### PR TITLE
[15.0][MIG] account_invoice_refund_line_selection

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by RodrigoBM** [comment]
add this commit 7844d10908276fd9d89733c49bc1a46a8c39e9ac

**Comment by RodrigoBM** [comment]
- [ ] add this commit 7844d10908276fd9d89733c49bc1a46a8c39e9ac

**Comment by RodrigoBM** [comment]
> add this commit [7844d10](https://github.com/OCA/account-invoicing/commit/7844d10908276fd9d89733c49bc1a46a8c39e9ac)

I have seen that the same solution has been added, but I don't know if it is more correct to add the commit of the fix that already exists.

**Comment by ChrisOForgeFlow** [comment]
I believe that migration was done before the commit you refer was merged(https://github.com/OCA/account-invoicing/pull/1292), because that commit is not included

**Comment by RodrigoBM** [comment]
But the correction Nov 25, 2022 and your migration is from Dec 23, 2022, I understand that you have to add that comit.

**Comment by ChrisOForgeFlow** [comment]
> But the correction Nov 25, 2022 and your migration is from Dec 23, 2022, I understand that you have to add that comit.

Yes, commit is Nov 25, but was merged after my PR , because that when I retrieve all history of commit on migration process, this commit was not merged yet

image

**Comment by etobella** [comment]
@ChrisOForgeFlow It is not a problem if the PR was merged or not before the creation of the commit. It is a patch that is needed. For this reason, it is interesting to add it.

Actually, it comes from an old PR opened by me https://github.com/OCA/account-invoicing/pull/1131 and I forgot to port it to 14. Can you add it manually using cherry-pick, please? :pray:

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow It is not a problem if the PR was merged or not before the creation of the commit. It is a patch that is needed. For this reason, it is interesting to add it.
> 
> Actually, it comes from an old PR opened by me #1131 and I forgot to port it to 14. Can you add it manually using cherry-pick, please? pray

Done! Thank you for explanation

**Review by RodrigoBM — APPROVED** [review]

**Comment by P4R** [comment]
@rafaelbn @RodrigoBM Could you merge this?

**Comment by RodrigoBM** [comment]
ping @rafaelbn  i am not psc @P4R

**Review by rafaelbn — APPROVED** [review]
thank you 👍🏼 

/ocabot merge patch

**Pull request merged**
