### PR TITLE
[15.0][mig] account_invoice_payment_retention

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Standard Migration :100:

### CODE REVIEW

**Comment by TheerayutEncoder** [comment]
I'm fixing it.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by Saran440** [comment]
This pr cheery-pick from https://github.com/OCA/account-invoicing/pull/1165
and add new feature default account in customer invoice (receivable account)
Selection_012

When user create retention at `Customer Invoice`. payment retention will use `Retention Receivable Account`
When user create retention at `Vendor Bill`. payment retention will use `Retention Payable Account`

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
