### PR TITLE
[12.0][MIG] product_supplierinfo_for_customer_invoice

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

- [x] Depends of https://github.com/OCA/product-attribute/pull/515.

### CODE REVIEW

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
tried to create a invoice here: http://3392866-622-d6daf4.runbot1.odoo-community.org/web?debug=1#id=23&action=370&model=sale.order&view_type=form&menu_id=225

```
  File "/home/odoo/build/OCA/account-invoicing/product_supplierinfo_for_customer_invoice/models/account_invoice.py", line 14, in _get_product_customer_code
    for line in self.filtered(lambda il: il.product_id.supplier_ids):
  File "/.repo_requirements/odoo/odoo/models.py", line 4898, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/.repo_requirements/odoo/odoo/models.py", line 4898, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/build/OCA/account-invoicing/product_supplierinfo_for_customer_invoice/models/account_invoice.py", line 14, in <lambda>
    for line in self.filtered(lambda il: il.product_id.supplier_ids):
AttributeError: 'product.product' object has no attribute 'supplier_ids'
```

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
broken

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional review LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by NuriaXifre — APPROVED** [review]
Functional review done!

**Review by JoanSForgeFlow — APPROVED** [review]

**Pull request merged**
