### PR TITLE
[12.0][FIX] company_dependent misspelled in some fields

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]

**Comment by pedrobaeza** [comment]
You should transfer existing values through a migration script

**Comment by sergiocorato** [comment]
> You should transfer existing values through a migration script

Creating the same value for all existing companies?

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/openupgradelib/blob/077068b62c2ab3ea2cb09634f1084fb5743d3067/openupgradelib/openupgrade.py#L2551 method

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Migration script needed.

**Comment by sergiocorato** [comment]
> Migration script needed.

Added

**Comment by pedrobaeza** [comment]
Are you sure you can use the same field for the source and the target of the field?

**Review by ivantodorovich — APPROVED** [review]

**Pull request closed without merging**
