### PR TITLE
[14.0][MIG] product_supplierinfo_for_customer_invoice

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Forward port of https://github.com/OCA/account-invoicing/pull/974.

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Supersedes https://github.com/OCA/account-invoicing/pull/948, as this one is aligned with version 13.

**Review by JordiMForgeFlow — APPROVED** [review]
Code review LGTM 👍🏼

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM!

**Comment by AaronHForgeFlow** [comment]
/ocabot merge nobump

come on, you can do it :)

**Pull request merged**
