### PR TITLE
[MIG] account_invoice_supplier_self_invoice: Migration to 14.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration
@etobella

### CODE REVIEW

**Review by kittiu — APPROVED** [review]
Reviewed

**Review by etobella — APPROVED** [review]

**Comment by pelaba** [comment]
can this be merged ?

**Comment by rafaelbn** [comment]
I followed the steps in runboat and...

#. Go to 'Accounting/Invoicing > Vendors > Vendors'
#. Modify a Provider and click 'Set Self Invoice' inside the page 'Sales &
   Purchases'
#. Go to 'Accounting/Invoicing > Vendors > Bills'
#. Create an invoice for the provider and validate it
#. The self invoice is accessible through the button: Self invoice

Then:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_invoice_supplier_self_invoice_report_invoice_self_document_1075
AttributeError: 'account.move' object has no attribute 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 2134, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 2065, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/addons/account/models/ir_actions_report.py", line 50, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 824, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 865, in _render_qweb_html
    return self._render_template(self.report_name, data), 'html'
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 601, in _render_template
    return view_obj._render_template(template, values)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 1718, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/opt/odoo/addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 1726, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_invoice_supplier_self_invoice_report_invoice_self_1033
  File "<template>", line 2, in body_call_content_1031
  File "<template>", line 3, in foreach_1030
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'account.move' object has no attribute 'type'
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_invoice_supplier_self_invoice_report_invoice_self_document_1075
AttributeError: 'account.move' object has no attribute 'type'

Error to render compiling AST
AttributeError: 'account.move' object has no attribute 'type'
Template: account_invoice_supplier_self_invoice.report_invoice_self_document
Path: /t/div[2]/div/h2/span[1]
Node: <span t-if="o.type == 'in_invoice' and (o.state == 'open' or o.state == 'posted')">
                    Invoice
                </span>
```

**Comment by rafaelbn** [comment]
Hello @olgamarcocb @etobella could you please review https://github.com/OCA/account-invoicing/pull/1154#issuecomment-1154498563 I got an Odoo Server Error

**Comment by etobella** [comment]
@rafaelbn I think it is fixed now. Can you recheck it please?

**Review by rafaelbn — APPROVED** [review]
Rechecked! 👍

**Pull request merged**
