### PR TITLE
[15.0][MIG] account_invoice_fixed_discount: Migration to 15.0

### PR DESCRIPTION
**Pull request by ao-landoo**
Standard migration

Opened new PR as no activity on #1186

### CODE REVIEW

**Comment by ao-landoo** [comment]
@MiquelRForgeFlow could you review this please?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by Rad0van — APPROVED** [review]
LGTM. Functional test.

**Comment by ao-landoo** [comment]
@pedrobaeza Can it be merged?

**Pull request merged**
