### PR TITLE
[7.0] [FIX] account_invoice_merge [needs review]

### PR DESCRIPTION
**Pull request by llacroix**
Missing plus operator.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Although it seems a bit odd, Python allows this concatenation without `+`, so there's no issue.

:-1:

**Comment by sbidoul** [comment]
@pedrobaeza I'd say @llacroix is right. Without the + it is equivalent to `"[('id','in',[,".join(map(str, allinvoices.keys()))` wich is not what we want.

So :+1: from my side.

**Comment by pedrobaeza** [comment]
OK, I see. You're right.

Sorry for the mistake.

:+1:

**Comment by llacroix** [comment]
Yes, that's kind of disturbing. The order of operator has some importance here.

**Comment by llacroix** [comment]
:+1:

**Pull request merged**
