### PR TITLE
[14.0][MIG] account_invoice_refund_reason

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM

**Review by JaumeBforgeFlow — APPROVED** [review]
Code and functional review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@Hardik-OSI I added some improvement from your PR https://github.com/OCA/account-invoicing/pull/905.
@SilvioC2C I added some improvement from your PR https://github.com/OCA/account-invoicing/pull/1041.
@Reyes4711-S73 I added some improvement from your PR https://github.com/OCA/account-invoicing/pull/1138.

And in the (fusion) improvement commit I added everyone authorship. This way, I think we can proceed with this PR and close the other old ones.

**Comment by AaronHForgeFlow** [comment]
Thanks for the work @MiquelRForgeFlow !

**Review by SilvioC2C — APPROVED** [review]
LGTM, thanks for your work!

**Pull request merged**
