### PR TITLE
[12.0][MIG] account_invoice_anglo_saxon_no_cogs_deferral

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

CC @Eficent

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
ping @jbeficent

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by HviorForgeFlow** [comment]
@ageficent @lreficent @aheficent could you review? Thanks!

**Comment by AaronHForgeFlow** [comment]
It  seems runbot is red because other module

**Review by AaronHForgeFlow — APPROVED** [review]
Functional checks ok

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by AaronHForgeFlow** [comment]
what module depends on brand repo?

**Comment by HviorForgeFlow** [comment]
@aheficent partner-brand was moved to brand repo from partner-contact one

**Pull request merged**
