### PR TITLE
Add error if invoices not same user_id

### PR DESCRIPTION
**Pull request by lasley**
Invoice merge fails silently if user_id is not the same on all invoices. Added error to accommodate.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think the idea is not to fail, so it's better to remove where it occurs? Can you identify it?

**Comment by lasley** [comment]
I agree with this, and can easily identify it. Question is - what user should it be switched to? This module is more of a fix-em anyways, so maybe if we just note that it will change to the user of the first invoice?

**Comment by pedrobaeza** [comment]
Yeah, I think it's the better choice. Anyway, I doubt someone uses this field as a significant one.

**Comment by lasley** [comment]
Totally agree. I'll modify the PR here in a bit :smile:

**Comment by AaronHForgeFlow** [comment]
Closing as stale. Feel free to reopen if working again on this.

**Pull request closed without merging**
