### PR TITLE
[FIX] account_invoice_triple_discount: Developer Mode was required to use discounts

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Shouldn't it be `product.group_discount_per_so_line` as with `discount`?

**Comment by dreispt** [comment]
Thank you @chienandalu , that's a good point. I made that correction.

**Review by chienandalu — COMMENTED** [review]
Run pre-commit to get the proper reformat

**Comment by dreispt** [comment]
Done!

**Review by chienandalu — APPROVED** [review]
:slightly_smiling_face: :+1:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
