### PR TITLE
FIX acc_invoice_pricelist: tax include in multicompany

### PR DESCRIPTION
**Pull request by bealdav**
backport of https://github.com/OCA/account-invoicing/pull/550

@pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Fast-tracking this

**Comment by pedrobaeza** [comment]
@sbidoul if I put something extra in the comment apart from `\ocabot...`, the bot doesn't recognize the command. Is that something solvable?

**Comment by sbidoul** [comment]
Yes that's solvable, the command parser is quite rudimentary for now, it can certainly be improved. Can you create an issue for that?

**Pull request merged**
