### PR TITLE
[13.0][FIX] sale_order_invoicing_grouping_criteria: Return recordset instead of list

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this patch

**Comment by pedrobaeza** [comment]
Ouch, pre-commit fails. Why don't you install locally for being run always (`pre-commit install -f` in your repository)?

**Comment by sergio-teruel** [comment]
Ohh Yes, I already have it installed, but in some cases I forget execute it locally....

**Pull request merged**
