### PR TITLE
[add] free invoice line module

### PR DESCRIPTION
**Pull request by scigghia**
Hi all!
This module adds management of Free invoice lines (omaggio in fattura for Italian accounting)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Andrea, can you ellaborate the user case for this module?

**Comment by scigghia** [comment]
Hi Pedro,
it is usefull when user needs to invoice one or more "free samples", then the amount for these lines  and tax lines must be 0

**Comment by pedrobaeza** [comment]
Yeah,  but this can be easily achieved filling a 100% discount or emptying the price.

Technically speaking, you're entirely overwriting `_amount_all`, which is a very bad bad practise, so for now :-1:

**Comment by alexis-via** [comment]
I have the same opinion as Pedro. It don't understand why we would need a full module with so many lines of code just to have an invoice line at 0 ; you could set the unit_price to 0 or set the discount to 100%... and you would get the same result, no ?

**Comment by joaoalf** [comment]
:-1: 
Agree with others.

**Pull request closed without merging**
