### PR TITLE
Add module 'account_invoice_uom'

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by eLBati** [comment]
Even if WIP, this gets my :+1:

**Comment by eLBati** [comment]
@tafaRU what needs to be done here?

**Comment by tafaRU** [comment]
@eLBati I've just completed the last changes, now the PR is ready for review.

**Comment by eLBati** [comment]
Thanks :+1:

**Comment by archetipo** [comment]
:+1:

**Pull request merged**
