### PR TITLE
[15.0][MIG] stock_picking_invoicing_incoterm

### PR DESCRIPTION
**Pull request by yankinmax**
Forward opened migration PR to v15:
 - [ ] https://github.com/OCA/account-invoicing/pull/828

### CODE REVIEW

**Comment by yankinmax** [comment]
I wonder how can we solve this issue happening on install of this module:
```
odoo.addons.account_invoice_fiscal_position_update.tests.test_inv_fiscal_pos_update: Starting TestProductIdChange.test_fiscal_position_id_change ... 
2022-05-18 11:12:12,043 258 ERROR odoo odoo.sql_db: bad query: UPDATE "product_product" SET "can_image_variant_1024_be_zoomed"=false,"combination_indices"='',"write_date"='2022-05-18T11:12:09.386489'::timestamp,"write_uid"=10 WHERE id IN (49)
ERROR: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(38, ) already exists.
```

**Review by ajaniszewska-dev — APPROVED** [review]
code LG but have no idea how to help with build.

**Comment by MiquelRForgeFlow** [comment]
@yankinmax that error is already fixed. please rebase

**Comment by yankinmax** [comment]
@MiquelRForgeFlow can you pls submit your review here? so, we can ask to merge it

**Comment by MiquelRForgeFlow** [comment]
@yankinmax if the module doesn't depend on https://github.com/OCA/account-invoicing/pull/828 anymore, please edit first post to avoid misleads 😉

**Comment by yankinmax** [comment]
@MiquelRForgeFlow why do you think it doesn't depend? It's still the same case.

**Comment by MiquelRForgeFlow** [comment]
I mean, if it depends, then it should be in the manifest as a dependency.

**Comment by yankinmax** [comment]
> I mean, if it depends, then it should be in the manifest as a dependency.

Ah, I see a misunderstanding. Sorry. It doesn't depend in the sense of the module dependency.
It's just that I cherry-picked commits from that PR, which migrates this module to v14.
Updating PR description

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by yankinmax** [comment]
@dreispt can you pls help to get it merged?

**Pull request merged**
