### PR TITLE
Slovene translation added

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
No code changes, just translations added based on existing templates.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically correct.

:+1:

**Comment by yvaucher** [comment]
@sysadminmatmoz The commit is not linked to your github account.

You need to configure your email, either on your local git config or on github.

**Comment by pedrobaeza** [comment]
You should rebase your branch.

**Comment by sysadminmatmoz** [comment]
Well, the paperwork is done too :)

**Comment by sysadminmatmoz** [comment]
Sorry, I'm becoming careless with age. :)

**Comment by pedrobaeza** [comment]
There's still some undesired changes. You can locate them in files or commits.

**Pull request closed without merging**
