### PR TITLE
[13.0][NEW][account_invoice_force_origin] New module to force invoice_origin field

### PR DESCRIPTION
**Pull request by robyf70**
New module to permit to force invoice_origin field.

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]
@robyf70 Can you rebase?

**Comment by robyf70** [comment]
> @robyf70 Can you rebase?

Done

**Comment by JordiBForgeFlow** [comment]
@robyf70 Travis fails due to the pre-commit. You should install pre-commit in your computer. See https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

**Comment by robyf70** [comment]
> @robyf70 Travis fails due to the pre-commit. You should install pre-commit in your computer. See https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

Ah! Forgot to do that! I did it now

**Comment by JordiBForgeFlow** [comment]
FYI @HviorForgeFlow

**Pull request merged**
