### PR TITLE
[ADD] new module account_invoice_uom_column

### PR DESCRIPTION
**Pull request by legalsylvain**
**Rational:**

by default, in Odoo, quantity and UoM are in the same column in report. That can be not very readable, and for analysis (invoice2data usage) it is not optimal This module split the column into two dedicated columns Quantity + UoM.

**Invoice report - Without the module**

1_without_module

**Invoice report - WITH the module**

2_with_module

### CODE REVIEW

**Review by quentinDupont — APPROVED** [review]
Code review, well documented :heavy_check_mark: 
And works in production !

**Review by rvalyi — APPROVED** [review]
LGTM

**Comment by legalsylvain** [comment]
@rvalyi : could you merge this one, as it is approved. 

a quick review on this similar one is welcome, if you have a time : https://github.com/OCA/account-invoicing/pull/1601

thannks !

**Comment by rvalyi** [comment]
here you go:

/ocabot merge nobump

**Pull request merged**
