### PR TITLE
[10.0][ADD] account_invoice_date_required

### PR DESCRIPTION
**Pull request by rousseldenis**
In Odoo, when you validate an invoice with a void invoice date, it is
automatically filled in with current date (today).
 The invoice validation is now restricted if the invoice date is not filled in.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Review by Cedric-Pigeon — APPROVED** [review]
Code review OK. Could please add a small description on you PR for people to understand what it aims to do ?

**Comment by rousseldenis** [comment]
> Could please add a small description on you PR for people to understand what it aims to do ?

Done

**Review by tafaRU — APPROVED** [review]
Only code review.

**Comment by rousseldenis** [comment]
Set to WIP. Tests are failing. Will add an option

**Comment by tafaRU** [comment]
@rousseldenis ping me when you want to change the status.

**Comment by Cedric-Pigeon** [comment]
@rousseldenis What's the status of this ?

**Review by ThomasBinsfeld — APPROVED** [review]

**Pull request merged**
