### PR TITLE
[MIG] account_invoice_mode_at_shipping: Migration to 15.0

### PR DESCRIPTION
**Pull request by BertVGroenendael**

### CODE REVIEW

**Comment by ajaniszewska-dev** [comment]
@BertVGroenendael can you please fix build?

**Comment by rven** [comment]
> @BertVGroenendael can you please fix build?

@ajaniszewska-dev This build cannot be fixed at this moment because it depends on account_invoice_base_invoicing_mode which is also in PR https://github.com/OCA/account-invoicing/pull/1061

**Review by ajaniszewska-dev — APPROVED** [review]
code LG, for dependency OCA PRs you may use test-requirements.txt to refer them for test/build purpose.

**Comment by rven** [comment]
> test-requirements.txt
Do you mean this https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#185oca_dependenciestxt?
Does this also work for modules in the same repository?

**Comment by ajaniszewska-dev** [comment]
> > test-requirements.txt
> > Do you mean this https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#185oca_dependenciestxt?
> > Does this also work for modules in the same repository?

yes, however afair there is no test-requirements specified in this doc (i don't know why). How it was worked for me, to add in separate commit test-requirements.txt file with content inside:

`git+https://github.com/OCA/$REPO@refs/pull/$PR_number/head#subdirectory=setup/$MODULE
`
you should replace everything starting with $ so in your case syntax in the file would be something like:

`git+https://github.com/OCA/account-invoicing@refs/pull/1061/head#subdirectory=setup/account_invoice_base_invoicing_mode`

plus worth add note in PR description that it depends on PR (PR number) and dependency file was updated in the separate commit.

**Comment by rven** [comment]
This module depends on https://github.com/OCA/account-invoicing/pull/1061.
test-requirements.txt file added in separated commit.

**Comment by StefanRijnhart** [comment]
Closing in favour of https://github.com/OCA/account-invoicing/pull/1247. I have now based the 16.0 migration of the module on that PR. Thank you nevertheless for your contribution!

**Pull request closed without merging**
