### PR TITLE
[15.0][MIG] account_invoice_validation_queued

### PR DESCRIPTION
**Pull request by BT-jcolmeiro**
Standard migration.

Seems to work straight out of the box from v14.

Substituted SavepointCase for TransactionCase due to deprecation.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Looks like you need to commit the setup directory
```
Run newfiles="$(git ls-files --others --exclude-from=.gitignore)"
Please check-in the following files:
setup/account_invoice_validation_queued/odoo/addons/account_invoice_validation_queued
Error: Process completed with exit code 1.
```

**Comment by BT-jcolmeiro** [comment]
@StefanRijnhart You where right. Done!

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update!

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test

**Pull request merged**
