### PR TITLE
[FIX] sale_order_partial_invoice: Precision on computed fields

### PR DESCRIPTION
**Pull request by pedrobaeza**
There's a rounding problem sometimes when summing quantities for the partial invoices. This patch solves it.

cc @gurneyalex

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1: (code review only, no test)

**Comment by gurneyalex** [comment]
can you describe a scenario exhibiting the issue?

**Comment by pedrobaeza** [comment]
I have a sale order that was invoiced in 3 times: 0.35, 0.35 and 0.30, and the result of the sum was 0,9999999! In that case, the sale order was not given as done, and the line is still presented to be invoiced.

**Comment by eLBati** [comment]
LGTM :+1:

**Comment by pedrobaeza** [comment]
Please merge

**Pull request merged**
