### PR TITLE
[14.0][ADD] account_invoice_date_default

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
This module adds the default date in invoices to the current date, as it was in previous Odoo version.

Normally the date will be today's date and this will save time.

@ForgeFlow

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
LGTM

**Review by dreispt — APPROVED** [review]

**Comment by sergiocorato** [comment]
@AaronHForgeFlow You should permit ocabot to rebase your repos, to simplify the job of the PSC :)

**Pull request closed without merging**
