### PR TITLE
[17.0][MIG] account_invoice_crm_tag: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Missing "pre-commit" commit.

/ocabot migration account_invoice_crm_tag

**Comment by peluko00** [comment]
Module migrated to version 17.0

cc https://github.com/APSL 148963

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

Issue https://github.com/OCA/hr/issues/1600

**Review by David-solyddigital — APPROVED** [review]
Functional is OK

**Review by moitabenfdz — APPROVED** [review]
Functional and code review. LGTM

**Comment by pedrobaeza** [comment]
Please fix commit history (missing pre-commit commit, weird ` [UPD] Update account_invoice_crm_tag.pot` commit, etc) and you will need to rebase this branch and fix the things that arise.

**Comment by peluko00** [comment]
Please @pedrobaeza can you review it

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_invoice_crm_tag
/ocabot merge nobump

**Pull request merged**
