### PR TITLE
[15.0] [MIG] account_move_tier_validation_forward

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/server-ux/pull/528

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]
Code review LGTM

**Comment by adrienpeiffer** [comment]
@JasminSForgeFlow Could you check why tests are failing ?

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow Could you check why tests are failing ?

It failed because the dependent module was not merged, now rebased and seemed fine.
Thanks

**Review by adrienpeiffer — APPROVED** [review]

**Pull request merged**
