### PR TITLE
Revert "[IMP] account_invoice_merge: refactor invoice merging"

### PR DESCRIPTION
**Pull request by elicoidal**
Reverts OCA/account-invoicing#386

### CODE REVIEW

**Comment by elicoidal** [comment]
@mreficent @intero-chz

**Comment by elicoidal** [comment]
@mpanarin

**Comment by elicoidal** [comment]
Travis is green again: Fast tracking

**Comment by mpanarin** [comment]
Okay, although I don't really understand the reason for the revert. Because of this refactor modules started failing or what? As during the development the branch was green. Maybe instead of reverting this, fixing the failing modules was worth the shot?

**Comment by intero-chz** [comment]
@mpanarin i think this fixes should be done with this PR here. As i already wrote only the _attachment module seems a bit more complicated. The other two modules should be fixed in no time :-)

**Pull request merged**
