### PR TITLE
[ADD] new module account_invoice_update_check to prevent to write on invoices lines of non draft invoices

### PR DESCRIPTION
**Pull request by legalsylvain**
This trivial module prevent to write on ``account.invoice.line`` model, if invoices are not in draft state.

It is a similar implementation as ``account.move.line`` checks, present in ``account`` module.
see : https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L1301

it prevent to make write : 
- via ORM
- via extra modules developped
- via some OCA modules configured like ``mass_editing``.

Thanks for your review.

GRAP-267.
CC : @quentinDupont.

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
👍

**Review by quentinDupont — APPROVED** [review]
:heavy_check_mark:

**Comment by legalsylvain** [comment]
Hi @rafaelbn, could you merge this one ? thanks !

**Review by primes2h — APPROVED** [review]
LGTM

Thanks!

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
