### PR TITLE
[REM] account_invoice_rounding: remove useless prints

### PR DESCRIPTION
**Pull request by Yenthe666**

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]
on one hand you think "how that in the OCA, come one?", then you even do a git-blame to find out the culprit https://github.com/OCA/account-invoicing/blame/1f3dab4ed24d4642661348b2872344012b78ca16/account_invoice_rounding/tests/test_invoice_rounding.py#L73

And then you think: "come one this is a v8 test"...

@Yenthe666 are you not the Odoo bleeding edge guy or what?

**Comment by Yenthe666** [comment]
@rvalyi haha, one of our tests blew up on this one so I decided to fix it, no matter how small and old it may seem :) 
Some attempts to contribute to OCA.

**Review by jgrandguillaume — APPROVED** [review]
LGTM thx ;)

**Comment by Yenthe666** [comment]
@jgrandguillaume any chance you could get it fixed? 🤔

**Comment by Yenthe666** [comment]
ty :)

**Pull request merged**
