### PR TITLE
[14.0][MIG]account_invoice_fixed_discount

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration
Supersedes https://github.com/OCA/account-invoicing/pull/865

### CODE REVIEW

**Comment by manuelregidor** [comment]
@ValentinVinagre @HaraldPanten

**Comment by osi-scampbell** [comment]
@manuelregidor What about #835? Can close that one and keep this one?

**Review by desdelinux — APPROVED** [review]
Functional Review is Ok

@ValentinVinagre @HaraldPanten

**Comment by manuelregidor** [comment]
@osi-scampbell OK. Thank you.

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
