### PR TITLE
[13.0][MIG] account_invoice_fiscal_position_update

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Works as expected

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza is anything missing here?

**Pull request merged**
