### PR TITLE
[14.0][ADD] account_invoice_payment_retention

### PR DESCRIPTION
**Pull request by Saran440**
### Overview

This module will provide optional feature for invoice/payment
1. At "vendor bill", user can plan for percent/amount to be retained during payment
2. At "payment", to retain the amount as planned (enforce / not enforce)
3. At a later time, create new "vendor bill", user can select the payment with retention (journal entrie(s)), to clear out that retention.

Note: This works for customer invoice the same way.

### Sample use cases
My company issue a service contract to a supplier with condition, there will be 10% warranty retention for every payment issued. And that after 1 year passed, my company will return that retained amount to the supplier.

### To activate the feature in Odoo,

image

### Plan for retention 10% during invoice

image

### Retention occur during payment

image

image

### Time passed, now it is time to return the retained amount

image

### CODE REVIEW

**Comment by kittiu** [comment]
Please rebase.

**Comment by Saran440** [comment]
Rebased.

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Comment by kittiu** [comment]
@Saran440 travis is red. There is error `The Bill/Refund date is required to validate this document.`, please fix the test script.
Thanks.

**Comment by Saran440** [comment]
@kittiu I fixed, Could you rebase this pr, if it's okay.

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
> @kittiu I fixed, Could you rebase this pr, if it's okay.

Done

**Review by antoniocanovas — APPROVED** [review]
Functional review, after demo data changes

**Pull request merged**
