### PR TITLE
[15.0][FIX] account_invoice_mass_sending: Users have extra notifications when the invoice has sent by the job

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT51673

ping @pilarvargas-tecnativa @chienandalu

### CODE REVIEW

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by jguenat** [comment]
thanks @sergio-teruel 
This is to avoid other follower of the invoice to get notification when it is send by the job right?
Kind of hard to test it on runboat because queue_job is not enabled there.
Does it has any side effect when module mass_mailing is installed?

**Comment by sergio-teruel** [comment]
Hi @jguenat I do not try with this module but I don't think it should be a problem.
The compute method is altered only if 'account_invoice_mass_sending' key comes in context

**Review by jguenat — APPROVED** [review]
Indeed no issue with mail_marketing.
Tested it and it works well thanks
If making codecov happy is mendatory then we just need a test sending an invoice without enqueue_invoices

**Comment by pedrobaeza** [comment]
Fw-port it to upper versions:

/ocabot merge patch

**Pull request merged**
