### PR TITLE
8.0 invoice merge fix

### PR DESCRIPTION
**Pull request by luc-demeyer**
change logic to ensure correct restoration of sale_order_line - invoice_line relation

### CODE REVIEW

**Comment by NL66278** [comment]
:+1:  LGTM And green on tests

**Comment by lfreeke** [comment]
:+1: LGTM

**Review by pankk — APPROVED** [review]
👍

**Comment by luc-demeyer** [comment]
3 positive reviews.
I think this one is ready for merge.
Can someone do this ?
Tx,
Luc

**Comment by pedrobaeza** [comment]
OK, merging.

**Comment by pedrobaeza** [comment]
The merge of this has turned red Travis. Please check:

https://travis-ci.org/OCA/account-invoicing/builds/194029915

**Comment by luc-demeyer** [comment]
I'll have a look and make a new PR to fix this error.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
it seems like the 'SharedSetupTransactionCase' is broken in the current version of Odoo 8.0.
This problem may as a consequence impact all upcoming Pull Requests on any 8.0 OCA branch.

I fixed the account_invoice_line_sort tests by using the 'TransactionCase'
https://github.com/OCA/account-invoicing/pull/220/commits/9a0c94d12ea350e250b9f7cb388211f0871b8846

@sbidoul 
Since this is an ACSONE module: can you also have a look to this fix (while bypassing the 'SharedSetupTransactionCase' issue, I also found a small bug in the account.invoice.line, create method and included that fix in this PR.

**Pull request merged**
