### PR TITLE
[16.0][MIG] Migration of module account_invoice_tree_currency

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration of module account_invoice_tree_currency

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by Gelo-fl** [comment]
@alan196 Can you fix runboat to test the module?

**Comment by alan196** [comment]
@Gelo-fl the branch is rebased and runboat is now running

**Review by Gelo-fl — APPROVED** [review]
LGTM https://www.awesomescreenshot.com/video/19398949?key=5b22cdb1f6cd4956b1061d358a5b6373

**Review by RodrigoBM — APPROVED** [review]

**Comment by ghost** [comment]
ping @pedrobaeza

**Pull request merged**
