### PR TITLE
[13.0][MIG/REF] product_supplierinfo_for_customer_invoice

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
- migrate and adapt to account.move.
- use `_select_customerinfo` method.
- add tests.

* [x] :Depends on https://github.com/OCA/product-attribute/pull/891.

@ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
Code + functional review 👍🏼

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by LoisRForgeFlow** [comment]
@OCA/accounting-maintainers Could anyone merge?

**Pull request merged**
