### PR TITLE
[MIG] account_invoice_alternate_payer: Migration to 14.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration
Depends on #1149

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]
LG

**Review by etobella — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
code review LGTM

**Comment by etobella** [comment]
@ChrisOForgeFlow Ask before superseeding please. Fixed now. The problem was related to the change of the onchange fields.... Added a new function for the field and all should work properly now

**Pull request merged**
