### PR TITLE
[FIX] Do not overwrite account's view when adding kanban

### PR DESCRIPTION
**Pull request by SimoRubi**
Add kanban as first view without overwriting account's views.

### CODE REVIEW

**Review by hurrinico — APPROVED** [review]
👍

**Comment by eLBati** [comment]
> Do not overwrite account's view when adding kanban

Why not? Wasn't this done on purpose?
cc @elicoidal

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
@eLBati The issue here is that, before the PR, the view `account.action_invoice_tree1_view1` is replaced with a view of type kanban while originally (i.e in `account` module) it is of type tree.
Then, when the tree view is opened, it is the tree view of supplier invoices instead of the correct one (the tree view declared in `account`).

With this PR, I am adding a new view of type `kanban` and placing it before (`sequence = 0`) the tree view, instead of editing the original tree view declared in the menu's action.

I know it is complicated but let me try to clarify the situation:
In module `account`, the menu's action declared two views:
- tree `account.invoice_tree`
- form

Before the PR, in this module
- ~tree~ kanban Then the tree view opened was determined by the system and it might be no more `account.invoice_tree`
- form


After the PR:
- kanban 
- tree `account.invoice_tree`
- form

Same applies for supplier views/actions

**Comment by pedrobaeza** [comment]
I think the purpose is to not have that kanban view normally visible by default, but having it for mobile view with `web_responsive` / `web_enterprise` to show it

**Review by elicoidal — APPROVED** [review]
Change looks OK to me (I do not know the reasons of the original design but your proposal looks sane to me).
Version number should be 10.0.1.1.0 (you need to update the module)

**Comment by pedrobaeza** [comment]
But as said, I prefer to not have kanban on desktop views.

**Comment by SimoRubi** [comment]
Right @elicoidal I updated the version number.

@pedrobaeza I've read the README of the module again, I'm sorry but it just enjoys using kanban views for viewing invoices and says nothing about mobile/desktop.
Anyway, I'm not changing the behavior of this module, I'm just fixing what I explained earlier and I think it was a bug, you can check in any runbot of 10.0 for this repository with the following steps:
1. Go to invoicing > Customer invoices
2. Open the tree view
3. In debug, check that the tree view is `account.invoice_supplier_tree` (in standard odoo it is `account.invoice_tree`)

**Comment by SimoRubi** [comment]
squashed commits

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers can this be merged?
Thanks

**Comment by elicoidal** [comment]
@pedrobaeza please confirm we can move on.

**Comment by pedrobaeza** [comment]
OK, let's go with this.

**Pull request merged**
