### PR TITLE
[14.0][ADD] account_move_cancel_confirm

### PR DESCRIPTION
**Pull request by kittiu**
Depends on,
- [x] base_cancel_confirm https://github.com/OCA/server-ux/pull/297

This module extend `base_cancel_confirm` to make cancel confirmation with cancel reason (none / optional / requried).

Selection_044

### CODE REVIEW

**Comment by Saran440** [comment]
@kittiu please, review my commit https://github.com/OCA/account-invoicing/pull/872/commits/d70c0468bc76d2a06fd941dd03dd4a0544cb4132

Step to error:
1. Create vendor bills
2. Confirm > Register Payment
3. Reset to Draft Payment
4. Cancel Payment

payment can't change state to draft because payment cancel depend on cancel journal entries and it need reason cancel.
then, we add cancel reason on payment and pass value to journal entries.

I think PR https://github.com/OCA/account-payment/pull/449 is not need to add.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by kittiu** [comment]
Can you squash commit @Saran440

**Comment by Saran440** [comment]
still red because module `account_receipt_print` has error
waiting to merge - https://github.com/OCA/account-invoicing/pull/1262

**Comment by Saran440** [comment]
This PR ready to review and merge.

**Review by ps-tubtim — APPROVED** [review]

**Pull request closed without merging**
