### PR TITLE
[10.0] invoice_supplierinfo_update reworked naming on wizard buttons

### PR DESCRIPTION
**Pull request by PierrickBrun**
The buttons names where confusing, this commit makes it more
understandable.
It is only cosmetic change

### CODE REVIEW

**Comment by PierrickBrun** [comment]
@chafique-delli  @mourad-ehm @legalsylvain 
What do you think about it ? I think I will propagate the changes in 8.0 when it will be merged

**Comment by PierrickBrun** [comment]
@chafique-delli  @mourad-ehm @legalsylvain 
What do you think about it ? I think I will propagate the changes in 8.0 when it will be merged

**Comment by youring** [comment]
I think you were misunderstanding the button function. According to code,
**update_supplierinfo**: create/update supplier info _and_ mark the invoice as checked;
**update_supplierinfo_validate**: do above and validate the invoice.
But on the contrary, i think this module should not do stuff like validating invoice. Your modification on button names still make sense if change the wizard method a little bit.

**Comment by legalsylvain** [comment]
I see the new string as more confusing. 
Update without validate is clear ans reuse core terms. Update temporarily has less sense for me.

**Pull request closed without merging**
