### PR TITLE
[15.0][MIG] account_receipt_journal

### PR DESCRIPTION
**Pull request by Shide**
Straight forward migration + Improvements from https://github.com/OCA/account-invoicing/pull/1398#pullrequestreview-1317904177

MT-2035 @moduon @rafaelbn @SirTakobi @eLBati

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review is good.

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Hello, after review. I know this is a migration but module is incomplete from my point of view @eLBati @SirTakobi . Explanation with the improvement we should make:

- Create a Invoice in a Journal that is dedicated for receipts shouldn't happend never. That is the purpose of the module.

- Actually a user can create from invoicing an invoice in a receipt journal and this shouldn't happend.
 
@Shide please, improve me module to make it move robust

Video: https://www.loom.com/share/58480c3d895a40169b4b1091a777936d

I guess previous versions they are using it to create from sales or purchase, but our use case is directly by invoicing user (not accountant).

Thank you!

**Review by rafaelbn — APPROVED** [review]
👍

**Comment by rafaelbn** [comment]
@yajo @sbidoul  please could you help here with runboat? I mean how can we know hoy to solve with runboat is "pending"? Thank you!

**Comment by sbidoul** [comment]
Maybe a webhook call got lost. Try pushing a commit on this pr.

**Comment by rafaelbn** [comment]
Thank you! @Shide try a commit please

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
