### PR TITLE
[16.0][MIG] account_invoice_payment_term_date_due: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-anieto**
#1476 and #1473 are stale, so I take it.

### CODE REVIEW

**Comment by BT-anieto** [comment]
Hello @ivantodorovich Could you take a look at this PR? I do not know why tests are failing. I don't get the error message.

**Comment by BT-anieto** [comment]
@OCA/accounting-maintainers Hello. Could anyone tell me why the tests are failing? Thank you very much

**Review by BT-dherreros — APPROVED** [review]
LGTM

**Review by BT-pcavero — APPROVED** [review]
Looks good!

**Comment by BT-anieto** [comment]
@OCA/accounting-maintainers Good for merge?

**Comment by BT-anieto** [comment]
Good morning @pedrobaeza. Sorry to bother you, but neither the accounting maintainers nor the module maintainers answer me.

Could we merge this PR?

**Comment by pedrobaeza** [comment]
I'm not seeing the changes in https://github.com/OCA/account-invoicing/pull/1473/commits/cbb3d21d37987ad32f1117a9a1dec1dada6bd3bc#diff-24efa77db9de5fef130c82c8f7db072cf578342dc768017ba2113da1340000d9. Aren't they needed?

**Comment by BT-anieto** [comment]
I would say no. This was causing strange render.

**Pull request merged**
