### PR TITLE
Migration V9 account_invoice_merge

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please sign the CLA as found in https://odoo-community.org/page/cla

**Comment by pedrobaeza** [comment]
Why do you change the title I have put?

**Comment by ghost** [comment]
Sorry, was actually changing my previous title to align with the other
descriptions, so we have changed it almost at the same time. My apologies,
was really not intended.

2016-04-04 16:57 GMT+02:00 Pedro M. Baeza notifications@github.com:

**Comment by pedrobaeza** [comment]
OK, no problem. It was just curious. I try to put the the same title as the commit messages, as this one is then put in the commit when merging the PR.

**Comment by bistaray** [comment]
Good day!  What's the status of this?  It is ready to be merged, completing the migration to v9?

**Comment by antonybrugger** [comment]
+1

**Comment by antonybrugger** [comment]
Can you please merge this? Thank you

**Comment by pedrobaeza** [comment]
@antonybrugger, it's needed at least 2 approvals and 5 working days from the proposal, or 3 if before, but 1 of the reviews must be from something reliable (not a first contributor, sorry).

**Comment by tpalan** [comment]
should the version in **openerp**.py be changed to 9.0....?

**Comment by antonybrugger** [comment]
@pedrobaeza so can I know when OCA will merge this. Don't think it's big changes and initial PR is from April 2016

**Comment by pedrobaeza** [comment]
When a second review is done. This is not something with the original date, but with the involvement of the contributors. People don't review for free:
1. They have interest in the module/enhancement, so they review it for getting the module/enhancement.
2. The contributor or someone in the environment reviews some other opened PRs in the same repo or similar ones, and ask as counterpart to review this one.

It seems that there isn't anyone on point 1, so you should go for point 2.

**Comment by aristobulo-eezee** [comment]
@pedrobaeza I saw some details on this PR, would it be ok if I continue from this branch and open another PR? We need this module and I can dedicate some time to make it right. What do you think?

**Comment by pedrobaeza** [comment]
@aristobulo-eezee, let's ping @BT-hstoeckle to see if he is going to continue maintaining this PR. If so, then you should make a PR against his branch to be merged by him and get it here. If not, we close this PR and you start from the branch, but creating a new PR.

Deal?

**Comment by aristobulo-eezee** [comment]
So, still nothing? can we take care of this one or what? @pedrobaeza

**Comment by aristobulo-eezee** [comment]
@dreispt @gurneyalex maybe you could unblock this?

**Comment by antonybrugger** [comment]
@pedrobaeza we need this to be merged and we have done the work, what is the pb to merge in the OCA process! ?

**Comment by pedrobaeza** [comment]
There's still no interest by anyone more in reviewing, and you haven't made any review for encouraging people to review yours in exchange...

**Comment by aristobulo-eezee** [comment]
@pedrobaeza this is not ours, you blocked us from proposing ours, we tried to review this, you also said no. What are you talking about?

**Comment by pedrobaeza** [comment]
I didn't block it. I just said that the original contributor should say if it's interested in maintaining the PR, having priority as being the first one to propose it. 

He has spoken, but he wants to merge the PR without making the effort of reviewing others for asking for other reviewers in exchange and expecting that people is going to review for free his PR. I'm just saying that there's no 2 reviews as the rules stated (only yours). Other times, when contributions come from reputed contributors that have already made a lot of them, there's more trust on merging with only 1 review, but it's not the case.

I hope you understand that the blocking is not by my part, but it's yours trying to get shortcuts.

P.S.: The rules are clearly exposed in the contributing file: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#review

**Comment by alexis-via** [comment]
:+1:  once my PR to improve this port is merged https://github.com/BT-hstoeckle/account-invoicing/pull/1 Thanks for your work !

**Comment by pedrobaeza** [comment]
Thanks for you review and patch, @alexis-via.

There are still 2 things needed before merging:
- Travis status is red, so you have to see the reason and solve it: https://travis-ci.org/OCA/account-invoicing/jobs/173100846#L807.
- @BT-hstoeckl, please squash your 4 commits together.

**Comment by gurneyalex** [comment]
@alexis-via you probably forgot to git add `models/__init__.py` when you submitted https://github.com/BT-hstoeckle/account-invoicing/pull/1 and this is breaking the CI. 

If you have this at hand, can you submit another PR. Or maybe @BT-hstoeckle can handle it directly.

**Comment by alexis-via** [comment]
yes, I know, I made a PR just a few hours after, but it's not merged yet : https://github.com/BT-hstoeckle/account-invoicing/pull/2

**Comment by pedrobaeza** [comment]
It seems there's no more interest from the original author. @alexis-via, can you please make a new PR with all?

**Comment by pedrobaeza** [comment]
Closed superseeded by #209

**Pull request closed without merging**
