### PR TITLE
[15.0] [MIG] account_invoice_discount_display_amount

### PR DESCRIPTION
**Pull request by alexeirivera87**

### CODE REVIEW

**Comment by alexeirivera87** [comment]
@ernestotejeda

**Comment by rafaelbn** [comment]
Please @alexeirivera87 could you rebase?

**Comment by alexeirivera87** [comment]
@rafaelbn 

It's done

**Comment by rafaelbn** [comment]
This module only display the ammount in Odoo and not in the invoice PDF?

**Comment by alexeirivera87** [comment]
> This module only display the ammount in Odoo and not in the invoice PDF?

`        <xpath expr="//t[@t-call='account.document_tax_totals']" position="after">
            <tr t-if="display_discount" class="border-black">
                <td name="td_discount_total_label"><strong>Discount</strong></td>
                <td name="td_discount_total" class="text-right">
                    <span t-field="o.discount_total" />
                </td>
            </tr>
        </xpath>`

The amount is displayed in the PDF, the module is almost the same, compared to its similar in v14.

**Review by rafaelbn — APPROVED** [review]
👍🏼 

imagen

**Review by fcvalgar — APPROVED** [review]
Functional review.
LGTM, thank you @alexeirivera87 

image


image

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by rafaelbn** [comment]
Please @alexeirivera87 , review why travis is 🔴  Thank you!

```
2023-08-03 23:13:53,880 256 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_fixed_pricelist_without_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 317, in test_account_invoice_fixed_pricelist_without_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 65.41)
AssertionError: 100.0 != 65.41 within 7 places (34.59 difference)
 
2023-08-03 23:13:53,885 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist ... 
2023-08-03 23:13:53,900 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist_with_discount_secondary_currency ... 
2023-08-03 23:13:54,049 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: ====================================================================== 
2023-08-03 23:13:54,050 256 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_pricelist_with_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 293, in test_account_invoice_pricelist_with_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 58.87)
AssertionError: 90.0 != 58.87 within 7 places (31.130000000000003 difference)
 
2023-08-03 23:13:54,053 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist_without_discount ... 
2023-08-03 23:13:54,185 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_pricelist_without_discount_secondary_currency ... 
2023-08-03 23:13:54,324 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: ====================================================================== 
2023-08-03 23:13:54,324 256 ERROR odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: FAIL: TestAccountMovePricelist.test_account_invoice_pricelist_without_discount_secondary_currency
Traceback (most recent call last):
  File "/__w/account-invoicing/account-invoicing/account_invoice_pricelist/tests/test_account_move_pricelist.py", line 301, in test_account_invoice_pricelist_without_discount_secondary_currency
    self.assertAlmostEqual(invoice_line.price_unit, 65.41)
AssertionError: 100.0 != 65.41 within 7 places (34.59 difference)
 
2023-08-03 23:13:54,326 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_with_discount_change_pricelist ... 
2023-08-03 23:13:54,469 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_account_invoice_without_discount_change_pricelist ... 
2023-08-03 23:13:54,602 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_check_currency ... 
2023-08-03 23:13:54,620 256 INFO odoo odoo.addons.account_invoice_pricelist.tests.test_account_move_pricelist: Starting TestAccountMovePricelist.test_upstream_file_hash ... 
2023-08-03 23:13:55,067 256 INFO odoo odoo.modules.loading: Module account_invoice_pricelist loaded in 2.77s (incl. 1.73s test), 128 queries (+1573 test) 
2023-08-03 23:13:55,067 256 ERROR odoo odoo.modules.loading: Module account_invoice_pricelist: 3 failures, 0 errors of 11 tests 
```

**Comment by rafaelbn** [comment]
The problem is with module `account_invoice_pricelist` and not related with this PR

This are the latest PR fixing "things" arround the `account_invoice_pricelist` (problematic module)
- https://github.com/OCA/account-invoicing/pull/1457 @mbcosta @rvalyi 
- https://github.com/OCA/account-invoicing/pull/1439 @suniagajose
- https://github.com/OCA/account-invoicing/pull/1354 @pedrobaeza

**Pull request merged**
