### PR TITLE
[15.0][MIG] account_invoice_base_invoicing_mode (renamed)

### PR DESCRIPTION
**Pull request by TDu**
Renamed to `partner_invoicing_mode`.

### CODE REVIEW

**Review by i-vyshnevska — APPROVED** [review]
LG, in the context of renaming should we suggest a migration step to handle XML updates?

**Review by StefanRijnhart — APPROVED** [review]

**Comment by TDu** [comment]
I just added the migration script for the module rename

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
I don't think that the renaming works in the migration of module itself. The renaming has to be done here: https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_scripts/apriori.py#L6

**Comment by TDu** [comment]
> I don't think that the renaming works in the migration of module itself. The renaming has to be done here: https://github.com/OCA/OpenUpgrade/blob/15.0/openupgrade_scripts/apriori.py#L6

Ok, I based that on existing commit in other repos. Do you mean I have to open a PR on openupgrade ?

**Comment by StefanRijnhart** [comment]
Yes please! In that PR, please link to this PR so that we can merge in tandem.

**Comment by StefanRijnhart** [comment]
@TDu please remove that migration bit in this PR, then we can go ahead with it.

**Comment by TDu** [comment]
I removed the migration script

**Review by StefanRijnhart — APPROVED** [review]

**Comment by rafaelbn** [comment]
@simahawk ? you merged it in v13 😄 https://github.com/OCA/account-invoicing/pull/755

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@pedrobaeza this PR is ready to be merge :) Thanks

**Comment by pedrobaeza** [comment]
Merging blindly due to the reviews:

/ocabot merge nobump

**Pull request merged**
