### PR TITLE
[12.0][MIG] account_invoice_line_sequence

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
:scream_cat: travis needs help

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Standard approval

**Review by LoisRForgeFlow — APPROVED** [review]
Standard review :laughing:

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1: 

Nitpicking: Readme file should be updated according to OCA standards

**Comment by AaronHForgeFlow** [comment]
@mreficent can you attend comments?

**Comment by MiquelRForgeFlow** [comment]
> Nitpicking: Readme file should be updated according to OCA standards

@ageficent readme fragments has been put. The readme file will be automatically generated after merging the PR.

@aheficent ready

**Pull request merged**
