### PR TITLE
[16.0][MIG] account-invoicing: account_invoice_tax_note 

### PR DESCRIPTION
**Pull request by MarinaAForgeFlow**
Supersedes PR #1477

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — COMMENTED** [review]
Sorry, I need to update my last review. There is no way to check or edit the note from the tax groups menus.

image

**Comment by JordiMForgeFlow** [comment]
@MarinaAForgeFlow could you rebase?

**Review by JordiMForgeFlow — APPROVED** [review]
Code + functional review

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
