### PR TITLE
[15.0][MIG] account_invoice_refund_reason_skip_anglo_saxon

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Depends on:

- [x] https://github.com/OCA/account-invoicing/pull/1324

original: #1272 1272

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by AaronHForgeFlow** [comment]
is this a migration?

**Comment by ChrisOForgeFlow** [comment]
> is this a migration?

I would think not originally, but now since it is already at 14 it should be marked as migration, what do you recommend I open another PR or continue with this one?

**Comment by AaronHForgeFlow** [comment]
I think you can continue on this one, but yes, better to mark this as migration

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request closed without merging**
