### PR TITLE
[13.0][ADD] account_invoice_tree_currency

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Account Invoice Tree Currency
-----------------------------------------

This module allows you to optionally show currencies in the invoice tree view.

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
What about adding in the tree view the _amount_total_ to also see the amount in the invoice currency?

**Comment by MiquelRForgeFlow** [comment]
@JordiMForgeFlow Done!

**Comment by JordiMForgeFlow** [comment]
Perhaps it would be better to display also the _amount_untaxed_, _amount_tax_ and _amount_residual_, so we can see all the relevant values in the invoice currency. 
Also I would suggest with this addition to find more suitable naming of the fields to distinguish between the Total (Company Currency) and the Total (Invoice Currency). What do you think?

**Comment by MiquelRForgeFlow** [comment]
And what are your naming proposals?

**Comment by JordiMForgeFlow** [comment]
I would say _Field_ (Currency) for the fields with invoice currency, so we can leave the standard ones as they are.

**Comment by MiquelRForgeFlow** [comment]
Done

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
