### PR TITLE
[ADD] account_receipt_base

### PR DESCRIPTION
**Pull request by SirAionTech**
Supersede #1427.

### CODE REVIEW

**Comment by SirAionTech** [comment]
> @SirTakobi @eLBati
> 
> image
> 
> Could you please force a rebuild?

(from https://github.com/OCA/account-invoicing/pull/1427#issuecomment-1711789537)

@primes2h here you have the runboat.

----
@rafaelbn would you mind reviewing this? Here I have only rebased the changes of #1427.
And maybe you can approve the workflows.

----
> cc @SirAionTech

(from https://github.com/OCA/account-invoicing/pull/1427#issuecomment-1712520367)

@eLBati would you mind reviewing this? Then maybe we'll be closer to merge.

----
Thanks all!

**Review by eLBati — APPROVED** [review]
In production

**Review by mrcast — APPROVED** [review]
Tested in production

**Comment by LorenzoC0** [comment]
Ciao @SirAionTech,
non riesco a creare una Pull Request per il tuo branch, però volevo proporti le modifiche all'interno di [questo branch](https://github.com/LorenzoC0/account-invoicing/tree/14.0-add-account_receipt_base) per poter visualizzare il widget di riconciliazione anche nelle ricevute.

**Review by primes2h — APPROVED** [review]
LGTM

Thanks!

**Comment by primes2h** [comment]
@LorenzoC0 
It would be better to merge this first.
You can then create a new PR with proposed changes.

**Comment by SirAionTech** [comment]
> @LorenzoC0 It would be better to merge this first. You can then create a new PR with proposed changes.

I already merged his changes with https://github.com/SirAionTech/account-invoicing/pull/1.

@LorenzoC0 could you please add your review here? The more approvals, the closer we are to merge :tada:

**Review by LorenzoC0 — APPROVED** [review]

**Comment by SirAionTech** [comment]
> /ocabot rebase

Fatto

**Pull request merged**
