### PR TITLE
[ADD] account_invoice_line_sequence v10

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
Account Invoice lines with sequence number
==================================

Provides a new sequence field on invoice lines which helps to manage the order of the invoice lines.

Later this sequence can be displayed on the Invoice report.

### CODE REVIEW

**Comment by serpentcs-dev1** [comment]
@aheficent Could you please take a look?

**Comment by AaronHForgeFlow** [comment]
It seems that runbot it's not working now :face_with_head_bandage:  This will need to be rebuilt.

**Comment by moylop260** [comment]
FYI I rebuilt and now is green

**Review by AaronHForgeFlow — COMMENTED** [review]
It works well, the creation and the modification of the Invoices and also when duplicating. Only one think. For For previous Invoices the sequence is 10 for all the lines (See picture). I'm thinking about a pre-init hook to force update old sale orders in the database. Do you agree with me?

image

**Comment by serpentcs-dev1** [comment]
@aheficent Right yes, I'll do the needful.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional + code :ok_hand:

**Comment by serpentcs-dev1** [comment]
Now it works fine, the post-Init resets the sequence of the existing invoice lines. 

Thanks @aheficent  for your review!

screenshot from 2017-06-29 16-06-01

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1: 

Thanks for the work!

**Pull request merged**
