### PR TITLE
[16.0][IMP] account_global_discount: exclude products from global disc

### PR DESCRIPTION
**Pull request by ferran-S73**
Depends on https://github.com/OCA/server-backend/pull/221

### CODE REVIEW

**Comment by ferran-S73** [comment]
Hi @pedrobaeza, I've added the m2m field in the global discounts as suggested, however after a bit of testing I find it a bit confusing to use now.

Normally this module adds a table on the invoice in which the base before discount field gets decreased so it's easy to see which discount has been applied.
After my modification I've tweaked it so that this field shows the actual amount it's used to calculate the discount and so I've found some instances where this amount increases from one line to another leading to some confusion.

I'll show one example, in my invoice I have 2 global discounts (disc1 and disc2) and 2 product lines (product1 and product2) with the same tax. I put product2 on the excluded products for disc1 so my invoice line table and global discount table look like this:
imagen
imagen
As you can see the base for disc2 is greater than the base from disc1 even though it is applied after disc1 because for the first discount 1 product line is ignored.


I think this is over complicating the module a bit but technically is doable as you can see, so I'd like your opinion on whether this is functionally correct. Thanks in advance

**Comment by pedrobaeza** [comment]
OK, let's keep the flag by product to avoid that situations.

**Comment by QuocDuong1306** [comment]
Hello @ferran-S73 , maybe you need to update [test-requirements.txt](https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29) to check the tests

**Review by cyrilmanuel — APPROVED** [review]

**Comment by mariancuadranetkia** [comment]
Hello @ferran-S73 ,
I'm testing it in runboat, but it's returning an error about **bypass_global_discount** field (it not exists) when I try to create invoice with global discount... 
I've checked and module _base_global_discount_ is installed.. so, I'm not sure about the reason, it's possible that you need update test-requirements?

imagen


Thanks!

**Comment by ferran-S73** [comment]
> Hello @ferran-S73 , I'm testing it in runboat, but it's returning an error about **bypass_global_discount** field (it not exists) when I try to create invoice with global discount... I've checked and module _base_global_discount_ is installed.. so, I'm not sure about the reason, it's possible that you need update test-requirements?
> 
> imagen
> 
> Thanks!

@mariancuadranetkia the PR that this one depends on is already merged so maybe just the runboat needs to be rebuild or something. I don't think I need to add test-requirements for a merged pr. Maybe a maintainer can help in here I don't really know. If there is something I can do please let me know

**Comment by pedrobaeza** [comment]
Try to rebase + forced push to force runboat rebuild.

**Comment by ferran-S73** [comment]
@mariancuadranetkia runboat should be ready now. @pedrobaeza thanks for the tip!

**Comment by mariancuadranetkia** [comment]
@ferran-S73 perfect! Now I could test it and runs ok!

**Review by mariancuadranetkia — APPROVED** [review]
LGTM

**Pull request merged**
