### PR TITLE
[15.0][MIG] account_invoice_triple_discount

### PR DESCRIPTION
**Pull request by ramiadavid**
@yajo @rafaelbn please review if you want

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Work seems good. Travis is currently failing because of another module

**Comment by MiquelRForgeFlow** [comment]
please rebase, tests are solved

**Comment by ramiadavid** [comment]
done

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by leemannd** [comment]
Hello,
Can someone from @OCA/accounting-maintainers take a quick look? It would be great to have it merged.
Thank you

**Pull request merged**
