### PR TITLE
[15.0][MIG] account_invoice_refund_reason

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by JaumeBforgeFlow** [comment]
Hi @ChrisOForgeFlow, could you please add the fix on #1355.

**Comment by ChrisOForgeFlow** [comment]
> Hi @ChrisOForgeFlow, could you please add the fix on #1355.

Done!

**Comment by ChrisOForgeFlow** [comment]
> > Hi @ChrisOForgeFlow, could you please add the fix on #1355.
> 
> Done!

I reverted, because I think your fix don't apply for this version, or maybe need another kind of change for this version

**Review by JaumeBforgeFlow — APPROVED** [review]
Code + functional review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

**Pull request merged**
