### PR TITLE
[MIG][11.0] account_invoice_transmit_method: Migration to v11.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Review by pedrobaeza — APPROVED** [review]
Once the squash is done

**Comment by sergio-teruel** [comment]
OCA Transbot squashed

**Comment by pedrobaeza** [comment]
OK, let's merge it as this has been around too much time. /ocabot merge

**Pull request merged**
