### PR TITLE
[13.0][MIG] sale_order_invoicing_qty_percentage: Backport from 14.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
Backport from #1384

**Sales order invoicing by percentage of the quantity**

This module allows to invoice a percentage of the sales order, modifying invoiced quantities according such percentage.

Example: You have a service line to invoice 10 hours. You choose to invoice a 50% of the quantity, so the generated invoice line has 5 hours.

@Tecnativa TT41828

### CODE REVIEW

**Comment by NL66278** [comment]
@sbidoul runboat sometimes fails which some message about a missing addons command. have you any idea what might be the cause?
Example: https://runboat.odoo-community.org/api/v1/builds/b35cac2fd-0f51-4f00-a603-20604385dc8b/init-log

**Comment by sbidoul** [comment]
@NL66278 thanks for the heads up. It's an unexpected effect of https://github.com/OCA/oca-ci/pull/44, fixed in https://github.com/sbidoul/runboat/commit/5d95b19bc12e8e563a3ca7e4cc7de043b77853b2 and deployed on the OCA server.

**Comment by NL66278** [comment]
@sbidoul Thanks for your quick solution!

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
